const rgb = (token) => `rgb(var(--${token}))`;

export const color = {
  primary: {
    main: rgb('c-primary-main'),
    hover: rgb('c-primary-hover'),
  },
  gray: {
    light: rgb('c-gray-light'),
    c_eee: rgb('c-gray-eee'),
    c_ddd: rgb('c-gray-ddd'),
    c_ccc: rgb('c-gray-ccc'),
    c_bbb: rgb('c-gray-bbb'),
    c_aaa: rgb('c-gray-aaa'),
    c_999: rgb('c-gray-999'),
    c_666: rgb('c-gray-666'),
    c_333: rgb('c-gray-333'),
    dark: rgb('c-gray-dark'),
  },
  brand: {
    main: rgb('c-brand-main'),
    sub1: rgb('c-brand-sub1'),
    sub2: rgb('c-brand-sub2'),
    point: rgb('c-brand-point'),
  },
  text: {
    main: rgb('c-text-main'),
    sub: rgb('c-text-sub'),
    sub1: rgb('c-text-sub1'),
    sub2: rgb('c-text-sub2'),
    white: rgb('c-text-white'),
    light: rgb('c-text-light'),
    default: rgb('c-text-default'),
    dark: rgb('c-text-dark'),
    darken: rgb('c-text-darken'),
    black: rgb('c-text-black'),
    point: rgb('c-text-point'),
    disabled: rgb('c-text-disabled'),
    disabledDark: rgb('c-text-disabled-dark'),
  },
  border: {
    default: rgb('c-border-default'),
    main: rgb('c-border-main'),
	sub1: rgb('c-border-sub1'),
    sub2: rgb('c-border-sub2'),
    point: rgb('c-border-point'),
    dark: rgb('c-border-dark'),
    white: rgb('c-border-white'),
    black: rgb('c-border-black'),
    disabled: rgb('c-border-disabled'),
    disabledDark: rgb('c-border-disabled-dark'),
  },
  background: {
    main: rgb('c-background-main'),
    mainLight: rgb('c-background-main-light'),
	sub1: rgb('c-background-sub1'),
    sub2: rgb('c-background-sub2'),
    white: rgb('c-background-white'),
    offwhite: rgb('c-background-offwhite'),
    divider: rgb('c-background-divider'),
    disabled: rgb('c-background-disabled'),
    readonly: rgb('c-background-readonly'),
    disabledDark: rgb('c-background-disabled-dark'),
  },
  calendar: {
    sun: rgb('c-calendar-sun'),
    sat: rgb('c-calendar-sat'),
    hover: rgb('c-calendar-hover'),
  },
  state: {
    error: rgb('c-state-error'),
    caution: rgb('c-state-caution'),
  },
  delete: rgb('c-delete'),
};

export {
  main,
  sub,
  sub1,
  sub2,
  hover,
  light,
  c_eee,
  c_ddd,
  c_ccc,
  c_bbb,
  c_aaa,
  dark,
  darken,
  white,
  black,
  point,
  disabled,
  disabledDark,
  def,
  mainLight,
  offwhite,
  divider,
  readonly,
  error,
  sun,
  sat,
  del,
} from './tokenKeys';
