/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.apiGateway.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * PredicateStoreRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PredicateStoreRequestDto {

  /**
   * Predicate 유형
   */
  public enum PredicateTypeEnum {
    COOKIE("COOKIE"),
    
    HEADER("HEADER"),
    
    METHOD("METHOD"),
    
    PATH("PATH"),
    
    HOST("HOST"),
    
    QUERY("QUERY"),
    
    WEIGHT("WEIGHT");

    private String value;

    PredicateTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PredicateTypeEnum fromValue(String value) {
      for (PredicateTypeEnum b : PredicateTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private PredicateTypeEnum predicateType;

  private String key;

  private String definition;

  /**
   * Predicate 상태
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;


  public PredicateStoreRequestDto predicateType(PredicateTypeEnum predicateType) {
    this.predicateType = predicateType;
    return this;
  }

  /**
   * Predicate 유형
   * @return predicateType
  */
  @NotNull 
  @ApiModelProperty(example = "PATH", required = true, value = "Predicate 유형")
  @JsonProperty("predicateType")
  public PredicateTypeEnum getPredicateType() {
    return predicateType;
  }

  public void setPredicateType(PredicateTypeEnum predicateType) {
    this.predicateType = predicateType;
  }

  public PredicateStoreRequestDto key(String key) {
    this.key = key;
    return this;
  }

  /**
   * Predicate Key
   * @return key
  */
  @NotNull 
  @ApiModelProperty(example = "X-Request-ID", required = true, value = "Predicate Key")
  @JsonProperty("key")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public PredicateStoreRequestDto definition(String definition) {
    this.definition = definition;
    return this;
  }

  /**
   * Predicate 정의
   * @return definition
  */
  @NotNull 
  @ApiModelProperty(example = "ABCD", required = true, value = "Predicate 정의")
  @JsonProperty("definition")
  public String getDefinition() {
    return definition;
  }

  public void setDefinition(String definition) {
    this.definition = definition;
  }

  public PredicateStoreRequestDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Predicate 상태
   * @return status
  */
  @NotNull 
  @ApiModelProperty(example = "ENABLE", required = true, value = "Predicate 상태")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredicateStoreRequestDto predicateStoreRequestDto = (PredicateStoreRequestDto) o;
    return Objects.equals(this.predicateType, predicateStoreRequestDto.predicateType) &&
        Objects.equals(this.key, predicateStoreRequestDto.key) &&
        Objects.equals(this.definition, predicateStoreRequestDto.definition) &&
        Objects.equals(this.status, predicateStoreRequestDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(predicateType, key, definition, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredicateStoreRequestDto {\n");
    sb.append("    predicateType: ").append(toIndentedString(predicateType)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
