/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.apiGateway.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.apiGateway.interfaces.inboundAdapter.spec.PredicateResponseDto;
import com.winitech.apiGateway.interfaces.inboundAdapter.spec.PredicateStoreRequestDto;
import com.winitech.apiGateway.interfaces.inboundAdapter.spec.PredicateStoreResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "Predicate", value = "Predicate", description = "Predicate Controller")
@RequestMapping("/api/v1/api-gateway")
public interface PredicateApi {

    /**
     * PATCH /route/{routeId}/predicate/{predicateId} : predicate 수정
     * Predicate를 수정합니다.
     *
     * @param routeId Route ID (required)
     * @param predicateId Predicate ID (required)
     * @param predicateStoreRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Predicate" },
        value = "predicate 수정",
        nickname = "modifyPredicate",
        notes = "Predicate를 수정합니다.",
        response = PredicateStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = PredicateStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/route/{routeId}/predicate/{predicateId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<PredicateStoreResponseDto> modifyPredicate(
        @ApiParam(value = "Route ID", required = true) @PathVariable("routeId") UUID routeId,
        @ApiParam(value = "Predicate ID", required = true) @PathVariable("predicateId") UUID predicateId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) PredicateStoreRequestDto predicateStoreRequestDto
    );


    /**
     * POST /route/{routeId}/predicate : predicate 등록
     * predicate를 등록합니다.
     *
     * @param routeId Route ID (required)
     * @param predicateStoreRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Predicate" },
        value = "predicate 등록",
        nickname = "registerPredicate",
        notes = "predicate를 등록합니다.",
        response = PredicateStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = PredicateStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/route/{routeId}/predicate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<PredicateStoreResponseDto> registerPredicate(
        @ApiParam(value = "Route ID", required = true) @PathVariable("routeId") UUID routeId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) PredicateStoreRequestDto predicateStoreRequestDto
    );


    /**
     * DELETE /route/{routeId}/predicate/{predicateId} : predicate 삭제
     * Predicate를 삭제합니다.
     *
     * @param routeId Route ID (required)
     * @param predicateId Predicate ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Predicate" },
        value = "predicate 삭제",
        nickname = "removePredicate",
        notes = "Predicate를 삭제합니다.",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/route/{routeId}/predicate/{predicateId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removePredicate(
        @ApiParam(value = "Route ID", required = true) @PathVariable("routeId") UUID routeId,
        @ApiParam(value = "Predicate ID", required = true) @PathVariable("predicateId") UUID predicateId
    );


    /**
     * GET /route/{routeId}/predicate : predicate 목록조회
     * Predicate 목록을 조회합니다.
     *
     * @param routeId Route ID (required)
     * @param page 페이지 번호 (0부터 시작) (optional)
     * @param pageSize 페이지 사이즈 (optional)
     * @param searchType 검색유형 (optional)
     * @param searchKeyword 검색어 (optional)
     * @param searchStatus 상태 (optional)
     * @param searchPredicateType Predicate 유형 (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Predicate" },
        value = "predicate 목록조회",
        nickname = "searchAllPredicate",
        notes = "Predicate 목록을 조회합니다.",
        response = PredicateResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = PredicateResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/route/{routeId}/predicate",
        produces = { "application/json" }
    )
    CommonResponse<List<PredicateResponseDto>> searchAllPredicate(
        @ApiParam(value = "Route ID", required = true) @PathVariable("routeId") UUID routeId,
        @ApiParam(value = "페이지 번호 (0부터 시작)") @Valid @RequestParam(value = "page", required = false) Integer page,
        @ApiParam(value = "페이지 사이즈") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,
        @ApiParam(value = "검색유형", allowableValues = "NAME, URI") @Valid @RequestParam(value = "searchType", required = false) String searchType,
        @ApiParam(value = "검색어") @Valid @RequestParam(value = "searchKeyword", required = false) String searchKeyword,
        @ApiParam(value = "상태", allowableValues = "ENABLE, DISABLE") @Valid @RequestParam(value = "searchStatus", required = false) String searchStatus,
        @ApiParam(value = "Predicate 유형", allowableValues = "COOKIE, HEADER, METHOD, PATH, HOST, QUERY, WEIGHT") @Valid @RequestParam(value = "searchPredicateType", required = false) String searchPredicateType
    );


    /**
     * POST /route/{routeId}/predicate/{predicateId} : predicate 조회
     * predicate를 조회
     *
     * @param routeId Route ID (required)
     * @param predicateId Predicate ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Predicate" },
        value = "predicate 조회",
        nickname = "searchPredicateInfo",
        notes = "predicate를 조회",
        response = PredicateResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = PredicateResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/route/{routeId}/predicate/{predicateId}",
        produces = { "application/json" }
    )
    CommonResponse<PredicateResponseDto> searchPredicateInfo(
        @ApiParam(value = "Route ID", required = true) @PathVariable("routeId") UUID routeId,
        @ApiParam(value = "Predicate ID", required = true) @PathVariable("predicateId") UUID predicateId
    );

}
