/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.apiGateway.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * PredicateStoreResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PredicateStoreResponseDto {

  private UUID predicateId;

  public PredicateStoreResponseDto predicateId(UUID predicateId) {
    this.predicateId = predicateId;
    return this;
  }

  /**
   * Predicate ID
   * @return predicateId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "Predicate ID")
  @JsonProperty("predicateId")
  public UUID getPredicateId() {
    return predicateId;
  }

  public void setPredicateId(UUID predicateId) {
    this.predicateId = predicateId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredicateStoreResponseDto predicateStoreResponseDto = (PredicateStoreResponseDto) o;
    return Objects.equals(this.predicateId, predicateStoreResponseDto.predicateId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(predicateId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredicateStoreResponseDto {\n");
    sb.append("    predicateId: ").append(toIndentedString(predicateId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
