log4jdbc.spylogdelegator.name=com.winitech.common.library.log.Log4jdbcSpyLogDelegator

log4jdbc.dump.sql.select = true
log4jdbc.dump.sql.insert = true
log4jdbc.dump.sql.update = true
log4jdbc.dump.sql.delete = true
log4jdbc.dump.sql.create = true

log4jdbc.dump.sql.maxlinelength = 200

log4jdbc.dump.sql.addsemicolon = true
log4jdbc.trim.sql = true
log4jdbc.trim.sql.extrablanklines = true
