pluginManagement {
    repositories {
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
        gradlePluginPortal()
    }
}
rootProject.name = 'smart-asset'

// common 모듈 포함
include 'common'
project(':common').projectDir = new File('../common')