# -------------
# builder stage
# -------------

FROM node:20.16.0-bullseye AS builder

# 필요 패키지 설치
RUN apt-get update && apt-get install -y gzip

WORKDIR /app

# package.json, package-lock.json 복사
COPY package*.json ./

# npm 패키지 설치
RUN npm ci --no-audit --no-fund --no-progress 

ARG VITE_INTERNAL_URL=//dev-portal.cloud-winitech.com
ENV VITE_INTERNAL_URL=$VITE_INTERNAL_URL

# 소스코드 복사
COPY . .

# 빌드 및 .js, .css 파일 gzip 압축
RUN DISABLE_ESLINT_PLUGIN=true npm run build

RUN find ./dist -type f \( -name "*.js" -or -name "*.css" \) -size +100c -exec gzip --keep -9 "{}" \; && find ./dist -type f -name "*.map" -exec rm "{}" \;

# ----------------
# production stage
# ----------------

# 최신 버전 nginx 이미지 사용
FROM nginx:alpine-slim  

EXPOSE 8080

# nginx 설정 파일 복사
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app

# 배포 파일 디렉터리 생성
RUN mkdir ./build

# builder stage에서 빌드한 파일을 production stage로 복사
COPY --from=builder /app/dist ./build

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]
