/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AcknowledgementApprovalResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AcknowledgementApprovalResponseDto {

  private UUID acknowledgementApprovalId;

  /**
   * Gets or Sets approvalStep
   */
  public enum ApprovalStepEnum {
    EMPLOYEE("EMPLOYEE"),
    
    MANAGER("MANAGER");

    private String value;

    ApprovalStepEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ApprovalStepEnum fromValue(String value) {
      for (ApprovalStepEnum b : ApprovalStepEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ApprovalStepEnum approvalStep;

  private UUID approvedBy;

  private OffsetDateTime approvedAt;

  private String approverIpMasked;

  private String assetSnapshot;

  /**
   * Gets or Sets returnCondition
   */
  public enum ReturnConditionEnum {
    NORMAL("NORMAL"),
    
    ABNORMAL("ABNORMAL");

    private String value;

    ReturnConditionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReturnConditionEnum fromValue(String value) {
      for (ReturnConditionEnum b : ReturnConditionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ReturnConditionEnum returnCondition;

  /**
   * Gets or Sets nextLifeStatus
   */
  public enum NextLifeStatusEnum {
    USE("USE"),
    
    STORAGE("STORAGE"),
    
    REPAIR("REPAIR"),
    
    DISUSE("DISUSE"),
    
    DISPOSED("DISPOSED");

    private String value;

    NextLifeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NextLifeStatusEnum fromValue(String value) {
      for (NextLifeStatusEnum b : NextLifeStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private NextLifeStatusEnum nextLifeStatus;

  /**
   * Gets or Sets nextAssignType
   */
  public enum NextAssignTypeEnum {
    UNASSIGNED("UNASSIGNED"),
    
    PERSONAL("PERSONAL"),
    
    SHARED("SHARED"),
    
    LOANABLE("LOANABLE"),
    
    ON_LOAN("ON_LOAN");

    private String value;

    NextAssignTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NextAssignTypeEnum fromValue(String value) {
      for (NextAssignTypeEnum b : NextAssignTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private NextAssignTypeEnum nextAssignType;

  public AcknowledgementApprovalResponseDto acknowledgementApprovalId(UUID acknowledgementApprovalId) {
    this.acknowledgementApprovalId = acknowledgementApprovalId;
    return this;
  }

  /**
   * Get acknowledgementApprovalId
   * @return acknowledgementApprovalId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("acknowledgementApprovalId")
  public UUID getAcknowledgementApprovalId() {
    return acknowledgementApprovalId;
  }

  public void setAcknowledgementApprovalId(UUID acknowledgementApprovalId) {
    this.acknowledgementApprovalId = acknowledgementApprovalId;
  }

  public AcknowledgementApprovalResponseDto approvalStep(ApprovalStepEnum approvalStep) {
    this.approvalStep = approvalStep;
    return this;
  }

  /**
   * Get approvalStep
   * @return approvalStep
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("approvalStep")
  public ApprovalStepEnum getApprovalStep() {
    return approvalStep;
  }

  public void setApprovalStep(ApprovalStepEnum approvalStep) {
    this.approvalStep = approvalStep;
  }

  public AcknowledgementApprovalResponseDto approvedBy(UUID approvedBy) {
    this.approvedBy = approvedBy;
    return this;
  }

  /**
   * Get approvedBy
   * @return approvedBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("approvedBy")
  public UUID getApprovedBy() {
    return approvedBy;
  }

  public void setApprovedBy(UUID approvedBy) {
    this.approvedBy = approvedBy;
  }

  public AcknowledgementApprovalResponseDto approvedAt(OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
    return this;
  }

  /**
   * Get approvedAt
   * @return approvedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("approvedAt")
  public OffsetDateTime getApprovedAt() {
    return approvedAt;
  }

  public void setApprovedAt(OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
  }

  public AcknowledgementApprovalResponseDto approverIpMasked(String approverIpMasked) {
    this.approverIpMasked = approverIpMasked;
    return this;
  }

  /**
   * K2 증빙 - 부분 마스킹된 접속 IP (예 192.168.*.*)
   * @return approverIpMasked
  */
  
  @ApiModelProperty(value = "K2 증빙 - 부분 마스킹된 접속 IP (예 192.168.*.*)")
  @JsonProperty("approverIpMasked")
  public String getApproverIpMasked() {
    return approverIpMasked;
  }

  public void setApproverIpMasked(String approverIpMasked) {
    this.approverIpMasked = approverIpMasked;
  }

  public AcknowledgementApprovalResponseDto assetSnapshot(String assetSnapshot) {
    this.assetSnapshot = assetSnapshot;
    return this;
  }

  /**
   * Get assetSnapshot
   * @return assetSnapshot
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("assetSnapshot")
  public String getAssetSnapshot() {
    return assetSnapshot;
  }

  public void setAssetSnapshot(String assetSnapshot) {
    this.assetSnapshot = assetSnapshot;
  }

  public AcknowledgementApprovalResponseDto returnCondition(ReturnConditionEnum returnCondition) {
    this.returnCondition = returnCondition;
    return this;
  }

  /**
   * Get returnCondition
   * @return returnCondition
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("returnCondition")
  public ReturnConditionEnum getReturnCondition() {
    return returnCondition;
  }

  public void setReturnCondition(ReturnConditionEnum returnCondition) {
    this.returnCondition = returnCondition;
  }

  public AcknowledgementApprovalResponseDto nextLifeStatus(NextLifeStatusEnum nextLifeStatus) {
    this.nextLifeStatus = nextLifeStatus;
    return this;
  }

  /**
   * Get nextLifeStatus
   * @return nextLifeStatus
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("nextLifeStatus")
  public NextLifeStatusEnum getNextLifeStatus() {
    return nextLifeStatus;
  }

  public void setNextLifeStatus(NextLifeStatusEnum nextLifeStatus) {
    this.nextLifeStatus = nextLifeStatus;
  }

  public AcknowledgementApprovalResponseDto nextAssignType(NextAssignTypeEnum nextAssignType) {
    this.nextAssignType = nextAssignType;
    return this;
  }

  /**
   * Get nextAssignType
   * @return nextAssignType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("nextAssignType")
  public NextAssignTypeEnum getNextAssignType() {
    return nextAssignType;
  }

  public void setNextAssignType(NextAssignTypeEnum nextAssignType) {
    this.nextAssignType = nextAssignType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcknowledgementApprovalResponseDto acknowledgementApprovalResponseDto = (AcknowledgementApprovalResponseDto) o;
    return Objects.equals(this.acknowledgementApprovalId, acknowledgementApprovalResponseDto.acknowledgementApprovalId) &&
        Objects.equals(this.approvalStep, acknowledgementApprovalResponseDto.approvalStep) &&
        Objects.equals(this.approvedBy, acknowledgementApprovalResponseDto.approvedBy) &&
        Objects.equals(this.approvedAt, acknowledgementApprovalResponseDto.approvedAt) &&
        Objects.equals(this.approverIpMasked, acknowledgementApprovalResponseDto.approverIpMasked) &&
        Objects.equals(this.assetSnapshot, acknowledgementApprovalResponseDto.assetSnapshot) &&
        Objects.equals(this.returnCondition, acknowledgementApprovalResponseDto.returnCondition) &&
        Objects.equals(this.nextLifeStatus, acknowledgementApprovalResponseDto.nextLifeStatus) &&
        Objects.equals(this.nextAssignType, acknowledgementApprovalResponseDto.nextAssignType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acknowledgementApprovalId, approvalStep, approvedBy, approvedAt, approverIpMasked, assetSnapshot, returnCondition, nextLifeStatus, nextAssignType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcknowledgementApprovalResponseDto {\n");
    sb.append("    acknowledgementApprovalId: ").append(toIndentedString(acknowledgementApprovalId)).append("\n");
    sb.append("    approvalStep: ").append(toIndentedString(approvalStep)).append("\n");
    sb.append("    approvedBy: ").append(toIndentedString(approvedBy)).append("\n");
    sb.append("    approvedAt: ").append(toIndentedString(approvedAt)).append("\n");
    sb.append("    approverIpMasked: ").append(toIndentedString(approverIpMasked)).append("\n");
    sb.append("    assetSnapshot: ").append(toIndentedString(assetSnapshot)).append("\n");
    sb.append("    returnCondition: ").append(toIndentedString(returnCondition)).append("\n");
    sb.append("    nextLifeStatus: ").append(toIndentedString(nextLifeStatus)).append("\n");
    sb.append("    nextAssignType: ").append(toIndentedString(nextAssignType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
