/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AcknowledgementRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AcknowledgementRegisterRequestDto {

  private UUID tangibleAssetId;

  private UUID memberId;

  private String memberName;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    RECEIPT("RECEIPT"),
    
    RETURN("RETURN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private TypeEnum type;

  private String managerName;


  public AcknowledgementRegisterRequestDto tangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
    return this;
  }

  /**
   * Get tangibleAssetId
   * @return tangibleAssetId
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("tangibleAssetId")
  public UUID getTangibleAssetId() {
    return tangibleAssetId;
  }

  public void setTangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
  }

  public AcknowledgementRegisterRequestDto memberId(UUID memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Get memberId
   * @return memberId
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("memberId")
  public UUID getMemberId() {
    return memberId;
  }

  public void setMemberId(UUID memberId) {
    this.memberId = memberId;
  }

  public AcknowledgementRegisterRequestDto memberName(String memberName) {
    this.memberName = memberName;
    return this;
  }

  /**
   * 프런트가 이미 로드한 사용자 목록에서 넘겨주는 표시용 이름 - 문서 스냅샷의 {{대상자}}에 쓰인다
   * @return memberName
  */
  
  @ApiModelProperty(value = "프런트가 이미 로드한 사용자 목록에서 넘겨주는 표시용 이름 - 문서 스냅샷의 {{대상자}}에 쓰인다")
  @JsonProperty("memberName")
  public String getMemberName() {
    return memberName;
  }

  public void setMemberName(String memberName) {
    this.memberName = memberName;
  }

  public AcknowledgementRegisterRequestDto type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("type")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AcknowledgementRegisterRequestDto managerName(String managerName) {
    this.managerName = managerName;
    return this;
  }

  /**
   * 문서 스냅샷의 {{담당자}}에 쓰인다
   * @return managerName
  */
  
  @ApiModelProperty(value = "문서 스냅샷의 {{담당자}}에 쓰인다")
  @JsonProperty("managerName")
  public String getManagerName() {
    return managerName;
  }

  public void setManagerName(String managerName) {
    this.managerName = managerName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcknowledgementRegisterRequestDto acknowledgementRegisterRequestDto = (AcknowledgementRegisterRequestDto) o;
    return Objects.equals(this.tangibleAssetId, acknowledgementRegisterRequestDto.tangibleAssetId) &&
        Objects.equals(this.memberId, acknowledgementRegisterRequestDto.memberId) &&
        Objects.equals(this.memberName, acknowledgementRegisterRequestDto.memberName) &&
        Objects.equals(this.type, acknowledgementRegisterRequestDto.type) &&
        Objects.equals(this.managerName, acknowledgementRegisterRequestDto.managerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tangibleAssetId, memberId, memberName, type, managerName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcknowledgementRegisterRequestDto {\n");
    sb.append("    tangibleAssetId: ").append(toIndentedString(tangibleAssetId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    memberName: ").append(toIndentedString(memberName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    managerName: ").append(toIndentedString(managerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
