/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetCategoryIdResponseDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetCategoryModifyRequestDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetCategoryRegisterRequestDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetCategoryResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "AssetCategory", value = "AssetCategory", description = "자산 종류 관리 (S-200)")
@RequestMapping("/api/v1/smart-asset")
public interface AssetCategoryApi {

    /**
     * PATCH /asset-category/{categoryId} : 자산 종류 수정
     * 자산 종류를 수정합니다. (종류 코드는 수정 불가)
     *
     * @param categoryId 자산 종류 ID (required)
     * @param assetCategoryModifyRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetCategory" },
        value = "자산 종류 수정",
        nickname = "modifyAssetCategory",
        notes = "자산 종류를 수정합니다. (종류 코드는 수정 불가)",
        response = AssetCategoryIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetCategoryIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/asset-category/{categoryId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<AssetCategoryIdResponseDto> modifyAssetCategory(
        @ApiParam(value = "자산 종류 ID", required = true) @PathVariable("categoryId") UUID categoryId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) AssetCategoryModifyRequestDto assetCategoryModifyRequestDto
    );


    /**
     * POST /asset-category : 자산 종류 등록
     * 자산 종류를 등록합니다.
     *
     * @param assetCategoryRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetCategory" },
        value = "자산 종류 등록",
        nickname = "registerAssetCategory",
        notes = "자산 종류를 등록합니다.",
        response = AssetCategoryIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetCategoryIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/asset-category",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<AssetCategoryIdResponseDto> registerAssetCategory(
        @ApiParam(value = "") @Valid @RequestBody(required = false) AssetCategoryRegisterRequestDto assetCategoryRegisterRequestDto
    );


    /**
     * DELETE /asset-category/{categoryId} : 자산 종류 삭제
     * 자산 종류를 삭제(사용 해제)합니다. 기본 제공 4종은 삭제할 수 없습니다.
     *
     * @param categoryId 자산 종류 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetCategory" },
        value = "자산 종류 삭제",
        nickname = "removeAssetCategory",
        notes = "자산 종류를 삭제(사용 해제)합니다. 기본 제공 4종은 삭제할 수 없습니다.",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/asset-category/{categoryId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removeAssetCategory(
        @ApiParam(value = "자산 종류 ID", required = true) @PathVariable("categoryId") UUID categoryId
    );


    /**
     * GET /asset-category : 자산 종류 목록 조회
     * 자산 종류 목록을 조회합니다.
     *
     * @param keyword  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetCategory" },
        value = "자산 종류 목록 조회",
        nickname = "searchAllAssetCategory",
        notes = "자산 종류 목록을 조회합니다.",
        response = AssetCategoryResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetCategoryResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/asset-category",
        produces = { "application/json" }
    )
    CommonResponse<List<AssetCategoryResponseDto>> searchAllAssetCategory(
        @ApiParam(value = "") @Valid @RequestParam(value = "keyword", required = false) String keyword
    );


    /**
     * GET /asset-category/{categoryId} : 자산 종류 상세 조회
     * 자산 종류의 상세정보를 조회합니다.
     *
     * @param categoryId 자산 종류 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetCategory" },
        value = "자산 종류 상세 조회",
        nickname = "searchAssetCategory",
        notes = "자산 종류의 상세정보를 조회합니다.",
        response = AssetCategoryResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetCategoryResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/asset-category/{categoryId}",
        produces = { "application/json" }
    )
    CommonResponse<AssetCategoryResponseDto> searchAssetCategory(
        @ApiParam(value = "자산 종류 ID", required = true) @PathVariable("categoryId") UUID categoryId
    );

}
