/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AssetLocationResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AssetLocationResponseDto {

  private UUID locationId;

  private String locationName;

  private Integer sortSeq;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  public AssetLocationResponseDto locationId(UUID locationId) {
    this.locationId = locationId;
    return this;
  }

  /**
   * Get locationId
   * @return locationId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("locationId")
  public UUID getLocationId() {
    return locationId;
  }

  public void setLocationId(UUID locationId) {
    this.locationId = locationId;
  }

  public AssetLocationResponseDto locationName(String locationName) {
    this.locationName = locationName;
    return this;
  }

  /**
   * Get locationName
   * @return locationName
  */
  
  @ApiModelProperty(example = "본사", value = "")
  @JsonProperty("locationName")
  public String getLocationName() {
    return locationName;
  }

  public void setLocationName(String locationName) {
    this.locationName = locationName;
  }

  public AssetLocationResponseDto sortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
    return this;
  }

  /**
   * Get sortSeq
   * @return sortSeq
  */
  
  @ApiModelProperty(example = "1", value = "")
  @JsonProperty("sortSeq")
  public Integer getSortSeq() {
    return sortSeq;
  }

  public void setSortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
  }

  public AssetLocationResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetLocationResponseDto assetLocationResponseDto = (AssetLocationResponseDto) o;
    return Objects.equals(this.locationId, assetLocationResponseDto.locationId) &&
        Objects.equals(this.locationName, assetLocationResponseDto.locationName) &&
        Objects.equals(this.sortSeq, assetLocationResponseDto.sortSeq) &&
        Objects.equals(this.status, assetLocationResponseDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationId, locationName, sortSeq, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetLocationResponseDto {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationName: ").append(toIndentedString(locationName)).append("\n");
    sb.append("    sortSeq: ").append(toIndentedString(sortSeq)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
