/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetLocationIdResponseDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetLocationModifyRequestDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetLocationRegisterRequestDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.AssetLocationResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "AssetLocation", value = "AssetLocation", description = "자산 위치 관리 (S-201)")
@RequestMapping("/api/v1/smart-asset")
public interface AssetLocationApi {

    /**
     * PATCH /asset-location/{locationId} : 자산 위치 수정
     * 자산 위치를 수정합니다.
     *
     * @param locationId 자산 위치 ID (required)
     * @param assetLocationModifyRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetLocation" },
        value = "자산 위치 수정",
        nickname = "modifyAssetLocation",
        notes = "자산 위치를 수정합니다.",
        response = AssetLocationIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetLocationIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/asset-location/{locationId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<AssetLocationIdResponseDto> modifyAssetLocation(
        @ApiParam(value = "자산 위치 ID", required = true) @PathVariable("locationId") UUID locationId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) AssetLocationModifyRequestDto assetLocationModifyRequestDto
    );


    /**
     * POST /asset-location : 자산 위치 등록
     * 자산 위치를 등록합니다.
     *
     * @param assetLocationRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetLocation" },
        value = "자산 위치 등록",
        nickname = "registerAssetLocation",
        notes = "자산 위치를 등록합니다.",
        response = AssetLocationIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetLocationIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/asset-location",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<AssetLocationIdResponseDto> registerAssetLocation(
        @ApiParam(value = "") @Valid @RequestBody(required = false) AssetLocationRegisterRequestDto assetLocationRegisterRequestDto
    );


    /**
     * DELETE /asset-location/{locationId} : 자산 위치 삭제
     * 자산 위치를 삭제(사용 해제)합니다.
     *
     * @param locationId 자산 위치 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetLocation" },
        value = "자산 위치 삭제",
        nickname = "removeAssetLocation",
        notes = "자산 위치를 삭제(사용 해제)합니다.",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/asset-location/{locationId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removeAssetLocation(
        @ApiParam(value = "자산 위치 ID", required = true) @PathVariable("locationId") UUID locationId
    );


    /**
     * GET /asset-location : 자산 위치 목록 조회
     * 자산 위치 목록을 조회합니다.
     *
     * @param keyword  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetLocation" },
        value = "자산 위치 목록 조회",
        nickname = "searchAllAssetLocation",
        notes = "자산 위치 목록을 조회합니다.",
        response = AssetLocationResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetLocationResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/asset-location",
        produces = { "application/json" }
    )
    CommonResponse<List<AssetLocationResponseDto>> searchAllAssetLocation(
        @ApiParam(value = "") @Valid @RequestParam(value = "keyword", required = false) String keyword
    );


    /**
     * GET /asset-location/{locationId} : 자산 위치 상세 조회
     * 자산 위치의 상세정보를 조회합니다.
     *
     * @param locationId 자산 위치 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "AssetLocation" },
        value = "자산 위치 상세 조회",
        nickname = "searchAssetLocation",
        notes = "자산 위치의 상세정보를 조회합니다.",
        response = AssetLocationResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = AssetLocationResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/asset-location/{locationId}",
        produces = { "application/json" }
    )
    CommonResponse<AssetLocationResponseDto> searchAssetLocation(
        @ApiParam(value = "자산 위치 ID", required = true) @PathVariable("locationId") UUID locationId
    );

}
