/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AssetCategoryResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AssetCategoryResponseDto {

  private UUID categoryId;

  private String categoryCode;

  private String categoryName;

  private Integer sortSeq;

  private Boolean editable;

  private Integer usefulLifeMonths;

  private BigDecimal residualRate;

  private BigDecimal memorandumValue;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  public AssetCategoryResponseDto categoryId(UUID categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * 자산 종류 ID
   * @return categoryId
  */
  @Valid 
  @ApiModelProperty(value = "자산 종류 ID")
  @JsonProperty("categoryId")
  public UUID getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(UUID categoryId) {
    this.categoryId = categoryId;
  }

  public AssetCategoryResponseDto categoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
    return this;
  }

  /**
   * 자산 종류 코드
   * @return categoryCode
  */
  
  @ApiModelProperty(example = "NOTEBOOK", value = "자산 종류 코드")
  @JsonProperty("categoryCode")
  public String getCategoryCode() {
    return categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  public AssetCategoryResponseDto categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

  /**
   * 자산 종류명
   * @return categoryName
  */
  
  @ApiModelProperty(example = "노트북", value = "자산 종류명")
  @JsonProperty("categoryName")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public AssetCategoryResponseDto sortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
    return this;
  }

  /**
   * 정렬 순서
   * @return sortSeq
  */
  
  @ApiModelProperty(example = "1", value = "정렬 순서")
  @JsonProperty("sortSeq")
  public Integer getSortSeq() {
    return sortSeq;
  }

  public void setSortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
  }

  public AssetCategoryResponseDto editable(Boolean editable) {
    this.editable = editable;
    return this;
  }

  /**
   * 기본 제공 종류 여부(false면 삭제 불가)
   * @return editable
  */
  
  @ApiModelProperty(value = "기본 제공 종류 여부(false면 삭제 불가)")
  @JsonProperty("editable")
  public Boolean getEditable() {
    return editable;
  }

  public void setEditable(Boolean editable) {
    this.editable = editable;
  }

  public AssetCategoryResponseDto usefulLifeMonths(Integer usefulLifeMonths) {
    this.usefulLifeMonths = usefulLifeMonths;
    return this;
  }

  /**
   * 내용연수(개월)
   * @return usefulLifeMonths
  */
  
  @ApiModelProperty(example = "48", value = "내용연수(개월)")
  @JsonProperty("usefulLifeMonths")
  public Integer getUsefulLifeMonths() {
    return usefulLifeMonths;
  }

  public void setUsefulLifeMonths(Integer usefulLifeMonths) {
    this.usefulLifeMonths = usefulLifeMonths;
  }

  public AssetCategoryResponseDto residualRate(BigDecimal residualRate) {
    this.residualRate = residualRate;
    return this;
  }

  /**
   * 잔존가치율(%)
   * @return residualRate
  */
  @Valid 
  @ApiModelProperty(example = "10", value = "잔존가치율(%)")
  @JsonProperty("residualRate")
  public BigDecimal getResidualRate() {
    return residualRate;
  }

  public void setResidualRate(BigDecimal residualRate) {
    this.residualRate = residualRate;
  }

  public AssetCategoryResponseDto memorandumValue(BigDecimal memorandumValue) {
    this.memorandumValue = memorandumValue;
    return this;
  }

  /**
   * 비망가액(원)
   * @return memorandumValue
  */
  @Valid 
  @ApiModelProperty(example = "1000", value = "비망가액(원)")
  @JsonProperty("memorandumValue")
  public BigDecimal getMemorandumValue() {
    return memorandumValue;
  }

  public void setMemorandumValue(BigDecimal memorandumValue) {
    this.memorandumValue = memorandumValue;
  }

  public AssetCategoryResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetCategoryResponseDto assetCategoryResponseDto = (AssetCategoryResponseDto) o;
    return Objects.equals(this.categoryId, assetCategoryResponseDto.categoryId) &&
        Objects.equals(this.categoryCode, assetCategoryResponseDto.categoryCode) &&
        Objects.equals(this.categoryName, assetCategoryResponseDto.categoryName) &&
        Objects.equals(this.sortSeq, assetCategoryResponseDto.sortSeq) &&
        Objects.equals(this.editable, assetCategoryResponseDto.editable) &&
        Objects.equals(this.usefulLifeMonths, assetCategoryResponseDto.usefulLifeMonths) &&
        Objects.equals(this.residualRate, assetCategoryResponseDto.residualRate) &&
        Objects.equals(this.memorandumValue, assetCategoryResponseDto.memorandumValue) &&
        Objects.equals(this.status, assetCategoryResponseDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryId, categoryCode, categoryName, sortSeq, editable, usefulLifeMonths, residualRate, memorandumValue, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetCategoryResponseDto {\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    categoryCode: ").append(toIndentedString(categoryCode)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    sortSeq: ").append(toIndentedString(sortSeq)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    usefulLifeMonths: ").append(toIndentedString(usefulLifeMonths)).append("\n");
    sb.append("    residualRate: ").append(toIndentedString(residualRate)).append("\n");
    sb.append("    memorandumValue: ").append(toIndentedString(memorandumValue)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
