/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardAssetSummaryDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardExpiringSoonDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardInventoryProgressDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardLicenseConsistencyDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardLoanStatusDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardMonthlyCostDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardNameCountDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DashboardTicketStatusDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DashboardSummaryResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DashboardSummaryResponseDto {

  private OffsetDateTime aggregatedAt;

  private DashboardAssetSummaryDto assetSummary;

  @Valid
  private List<@Valid DashboardNameCountDto> categoryDistribution;

  @Valid
  private List<@Valid DashboardNameCountDto> locationDistribution;

  @Valid
  private List<@Valid DashboardNameCountDto> statusDistribution;

  @Valid
  private List<@Valid DashboardMonthlyCostDto> monthlyCostTrend;

  private DashboardExpiringSoonDto expiringSoon;

  private DashboardTicketStatusDto ticketStatus;

  private DashboardLoanStatusDto loanStatus;

  @Valid
  private List<@Valid DashboardInventoryProgressDto> inventoryProgress;

  private DashboardLicenseConsistencyDto licenseConsistency;

  public DashboardSummaryResponseDto aggregatedAt(OffsetDateTime aggregatedAt) {
    this.aggregatedAt = aggregatedAt;
    return this;
  }

  /**
   * 이 응답을 계산한 시각 (D7 - 미확정 기간은 매 요청 재계산됨을 화면에 표기)
   * @return aggregatedAt
  */
  @Valid 
  @ApiModelProperty(value = "이 응답을 계산한 시각 (D7 - 미확정 기간은 매 요청 재계산됨을 화면에 표기)")
  @JsonProperty("aggregatedAt")
  public OffsetDateTime getAggregatedAt() {
    return aggregatedAt;
  }

  public void setAggregatedAt(OffsetDateTime aggregatedAt) {
    this.aggregatedAt = aggregatedAt;
  }

  public DashboardSummaryResponseDto assetSummary(DashboardAssetSummaryDto assetSummary) {
    this.assetSummary = assetSummary;
    return this;
  }

  /**
   * Get assetSummary
   * @return assetSummary
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("assetSummary")
  public DashboardAssetSummaryDto getAssetSummary() {
    return assetSummary;
  }

  public void setAssetSummary(DashboardAssetSummaryDto assetSummary) {
    this.assetSummary = assetSummary;
  }

  public DashboardSummaryResponseDto categoryDistribution(List<@Valid DashboardNameCountDto> categoryDistribution) {
    this.categoryDistribution = categoryDistribution;
    return this;
  }

  public DashboardSummaryResponseDto addCategoryDistributionItem(DashboardNameCountDto categoryDistributionItem) {
    if (this.categoryDistribution == null) {
      this.categoryDistribution = new ArrayList<>();
    }
    this.categoryDistribution.add(categoryDistributionItem);
    return this;
  }

  /**
   * Get categoryDistribution
   * @return categoryDistribution
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("categoryDistribution")
  public List<@Valid DashboardNameCountDto> getCategoryDistribution() {
    return categoryDistribution;
  }

  public void setCategoryDistribution(List<@Valid DashboardNameCountDto> categoryDistribution) {
    this.categoryDistribution = categoryDistribution;
  }

  public DashboardSummaryResponseDto locationDistribution(List<@Valid DashboardNameCountDto> locationDistribution) {
    this.locationDistribution = locationDistribution;
    return this;
  }

  public DashboardSummaryResponseDto addLocationDistributionItem(DashboardNameCountDto locationDistributionItem) {
    if (this.locationDistribution == null) {
      this.locationDistribution = new ArrayList<>();
    }
    this.locationDistribution.add(locationDistributionItem);
    return this;
  }

  /**
   * Get locationDistribution
   * @return locationDistribution
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("locationDistribution")
  public List<@Valid DashboardNameCountDto> getLocationDistribution() {
    return locationDistribution;
  }

  public void setLocationDistribution(List<@Valid DashboardNameCountDto> locationDistribution) {
    this.locationDistribution = locationDistribution;
  }

  public DashboardSummaryResponseDto statusDistribution(List<@Valid DashboardNameCountDto> statusDistribution) {
    this.statusDistribution = statusDistribution;
    return this;
  }

  public DashboardSummaryResponseDto addStatusDistributionItem(DashboardNameCountDto statusDistributionItem) {
    if (this.statusDistribution == null) {
      this.statusDistribution = new ArrayList<>();
    }
    this.statusDistribution.add(statusDistributionItem);
    return this;
  }

  /**
   * Get statusDistribution
   * @return statusDistribution
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("statusDistribution")
  public List<@Valid DashboardNameCountDto> getStatusDistribution() {
    return statusDistribution;
  }

  public void setStatusDistribution(List<@Valid DashboardNameCountDto> statusDistribution) {
    this.statusDistribution = statusDistribution;
  }

  public DashboardSummaryResponseDto monthlyCostTrend(List<@Valid DashboardMonthlyCostDto> monthlyCostTrend) {
    this.monthlyCostTrend = monthlyCostTrend;
    return this;
  }

  public DashboardSummaryResponseDto addMonthlyCostTrendItem(DashboardMonthlyCostDto monthlyCostTrendItem) {
    if (this.monthlyCostTrend == null) {
      this.monthlyCostTrend = new ArrayList<>();
    }
    this.monthlyCostTrend.add(monthlyCostTrendItem);
    return this;
  }

  /**
   * Get monthlyCostTrend
   * @return monthlyCostTrend
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("monthlyCostTrend")
  public List<@Valid DashboardMonthlyCostDto> getMonthlyCostTrend() {
    return monthlyCostTrend;
  }

  public void setMonthlyCostTrend(List<@Valid DashboardMonthlyCostDto> monthlyCostTrend) {
    this.monthlyCostTrend = monthlyCostTrend;
  }

  public DashboardSummaryResponseDto expiringSoon(DashboardExpiringSoonDto expiringSoon) {
    this.expiringSoon = expiringSoon;
    return this;
  }

  /**
   * Get expiringSoon
   * @return expiringSoon
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("expiringSoon")
  public DashboardExpiringSoonDto getExpiringSoon() {
    return expiringSoon;
  }

  public void setExpiringSoon(DashboardExpiringSoonDto expiringSoon) {
    this.expiringSoon = expiringSoon;
  }

  public DashboardSummaryResponseDto ticketStatus(DashboardTicketStatusDto ticketStatus) {
    this.ticketStatus = ticketStatus;
    return this;
  }

  /**
   * Get ticketStatus
   * @return ticketStatus
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("ticketStatus")
  public DashboardTicketStatusDto getTicketStatus() {
    return ticketStatus;
  }

  public void setTicketStatus(DashboardTicketStatusDto ticketStatus) {
    this.ticketStatus = ticketStatus;
  }

  public DashboardSummaryResponseDto loanStatus(DashboardLoanStatusDto loanStatus) {
    this.loanStatus = loanStatus;
    return this;
  }

  /**
   * Get loanStatus
   * @return loanStatus
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("loanStatus")
  public DashboardLoanStatusDto getLoanStatus() {
    return loanStatus;
  }

  public void setLoanStatus(DashboardLoanStatusDto loanStatus) {
    this.loanStatus = loanStatus;
  }

  public DashboardSummaryResponseDto inventoryProgress(List<@Valid DashboardInventoryProgressDto> inventoryProgress) {
    this.inventoryProgress = inventoryProgress;
    return this;
  }

  public DashboardSummaryResponseDto addInventoryProgressItem(DashboardInventoryProgressDto inventoryProgressItem) {
    if (this.inventoryProgress == null) {
      this.inventoryProgress = new ArrayList<>();
    }
    this.inventoryProgress.add(inventoryProgressItem);
    return this;
  }

  /**
   * Get inventoryProgress
   * @return inventoryProgress
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("inventoryProgress")
  public List<@Valid DashboardInventoryProgressDto> getInventoryProgress() {
    return inventoryProgress;
  }

  public void setInventoryProgress(List<@Valid DashboardInventoryProgressDto> inventoryProgress) {
    this.inventoryProgress = inventoryProgress;
  }

  public DashboardSummaryResponseDto licenseConsistency(DashboardLicenseConsistencyDto licenseConsistency) {
    this.licenseConsistency = licenseConsistency;
    return this;
  }

  /**
   * Get licenseConsistency
   * @return licenseConsistency
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseConsistency")
  public DashboardLicenseConsistencyDto getLicenseConsistency() {
    return licenseConsistency;
  }

  public void setLicenseConsistency(DashboardLicenseConsistencyDto licenseConsistency) {
    this.licenseConsistency = licenseConsistency;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardSummaryResponseDto dashboardSummaryResponseDto = (DashboardSummaryResponseDto) o;
    return Objects.equals(this.aggregatedAt, dashboardSummaryResponseDto.aggregatedAt) &&
        Objects.equals(this.assetSummary, dashboardSummaryResponseDto.assetSummary) &&
        Objects.equals(this.categoryDistribution, dashboardSummaryResponseDto.categoryDistribution) &&
        Objects.equals(this.locationDistribution, dashboardSummaryResponseDto.locationDistribution) &&
        Objects.equals(this.statusDistribution, dashboardSummaryResponseDto.statusDistribution) &&
        Objects.equals(this.monthlyCostTrend, dashboardSummaryResponseDto.monthlyCostTrend) &&
        Objects.equals(this.expiringSoon, dashboardSummaryResponseDto.expiringSoon) &&
        Objects.equals(this.ticketStatus, dashboardSummaryResponseDto.ticketStatus) &&
        Objects.equals(this.loanStatus, dashboardSummaryResponseDto.loanStatus) &&
        Objects.equals(this.inventoryProgress, dashboardSummaryResponseDto.inventoryProgress) &&
        Objects.equals(this.licenseConsistency, dashboardSummaryResponseDto.licenseConsistency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregatedAt, assetSummary, categoryDistribution, locationDistribution, statusDistribution, monthlyCostTrend, expiringSoon, ticketStatus, loanStatus, inventoryProgress, licenseConsistency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardSummaryResponseDto {\n");
    sb.append("    aggregatedAt: ").append(toIndentedString(aggregatedAt)).append("\n");
    sb.append("    assetSummary: ").append(toIndentedString(assetSummary)).append("\n");
    sb.append("    categoryDistribution: ").append(toIndentedString(categoryDistribution)).append("\n");
    sb.append("    locationDistribution: ").append(toIndentedString(locationDistribution)).append("\n");
    sb.append("    statusDistribution: ").append(toIndentedString(statusDistribution)).append("\n");
    sb.append("    monthlyCostTrend: ").append(toIndentedString(monthlyCostTrend)).append("\n");
    sb.append("    expiringSoon: ").append(toIndentedString(expiringSoon)).append("\n");
    sb.append("    ticketStatus: ").append(toIndentedString(ticketStatus)).append("\n");
    sb.append("    loanStatus: ").append(toIndentedString(loanStatus)).append("\n");
    sb.append("    inventoryProgress: ").append(toIndentedString(inventoryProgress)).append("\n");
    sb.append("    licenseConsistency: ").append(toIndentedString(licenseConsistency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
