/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DashboardLicenseConsistencyDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DashboardLicenseConsistencyDto {

  private Long overCapacityLicenseCount;

  private Long unlinkedAssignmentCount;

  public DashboardLicenseConsistencyDto overCapacityLicenseCount(Long overCapacityLicenseCount) {
    this.overCapacityLicenseCount = overCapacityLicenseCount;
    return this;
  }

  /**
   * Get overCapacityLicenseCount
   * @return overCapacityLicenseCount
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("overCapacityLicenseCount")
  public Long getOverCapacityLicenseCount() {
    return overCapacityLicenseCount;
  }

  public void setOverCapacityLicenseCount(Long overCapacityLicenseCount) {
    this.overCapacityLicenseCount = overCapacityLicenseCount;
  }

  public DashboardLicenseConsistencyDto unlinkedAssignmentCount(Long unlinkedAssignmentCount) {
    this.unlinkedAssignmentCount = unlinkedAssignmentCount;
    return this;
  }

  /**
   * Get unlinkedAssignmentCount
   * @return unlinkedAssignmentCount
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("unlinkedAssignmentCount")
  public Long getUnlinkedAssignmentCount() {
    return unlinkedAssignmentCount;
  }

  public void setUnlinkedAssignmentCount(Long unlinkedAssignmentCount) {
    this.unlinkedAssignmentCount = unlinkedAssignmentCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardLicenseConsistencyDto dashboardLicenseConsistencyDto = (DashboardLicenseConsistencyDto) o;
    return Objects.equals(this.overCapacityLicenseCount, dashboardLicenseConsistencyDto.overCapacityLicenseCount) &&
        Objects.equals(this.unlinkedAssignmentCount, dashboardLicenseConsistencyDto.unlinkedAssignmentCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overCapacityLicenseCount, unlinkedAssignmentCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardLicenseConsistencyDto {\n");
    sb.append("    overCapacityLicenseCount: ").append(toIndentedString(overCapacityLicenseCount)).append("\n");
    sb.append("    unlinkedAssignmentCount: ").append(toIndentedString(unlinkedAssignmentCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
