/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DashboardExpiringSoonItemDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DashboardExpiringSoonItemDto {

  private UUID intangibleAssetId;

  private String name;

  private OffsetDateTime expiryDate;

  private Long daysLeft;

  public DashboardExpiringSoonItemDto intangibleAssetId(UUID intangibleAssetId) {
    this.intangibleAssetId = intangibleAssetId;
    return this;
  }

  /**
   * Get intangibleAssetId
   * @return intangibleAssetId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("intangibleAssetId")
  public UUID getIntangibleAssetId() {
    return intangibleAssetId;
  }

  public void setIntangibleAssetId(UUID intangibleAssetId) {
    this.intangibleAssetId = intangibleAssetId;
  }

  public DashboardExpiringSoonItemDto name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DashboardExpiringSoonItemDto expiryDate(OffsetDateTime expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * Get expiryDate
   * @return expiryDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("expiryDate")
  public OffsetDateTime getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(OffsetDateTime expiryDate) {
    this.expiryDate = expiryDate;
  }

  public DashboardExpiringSoonItemDto daysLeft(Long daysLeft) {
    this.daysLeft = daysLeft;
    return this;
  }

  /**
   * 음수면 이미 만료됨
   * @return daysLeft
  */
  
  @ApiModelProperty(value = "음수면 이미 만료됨")
  @JsonProperty("daysLeft")
  public Long getDaysLeft() {
    return daysLeft;
  }

  public void setDaysLeft(Long daysLeft) {
    this.daysLeft = daysLeft;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardExpiringSoonItemDto dashboardExpiringSoonItemDto = (DashboardExpiringSoonItemDto) o;
    return Objects.equals(this.intangibleAssetId, dashboardExpiringSoonItemDto.intangibleAssetId) &&
        Objects.equals(this.name, dashboardExpiringSoonItemDto.name) &&
        Objects.equals(this.expiryDate, dashboardExpiringSoonItemDto.expiryDate) &&
        Objects.equals(this.daysLeft, dashboardExpiringSoonItemDto.daysLeft);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intangibleAssetId, name, expiryDate, daysLeft);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardExpiringSoonItemDto {\n");
    sb.append("    intangibleAssetId: ").append(toIndentedString(intangibleAssetId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    daysLeft: ").append(toIndentedString(daysLeft)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
