/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DepreciationRowResponseDto;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.DepreciationSummaryResponseDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DepreciationStatusResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DepreciationStatusResponseDto {

  @Valid
  private List<@Valid DepreciationRowResponseDto> rows;

  private DepreciationSummaryResponseDto summary;

  public DepreciationStatusResponseDto rows(List<@Valid DepreciationRowResponseDto> rows) {
    this.rows = rows;
    return this;
  }

  public DepreciationStatusResponseDto addRowsItem(DepreciationRowResponseDto rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<>();
    }
    this.rows.add(rowsItem);
    return this;
  }

  /**
   * Get rows
   * @return rows
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("rows")
  public List<@Valid DepreciationRowResponseDto> getRows() {
    return rows;
  }

  public void setRows(List<@Valid DepreciationRowResponseDto> rows) {
    this.rows = rows;
  }

  public DepreciationStatusResponseDto summary(DepreciationSummaryResponseDto summary) {
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("summary")
  public DepreciationSummaryResponseDto getSummary() {
    return summary;
  }

  public void setSummary(DepreciationSummaryResponseDto summary) {
    this.summary = summary;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationStatusResponseDto depreciationStatusResponseDto = (DepreciationStatusResponseDto) o;
    return Objects.equals(this.rows, depreciationStatusResponseDto.rows) &&
        Objects.equals(this.summary, depreciationStatusResponseDto.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rows, summary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationStatusResponseDto {\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
