/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DepreciationConfirmationResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DepreciationConfirmationResponseDto {

  private UUID id;

  private Integer fiscalYear;

  /**
   * Gets or Sets quarter
   */
  public enum QuarterEnum {
    Q1("Q1"),
    
    Q2("Q2"),
    
    Q3("Q3"),
    
    Q4("Q4");

    private String value;

    QuarterEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static QuarterEnum fromValue(String value) {
      for (QuarterEnum b : QuarterEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private QuarterEnum quarter;

  private OffsetDateTime confirmedAt;

  private UUID confirmedBy;

  private OffsetDateTime releasedAt;

  private UUID releasedBy;

  private String releaseReason;

  public DepreciationConfirmationResponseDto id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("id")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public DepreciationConfirmationResponseDto fiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
    return this;
  }

  /**
   * Get fiscalYear
   * @return fiscalYear
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("fiscalYear")
  public Integer getFiscalYear() {
    return fiscalYear;
  }

  public void setFiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
  }

  public DepreciationConfirmationResponseDto quarter(QuarterEnum quarter) {
    this.quarter = quarter;
    return this;
  }

  /**
   * Get quarter
   * @return quarter
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("quarter")
  public QuarterEnum getQuarter() {
    return quarter;
  }

  public void setQuarter(QuarterEnum quarter) {
    this.quarter = quarter;
  }

  public DepreciationConfirmationResponseDto confirmedAt(OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
    return this;
  }

  /**
   * Get confirmedAt
   * @return confirmedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("confirmedAt")
  public OffsetDateTime getConfirmedAt() {
    return confirmedAt;
  }

  public void setConfirmedAt(OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
  }

  public DepreciationConfirmationResponseDto confirmedBy(UUID confirmedBy) {
    this.confirmedBy = confirmedBy;
    return this;
  }

  /**
   * Get confirmedBy
   * @return confirmedBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("confirmedBy")
  public UUID getConfirmedBy() {
    return confirmedBy;
  }

  public void setConfirmedBy(UUID confirmedBy) {
    this.confirmedBy = confirmedBy;
  }

  public DepreciationConfirmationResponseDto releasedAt(OffsetDateTime releasedAt) {
    this.releasedAt = releasedAt;
    return this;
  }

  /**
   * Get releasedAt
   * @return releasedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("releasedAt")
  public OffsetDateTime getReleasedAt() {
    return releasedAt;
  }

  public void setReleasedAt(OffsetDateTime releasedAt) {
    this.releasedAt = releasedAt;
  }

  public DepreciationConfirmationResponseDto releasedBy(UUID releasedBy) {
    this.releasedBy = releasedBy;
    return this;
  }

  /**
   * Get releasedBy
   * @return releasedBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("releasedBy")
  public UUID getReleasedBy() {
    return releasedBy;
  }

  public void setReleasedBy(UUID releasedBy) {
    this.releasedBy = releasedBy;
  }

  public DepreciationConfirmationResponseDto releaseReason(String releaseReason) {
    this.releaseReason = releaseReason;
    return this;
  }

  /**
   * 처리 일시
   * @return releaseReason
  */
  
  @ApiModelProperty(value = "처리 일시")
  @JsonProperty("releaseReason")
  public String getReleaseReason() {
    return releaseReason;
  }

  public void setReleaseReason(String releaseReason) {
    this.releaseReason = releaseReason;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationConfirmationResponseDto depreciationConfirmationResponseDto = (DepreciationConfirmationResponseDto) o;
    return Objects.equals(this.id, depreciationConfirmationResponseDto.id) &&
        Objects.equals(this.fiscalYear, depreciationConfirmationResponseDto.fiscalYear) &&
        Objects.equals(this.quarter, depreciationConfirmationResponseDto.quarter) &&
        Objects.equals(this.confirmedAt, depreciationConfirmationResponseDto.confirmedAt) &&
        Objects.equals(this.confirmedBy, depreciationConfirmationResponseDto.confirmedBy) &&
        Objects.equals(this.releasedAt, depreciationConfirmationResponseDto.releasedAt) &&
        Objects.equals(this.releasedBy, depreciationConfirmationResponseDto.releasedBy) &&
        Objects.equals(this.releaseReason, depreciationConfirmationResponseDto.releaseReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fiscalYear, quarter, confirmedAt, confirmedBy, releasedAt, releasedBy, releaseReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationConfirmationResponseDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fiscalYear: ").append(toIndentedString(fiscalYear)).append("\n");
    sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
    sb.append("    confirmedAt: ").append(toIndentedString(confirmedAt)).append("\n");
    sb.append("    confirmedBy: ").append(toIndentedString(confirmedBy)).append("\n");
    sb.append("    releasedAt: ").append(toIndentedString(releasedAt)).append("\n");
    sb.append("    releasedBy: ").append(toIndentedString(releasedBy)).append("\n");
    sb.append("    releaseReason: ").append(toIndentedString(releaseReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
