/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DepreciationSummaryResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DepreciationSummaryResponseDto {

  private BigDecimal totalAcquisitionAmount;

  private BigDecimal totalOpeningAccumulated;

  private BigDecimal totalPeriodDepreciation;

  private BigDecimal totalClosingAccumulated;

  private BigDecimal totalBookValue;

  private Integer excludedCount;

  private Boolean confirmed;

  private OffsetDateTime confirmedAt;

  private OffsetDateTime calculatedAt;

  public DepreciationSummaryResponseDto totalAcquisitionAmount(BigDecimal totalAcquisitionAmount) {
    this.totalAcquisitionAmount = totalAcquisitionAmount;
    return this;
  }

  /**
   * Get totalAcquisitionAmount
   * @return totalAcquisitionAmount
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalAcquisitionAmount")
  public BigDecimal getTotalAcquisitionAmount() {
    return totalAcquisitionAmount;
  }

  public void setTotalAcquisitionAmount(BigDecimal totalAcquisitionAmount) {
    this.totalAcquisitionAmount = totalAcquisitionAmount;
  }

  public DepreciationSummaryResponseDto totalOpeningAccumulated(BigDecimal totalOpeningAccumulated) {
    this.totalOpeningAccumulated = totalOpeningAccumulated;
    return this;
  }

  /**
   * Get totalOpeningAccumulated
   * @return totalOpeningAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalOpeningAccumulated")
  public BigDecimal getTotalOpeningAccumulated() {
    return totalOpeningAccumulated;
  }

  public void setTotalOpeningAccumulated(BigDecimal totalOpeningAccumulated) {
    this.totalOpeningAccumulated = totalOpeningAccumulated;
  }

  public DepreciationSummaryResponseDto totalPeriodDepreciation(BigDecimal totalPeriodDepreciation) {
    this.totalPeriodDepreciation = totalPeriodDepreciation;
    return this;
  }

  /**
   * Get totalPeriodDepreciation
   * @return totalPeriodDepreciation
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalPeriodDepreciation")
  public BigDecimal getTotalPeriodDepreciation() {
    return totalPeriodDepreciation;
  }

  public void setTotalPeriodDepreciation(BigDecimal totalPeriodDepreciation) {
    this.totalPeriodDepreciation = totalPeriodDepreciation;
  }

  public DepreciationSummaryResponseDto totalClosingAccumulated(BigDecimal totalClosingAccumulated) {
    this.totalClosingAccumulated = totalClosingAccumulated;
    return this;
  }

  /**
   * Get totalClosingAccumulated
   * @return totalClosingAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalClosingAccumulated")
  public BigDecimal getTotalClosingAccumulated() {
    return totalClosingAccumulated;
  }

  public void setTotalClosingAccumulated(BigDecimal totalClosingAccumulated) {
    this.totalClosingAccumulated = totalClosingAccumulated;
  }

  public DepreciationSummaryResponseDto totalBookValue(BigDecimal totalBookValue) {
    this.totalBookValue = totalBookValue;
    return this;
  }

  /**
   * Get totalBookValue
   * @return totalBookValue
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalBookValue")
  public BigDecimal getTotalBookValue() {
    return totalBookValue;
  }

  public void setTotalBookValue(BigDecimal totalBookValue) {
    this.totalBookValue = totalBookValue;
  }

  public DepreciationSummaryResponseDto excludedCount(Integer excludedCount) {
    this.excludedCount = excludedCount;
    return this;
  }

  /**
   * Get excludedCount
   * @return excludedCount
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("excludedCount")
  public Integer getExcludedCount() {
    return excludedCount;
  }

  public void setExcludedCount(Integer excludedCount) {
    this.excludedCount = excludedCount;
  }

  public DepreciationSummaryResponseDto confirmed(Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

  /**
   * 이 기간이 확정 상태인지 - 확정이면 스냅샷값, 아니면 실시간 산출값
   * @return confirmed
  */
  
  @ApiModelProperty(value = "이 기간이 확정 상태인지 - 확정이면 스냅샷값, 아니면 실시간 산출값")
  @JsonProperty("confirmed")
  public Boolean getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }

  public DepreciationSummaryResponseDto confirmedAt(OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
    return this;
  }

  /**
   * Get confirmedAt
   * @return confirmedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("confirmedAt")
  public OffsetDateTime getConfirmedAt() {
    return confirmedAt;
  }

  public void setConfirmedAt(OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
  }

  public DepreciationSummaryResponseDto calculatedAt(OffsetDateTime calculatedAt) {
    this.calculatedAt = calculatedAt;
    return this;
  }

  /**
   * 미확정 기간의 산출 기준 시각 - 확정 기간은 null
   * @return calculatedAt
  */
  @Valid 
  @ApiModelProperty(value = "미확정 기간의 산출 기준 시각 - 확정 기간은 null")
  @JsonProperty("calculatedAt")
  public OffsetDateTime getCalculatedAt() {
    return calculatedAt;
  }

  public void setCalculatedAt(OffsetDateTime calculatedAt) {
    this.calculatedAt = calculatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationSummaryResponseDto depreciationSummaryResponseDto = (DepreciationSummaryResponseDto) o;
    return Objects.equals(this.totalAcquisitionAmount, depreciationSummaryResponseDto.totalAcquisitionAmount) &&
        Objects.equals(this.totalOpeningAccumulated, depreciationSummaryResponseDto.totalOpeningAccumulated) &&
        Objects.equals(this.totalPeriodDepreciation, depreciationSummaryResponseDto.totalPeriodDepreciation) &&
        Objects.equals(this.totalClosingAccumulated, depreciationSummaryResponseDto.totalClosingAccumulated) &&
        Objects.equals(this.totalBookValue, depreciationSummaryResponseDto.totalBookValue) &&
        Objects.equals(this.excludedCount, depreciationSummaryResponseDto.excludedCount) &&
        Objects.equals(this.confirmed, depreciationSummaryResponseDto.confirmed) &&
        Objects.equals(this.confirmedAt, depreciationSummaryResponseDto.confirmedAt) &&
        Objects.equals(this.calculatedAt, depreciationSummaryResponseDto.calculatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalAcquisitionAmount, totalOpeningAccumulated, totalPeriodDepreciation, totalClosingAccumulated, totalBookValue, excludedCount, confirmed, confirmedAt, calculatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationSummaryResponseDto {\n");
    sb.append("    totalAcquisitionAmount: ").append(toIndentedString(totalAcquisitionAmount)).append("\n");
    sb.append("    totalOpeningAccumulated: ").append(toIndentedString(totalOpeningAccumulated)).append("\n");
    sb.append("    totalPeriodDepreciation: ").append(toIndentedString(totalPeriodDepreciation)).append("\n");
    sb.append("    totalClosingAccumulated: ").append(toIndentedString(totalClosingAccumulated)).append("\n");
    sb.append("    totalBookValue: ").append(toIndentedString(totalBookValue)).append("\n");
    sb.append("    excludedCount: ").append(toIndentedString(excludedCount)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    confirmedAt: ").append(toIndentedString(confirmedAt)).append("\n");
    sb.append("    calculatedAt: ").append(toIndentedString(calculatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
