/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DepreciationScheduleRowResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DepreciationScheduleRowResponseDto {

  private Integer fiscalYear;

  /**
   * Gets or Sets quarter
   */
  public enum QuarterEnum {
    Q1("Q1"),
    
    Q2("Q2"),
    
    Q3("Q3"),
    
    Q4("Q4");

    private String value;

    QuarterEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static QuarterEnum fromValue(String value) {
      for (QuarterEnum b : QuarterEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private QuarterEnum quarter;

  private BigDecimal openingAccumulated;

  private BigDecimal periodDepreciation;

  private BigDecimal closingAccumulated;

  private BigDecimal bookValue;

  private Boolean confirmed;

  private Boolean excluded;

  public DepreciationScheduleRowResponseDto fiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
    return this;
  }

  /**
   * Get fiscalYear
   * @return fiscalYear
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("fiscalYear")
  public Integer getFiscalYear() {
    return fiscalYear;
  }

  public void setFiscalYear(Integer fiscalYear) {
    this.fiscalYear = fiscalYear;
  }

  public DepreciationScheduleRowResponseDto quarter(QuarterEnum quarter) {
    this.quarter = quarter;
    return this;
  }

  /**
   * Get quarter
   * @return quarter
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("quarter")
  public QuarterEnum getQuarter() {
    return quarter;
  }

  public void setQuarter(QuarterEnum quarter) {
    this.quarter = quarter;
  }

  public DepreciationScheduleRowResponseDto openingAccumulated(BigDecimal openingAccumulated) {
    this.openingAccumulated = openingAccumulated;
    return this;
  }

  /**
   * Get openingAccumulated
   * @return openingAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("openingAccumulated")
  public BigDecimal getOpeningAccumulated() {
    return openingAccumulated;
  }

  public void setOpeningAccumulated(BigDecimal openingAccumulated) {
    this.openingAccumulated = openingAccumulated;
  }

  public DepreciationScheduleRowResponseDto periodDepreciation(BigDecimal periodDepreciation) {
    this.periodDepreciation = periodDepreciation;
    return this;
  }

  /**
   * Get periodDepreciation
   * @return periodDepreciation
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("periodDepreciation")
  public BigDecimal getPeriodDepreciation() {
    return periodDepreciation;
  }

  public void setPeriodDepreciation(BigDecimal periodDepreciation) {
    this.periodDepreciation = periodDepreciation;
  }

  public DepreciationScheduleRowResponseDto closingAccumulated(BigDecimal closingAccumulated) {
    this.closingAccumulated = closingAccumulated;
    return this;
  }

  /**
   * Get closingAccumulated
   * @return closingAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("closingAccumulated")
  public BigDecimal getClosingAccumulated() {
    return closingAccumulated;
  }

  public void setClosingAccumulated(BigDecimal closingAccumulated) {
    this.closingAccumulated = closingAccumulated;
  }

  public DepreciationScheduleRowResponseDto bookValue(BigDecimal bookValue) {
    this.bookValue = bookValue;
    return this;
  }

  /**
   * Get bookValue
   * @return bookValue
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("bookValue")
  public BigDecimal getBookValue() {
    return bookValue;
  }

  public void setBookValue(BigDecimal bookValue) {
    this.bookValue = bookValue;
  }

  public DepreciationScheduleRowResponseDto confirmed(Boolean confirmed) {
    this.confirmed = confirmed;
    return this;
  }

  /**
   * Get confirmed
   * @return confirmed
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("confirmed")
  public Boolean getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(Boolean confirmed) {
    this.confirmed = confirmed;
  }

  public DepreciationScheduleRowResponseDto excluded(Boolean excluded) {
    this.excluded = excluded;
    return this;
  }

  /**
   * Get excluded
   * @return excluded
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("excluded")
  public Boolean getExcluded() {
    return excluded;
  }

  public void setExcluded(Boolean excluded) {
    this.excluded = excluded;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationScheduleRowResponseDto depreciationScheduleRowResponseDto = (DepreciationScheduleRowResponseDto) o;
    return Objects.equals(this.fiscalYear, depreciationScheduleRowResponseDto.fiscalYear) &&
        Objects.equals(this.quarter, depreciationScheduleRowResponseDto.quarter) &&
        Objects.equals(this.openingAccumulated, depreciationScheduleRowResponseDto.openingAccumulated) &&
        Objects.equals(this.periodDepreciation, depreciationScheduleRowResponseDto.periodDepreciation) &&
        Objects.equals(this.closingAccumulated, depreciationScheduleRowResponseDto.closingAccumulated) &&
        Objects.equals(this.bookValue, depreciationScheduleRowResponseDto.bookValue) &&
        Objects.equals(this.confirmed, depreciationScheduleRowResponseDto.confirmed) &&
        Objects.equals(this.excluded, depreciationScheduleRowResponseDto.excluded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fiscalYear, quarter, openingAccumulated, periodDepreciation, closingAccumulated, bookValue, confirmed, excluded);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationScheduleRowResponseDto {\n");
    sb.append("    fiscalYear: ").append(toIndentedString(fiscalYear)).append("\n");
    sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
    sb.append("    openingAccumulated: ").append(toIndentedString(openingAccumulated)).append("\n");
    sb.append("    periodDepreciation: ").append(toIndentedString(periodDepreciation)).append("\n");
    sb.append("    closingAccumulated: ").append(toIndentedString(closingAccumulated)).append("\n");
    sb.append("    bookValue: ").append(toIndentedString(bookValue)).append("\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    excluded: ").append(toIndentedString(excluded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
