/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * DepreciationRowResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DepreciationRowResponseDto {

  private UUID tangibleAssetId;

  private String assetCode;

  private String assetName;

  private String categoryName;

  private OffsetDateTime acquisitionDate;

  private BigDecimal acquisitionAmount;

  private BigDecimal openingAccumulated;

  private BigDecimal periodDepreciation;

  private BigDecimal closingAccumulated;

  private BigDecimal bookValue;

  private Integer elapsedMonths;

  private Integer usefulLifeMonths;

  /**
   * 상각 제외 사유 - 해당 없으면 null
   */
  public enum ExcludedReasonEnum {
    NO_AMOUNT("NO_AMOUNT"),
    
    NO_BASIS("NO_BASIS"),
    
    NOT_DEPRECIABLE_STATUS("NOT_DEPRECIABLE_STATUS");

    private String value;

    ExcludedReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExcludedReasonEnum fromValue(String value) {
      for (ExcludedReasonEnum b : ExcludedReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ExcludedReasonEnum excludedReason;

  public DepreciationRowResponseDto tangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
    return this;
  }

  /**
   * Get tangibleAssetId
   * @return tangibleAssetId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("tangibleAssetId")
  public UUID getTangibleAssetId() {
    return tangibleAssetId;
  }

  public void setTangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
  }

  public DepreciationRowResponseDto assetCode(String assetCode) {
    this.assetCode = assetCode;
    return this;
  }

  /**
   * Get assetCode
   * @return assetCode
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("assetCode")
  public String getAssetCode() {
    return assetCode;
  }

  public void setAssetCode(String assetCode) {
    this.assetCode = assetCode;
  }

  public DepreciationRowResponseDto assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

  /**
   * Get assetName
   * @return assetName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("assetName")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public DepreciationRowResponseDto categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

  /**
   * Get categoryName
   * @return categoryName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("categoryName")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public DepreciationRowResponseDto acquisitionDate(OffsetDateTime acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
    return this;
  }

  /**
   * Get acquisitionDate
   * @return acquisitionDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("acquisitionDate")
  public OffsetDateTime getAcquisitionDate() {
    return acquisitionDate;
  }

  public void setAcquisitionDate(OffsetDateTime acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
  }

  public DepreciationRowResponseDto acquisitionAmount(BigDecimal acquisitionAmount) {
    this.acquisitionAmount = acquisitionAmount;
    return this;
  }

  /**
   * Get acquisitionAmount
   * @return acquisitionAmount
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("acquisitionAmount")
  public BigDecimal getAcquisitionAmount() {
    return acquisitionAmount;
  }

  public void setAcquisitionAmount(BigDecimal acquisitionAmount) {
    this.acquisitionAmount = acquisitionAmount;
  }

  public DepreciationRowResponseDto openingAccumulated(BigDecimal openingAccumulated) {
    this.openingAccumulated = openingAccumulated;
    return this;
  }

  /**
   * 기초 감가상각누계액 - 상각 제외 자산은 null
   * @return openingAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "기초 감가상각누계액 - 상각 제외 자산은 null")
  @JsonProperty("openingAccumulated")
  public BigDecimal getOpeningAccumulated() {
    return openingAccumulated;
  }

  public void setOpeningAccumulated(BigDecimal openingAccumulated) {
    this.openingAccumulated = openingAccumulated;
  }

  public DepreciationRowResponseDto periodDepreciation(BigDecimal periodDepreciation) {
    this.periodDepreciation = periodDepreciation;
    return this;
  }

  /**
   * 당기 상각액 - 상각 제외 자산은 null
   * @return periodDepreciation
  */
  @Valid 
  @ApiModelProperty(value = "당기 상각액 - 상각 제외 자산은 null")
  @JsonProperty("periodDepreciation")
  public BigDecimal getPeriodDepreciation() {
    return periodDepreciation;
  }

  public void setPeriodDepreciation(BigDecimal periodDepreciation) {
    this.periodDepreciation = periodDepreciation;
  }

  public DepreciationRowResponseDto closingAccumulated(BigDecimal closingAccumulated) {
    this.closingAccumulated = closingAccumulated;
    return this;
  }

  /**
   * 기말 감가상각누계액 - 상각 제외 자산은 null
   * @return closingAccumulated
  */
  @Valid 
  @ApiModelProperty(value = "기말 감가상각누계액 - 상각 제외 자산은 null")
  @JsonProperty("closingAccumulated")
  public BigDecimal getClosingAccumulated() {
    return closingAccumulated;
  }

  public void setClosingAccumulated(BigDecimal closingAccumulated) {
    this.closingAccumulated = closingAccumulated;
  }

  public DepreciationRowResponseDto bookValue(BigDecimal bookValue) {
    this.bookValue = bookValue;
    return this;
  }

  /**
   * 장부가 (상각 제외 자산은 취득가액과 동일)
   * @return bookValue
  */
  @Valid 
  @ApiModelProperty(value = "장부가 (상각 제외 자산은 취득가액과 동일)")
  @JsonProperty("bookValue")
  public BigDecimal getBookValue() {
    return bookValue;
  }

  public void setBookValue(BigDecimal bookValue) {
    this.bookValue = bookValue;
  }

  public DepreciationRowResponseDto elapsedMonths(Integer elapsedMonths) {
    this.elapsedMonths = elapsedMonths;
    return this;
  }

  /**
   * 경과 개월 - 상각 제외 자산은 null
   * @return elapsedMonths
  */
  
  @ApiModelProperty(value = "경과 개월 - 상각 제외 자산은 null")
  @JsonProperty("elapsedMonths")
  public Integer getElapsedMonths() {
    return elapsedMonths;
  }

  public void setElapsedMonths(Integer elapsedMonths) {
    this.elapsedMonths = elapsedMonths;
  }

  public DepreciationRowResponseDto usefulLifeMonths(Integer usefulLifeMonths) {
    this.usefulLifeMonths = usefulLifeMonths;
    return this;
  }

  /**
   * Get usefulLifeMonths
   * @return usefulLifeMonths
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("usefulLifeMonths")
  public Integer getUsefulLifeMonths() {
    return usefulLifeMonths;
  }

  public void setUsefulLifeMonths(Integer usefulLifeMonths) {
    this.usefulLifeMonths = usefulLifeMonths;
  }

  public DepreciationRowResponseDto excludedReason(ExcludedReasonEnum excludedReason) {
    this.excludedReason = excludedReason;
    return this;
  }

  /**
   * 상각 제외 사유 - 해당 없으면 null
   * @return excludedReason
  */
  
  @ApiModelProperty(value = "상각 제외 사유 - 해당 없으면 null")
  @JsonProperty("excludedReason")
  public ExcludedReasonEnum getExcludedReason() {
    return excludedReason;
  }

  public void setExcludedReason(ExcludedReasonEnum excludedReason) {
    this.excludedReason = excludedReason;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationRowResponseDto depreciationRowResponseDto = (DepreciationRowResponseDto) o;
    return Objects.equals(this.tangibleAssetId, depreciationRowResponseDto.tangibleAssetId) &&
        Objects.equals(this.assetCode, depreciationRowResponseDto.assetCode) &&
        Objects.equals(this.assetName, depreciationRowResponseDto.assetName) &&
        Objects.equals(this.categoryName, depreciationRowResponseDto.categoryName) &&
        Objects.equals(this.acquisitionDate, depreciationRowResponseDto.acquisitionDate) &&
        Objects.equals(this.acquisitionAmount, depreciationRowResponseDto.acquisitionAmount) &&
        Objects.equals(this.openingAccumulated, depreciationRowResponseDto.openingAccumulated) &&
        Objects.equals(this.periodDepreciation, depreciationRowResponseDto.periodDepreciation) &&
        Objects.equals(this.closingAccumulated, depreciationRowResponseDto.closingAccumulated) &&
        Objects.equals(this.bookValue, depreciationRowResponseDto.bookValue) &&
        Objects.equals(this.elapsedMonths, depreciationRowResponseDto.elapsedMonths) &&
        Objects.equals(this.usefulLifeMonths, depreciationRowResponseDto.usefulLifeMonths) &&
        Objects.equals(this.excludedReason, depreciationRowResponseDto.excludedReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tangibleAssetId, assetCode, assetName, categoryName, acquisitionDate, acquisitionAmount, openingAccumulated, periodDepreciation, closingAccumulated, bookValue, elapsedMonths, usefulLifeMonths, excludedReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationRowResponseDto {\n");
    sb.append("    tangibleAssetId: ").append(toIndentedString(tangibleAssetId)).append("\n");
    sb.append("    assetCode: ").append(toIndentedString(assetCode)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    acquisitionDate: ").append(toIndentedString(acquisitionDate)).append("\n");
    sb.append("    acquisitionAmount: ").append(toIndentedString(acquisitionAmount)).append("\n");
    sb.append("    openingAccumulated: ").append(toIndentedString(openingAccumulated)).append("\n");
    sb.append("    periodDepreciation: ").append(toIndentedString(periodDepreciation)).append("\n");
    sb.append("    closingAccumulated: ").append(toIndentedString(closingAccumulated)).append("\n");
    sb.append("    bookValue: ").append(toIndentedString(bookValue)).append("\n");
    sb.append("    elapsedMonths: ").append(toIndentedString(elapsedMonths)).append("\n");
    sb.append("    usefulLifeMonths: ").append(toIndentedString(usefulLifeMonths)).append("\n");
    sb.append("    excludedReason: ").append(toIndentedString(excludedReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
