/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * IntangibleAssetResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class IntangibleAssetResponseDto {

  private UUID intangibleAssetId;

  /**
   * Gets or Sets intangibleType
   */
  public enum IntangibleTypeEnum {
    DOMAIN("DOMAIN"),
    
    CERTIFICATE("CERTIFICATE"),
    
    TRADEMARK("TRADEMARK"),
    
    OTHER("OTHER");

    private String value;

    IntangibleTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IntangibleTypeEnum fromValue(String value) {
      for (IntangibleTypeEnum b : IntangibleTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private IntangibleTypeEnum intangibleType;

  private String name;

  private String issuer;

  private OffsetDateTime registeredDate;

  private OffsetDateTime expiryDate;

  private UUID ownerMemberId;

  private String alertDays;

  private String memo;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  private Long daysUntilExpiry;

  private Boolean expired;

  private Boolean nearExpiry;

  public IntangibleAssetResponseDto intangibleAssetId(UUID intangibleAssetId) {
    this.intangibleAssetId = intangibleAssetId;
    return this;
  }

  /**
   * Get intangibleAssetId
   * @return intangibleAssetId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("intangibleAssetId")
  public UUID getIntangibleAssetId() {
    return intangibleAssetId;
  }

  public void setIntangibleAssetId(UUID intangibleAssetId) {
    this.intangibleAssetId = intangibleAssetId;
  }

  public IntangibleAssetResponseDto intangibleType(IntangibleTypeEnum intangibleType) {
    this.intangibleType = intangibleType;
    return this;
  }

  /**
   * Get intangibleType
   * @return intangibleType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("intangibleType")
  public IntangibleTypeEnum getIntangibleType() {
    return intangibleType;
  }

  public void setIntangibleType(IntangibleTypeEnum intangibleType) {
    this.intangibleType = intangibleType;
  }

  public IntangibleAssetResponseDto name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IntangibleAssetResponseDto issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Get issuer
   * @return issuer
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("issuer")
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public IntangibleAssetResponseDto registeredDate(OffsetDateTime registeredDate) {
    this.registeredDate = registeredDate;
    return this;
  }

  /**
   * Get registeredDate
   * @return registeredDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("registeredDate")
  public OffsetDateTime getRegisteredDate() {
    return registeredDate;
  }

  public void setRegisteredDate(OffsetDateTime registeredDate) {
    this.registeredDate = registeredDate;
  }

  public IntangibleAssetResponseDto expiryDate(OffsetDateTime expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * Get expiryDate
   * @return expiryDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("expiryDate")
  public OffsetDateTime getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(OffsetDateTime expiryDate) {
    this.expiryDate = expiryDate;
  }

  public IntangibleAssetResponseDto ownerMemberId(UUID ownerMemberId) {
    this.ownerMemberId = ownerMemberId;
    return this;
  }

  /**
   * Get ownerMemberId
   * @return ownerMemberId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("ownerMemberId")
  public UUID getOwnerMemberId() {
    return ownerMemberId;
  }

  public void setOwnerMemberId(UUID ownerMemberId) {
    this.ownerMemberId = ownerMemberId;
  }

  public IntangibleAssetResponseDto alertDays(String alertDays) {
    this.alertDays = alertDays;
    return this;
  }

  /**
   * Get alertDays
   * @return alertDays
  */
  
  @ApiModelProperty(example = "30,7,3,1", value = "")
  @JsonProperty("alertDays")
  public String getAlertDays() {
    return alertDays;
  }

  public void setAlertDays(String alertDays) {
    this.alertDays = alertDays;
  }

  public IntangibleAssetResponseDto memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   * @return memo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("memo")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public IntangibleAssetResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public IntangibleAssetResponseDto daysUntilExpiry(Long daysUntilExpiry) {
    this.daysUntilExpiry = daysUntilExpiry;
    return this;
  }

  /**
   * 파생값 - 오늘부터 만료일까지 남은 일수(음수면 지난 일수)
   * @return daysUntilExpiry
  */
  
  @ApiModelProperty(value = "파생값 - 오늘부터 만료일까지 남은 일수(음수면 지난 일수)")
  @JsonProperty("daysUntilExpiry")
  public Long getDaysUntilExpiry() {
    return daysUntilExpiry;
  }

  public void setDaysUntilExpiry(Long daysUntilExpiry) {
    this.daysUntilExpiry = daysUntilExpiry;
  }

  public IntangibleAssetResponseDto expired(Boolean expired) {
    this.expired = expired;
    return this;
  }

  /**
   * Get expired
   * @return expired
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("expired")
  public Boolean getExpired() {
    return expired;
  }

  public void setExpired(Boolean expired) {
    this.expired = expired;
  }

  public IntangibleAssetResponseDto nearExpiry(Boolean nearExpiry) {
    this.nearExpiry = nearExpiry;
    return this;
  }

  /**
   * Get nearExpiry
   * @return nearExpiry
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("nearExpiry")
  public Boolean getNearExpiry() {
    return nearExpiry;
  }

  public void setNearExpiry(Boolean nearExpiry) {
    this.nearExpiry = nearExpiry;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntangibleAssetResponseDto intangibleAssetResponseDto = (IntangibleAssetResponseDto) o;
    return Objects.equals(this.intangibleAssetId, intangibleAssetResponseDto.intangibleAssetId) &&
        Objects.equals(this.intangibleType, intangibleAssetResponseDto.intangibleType) &&
        Objects.equals(this.name, intangibleAssetResponseDto.name) &&
        Objects.equals(this.issuer, intangibleAssetResponseDto.issuer) &&
        Objects.equals(this.registeredDate, intangibleAssetResponseDto.registeredDate) &&
        Objects.equals(this.expiryDate, intangibleAssetResponseDto.expiryDate) &&
        Objects.equals(this.ownerMemberId, intangibleAssetResponseDto.ownerMemberId) &&
        Objects.equals(this.alertDays, intangibleAssetResponseDto.alertDays) &&
        Objects.equals(this.memo, intangibleAssetResponseDto.memo) &&
        Objects.equals(this.status, intangibleAssetResponseDto.status) &&
        Objects.equals(this.daysUntilExpiry, intangibleAssetResponseDto.daysUntilExpiry) &&
        Objects.equals(this.expired, intangibleAssetResponseDto.expired) &&
        Objects.equals(this.nearExpiry, intangibleAssetResponseDto.nearExpiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intangibleAssetId, intangibleType, name, issuer, registeredDate, expiryDate, ownerMemberId, alertDays, memo, status, daysUntilExpiry, expired, nearExpiry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntangibleAssetResponseDto {\n");
    sb.append("    intangibleAssetId: ").append(toIndentedString(intangibleAssetId)).append("\n");
    sb.append("    intangibleType: ").append(toIndentedString(intangibleType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    registeredDate: ").append(toIndentedString(registeredDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    ownerMemberId: ").append(toIndentedString(ownerMemberId)).append("\n");
    sb.append("    alertDays: ").append(toIndentedString(alertDays)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    daysUntilExpiry: ").append(toIndentedString(daysUntilExpiry)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    nearExpiry: ").append(toIndentedString(nearExpiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
