/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.smartAsset.interfaces.inboundAdapter.spec.InventoryResultRowResponseDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventoryMyStatusResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventoryMyStatusResponseDto {

  private Boolean hasActiveInventory;

  private UUID inventoryId;

  private String title;

  private Boolean approvalRequired;

  @Valid
  private List<@Valid InventoryResultRowResponseDto> results;

  public InventoryMyStatusResponseDto hasActiveInventory(Boolean hasActiveInventory) {
    this.hasActiveInventory = hasActiveInventory;
    return this;
  }

  /**
   * Get hasActiveInventory
   * @return hasActiveInventory
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("hasActiveInventory")
  public Boolean getHasActiveInventory() {
    return hasActiveInventory;
  }

  public void setHasActiveInventory(Boolean hasActiveInventory) {
    this.hasActiveInventory = hasActiveInventory;
  }

  public InventoryMyStatusResponseDto inventoryId(UUID inventoryId) {
    this.inventoryId = inventoryId;
    return this;
  }

  /**
   * Get inventoryId
   * @return inventoryId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("inventoryId")
  public UUID getInventoryId() {
    return inventoryId;
  }

  public void setInventoryId(UUID inventoryId) {
    this.inventoryId = inventoryId;
  }

  public InventoryMyStatusResponseDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InventoryMyStatusResponseDto approvalRequired(Boolean approvalRequired) {
    this.approvalRequired = approvalRequired;
    return this;
  }

  /**
   * Get approvalRequired
   * @return approvalRequired
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("approvalRequired")
  public Boolean getApprovalRequired() {
    return approvalRequired;
  }

  public void setApprovalRequired(Boolean approvalRequired) {
    this.approvalRequired = approvalRequired;
  }

  public InventoryMyStatusResponseDto results(List<@Valid InventoryResultRowResponseDto> results) {
    this.results = results;
    return this;
  }

  public InventoryMyStatusResponseDto addResultsItem(InventoryResultRowResponseDto resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("results")
  public List<@Valid InventoryResultRowResponseDto> getResults() {
    return results;
  }

  public void setResults(List<@Valid InventoryResultRowResponseDto> results) {
    this.results = results;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryMyStatusResponseDto inventoryMyStatusResponseDto = (InventoryMyStatusResponseDto) o;
    return Objects.equals(this.hasActiveInventory, inventoryMyStatusResponseDto.hasActiveInventory) &&
        Objects.equals(this.inventoryId, inventoryMyStatusResponseDto.inventoryId) &&
        Objects.equals(this.title, inventoryMyStatusResponseDto.title) &&
        Objects.equals(this.approvalRequired, inventoryMyStatusResponseDto.approvalRequired) &&
        Objects.equals(this.results, inventoryMyStatusResponseDto.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasActiveInventory, inventoryId, title, approvalRequired, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryMyStatusResponseDto {\n");
    sb.append("    hasActiveInventory: ").append(toIndentedString(hasActiveInventory)).append("\n");
    sb.append("    inventoryId: ").append(toIndentedString(inventoryId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    approvalRequired: ").append(toIndentedString(approvalRequired)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
