/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventoryCloneTemplateResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventoryCloneTemplateResponseDto {

  /**
   * Gets or Sets inventoryType
   */
  public enum InventoryTypeEnum {
    MEMBER("MEMBER"),
    
    ADMIN("ADMIN");

    private String value;

    InventoryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InventoryTypeEnum fromValue(String value) {
      for (InventoryTypeEnum b : InventoryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private InventoryTypeEnum inventoryType;

  private String title;

  private Boolean approvalRequired;

  private Boolean allowNewAssetRegistration;

  /**
   * Gets or Sets recurrenceRule
   */
  public enum RecurrenceRuleEnum {
    QUARTERLY("QUARTERLY"),
    
    SEMIANNUAL("SEMIANNUAL"),
    
    ANNUAL("ANNUAL");

    private String value;

    RecurrenceRuleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RecurrenceRuleEnum fromValue(String value) {
      for (RecurrenceRuleEnum b : RecurrenceRuleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private RecurrenceRuleEnum recurrenceRule;

  @Valid
  private List<UUID> excludedMemberIds;

  @Valid
  private List<UUID> inspectorMemberIds;

  public InventoryCloneTemplateResponseDto inventoryType(InventoryTypeEnum inventoryType) {
    this.inventoryType = inventoryType;
    return this;
  }

  /**
   * Get inventoryType
   * @return inventoryType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("inventoryType")
  public InventoryTypeEnum getInventoryType() {
    return inventoryType;
  }

  public void setInventoryType(InventoryTypeEnum inventoryType) {
    this.inventoryType = inventoryType;
  }

  public InventoryCloneTemplateResponseDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InventoryCloneTemplateResponseDto approvalRequired(Boolean approvalRequired) {
    this.approvalRequired = approvalRequired;
    return this;
  }

  /**
   * Get approvalRequired
   * @return approvalRequired
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("approvalRequired")
  public Boolean getApprovalRequired() {
    return approvalRequired;
  }

  public void setApprovalRequired(Boolean approvalRequired) {
    this.approvalRequired = approvalRequired;
  }

  public InventoryCloneTemplateResponseDto allowNewAssetRegistration(Boolean allowNewAssetRegistration) {
    this.allowNewAssetRegistration = allowNewAssetRegistration;
    return this;
  }

  /**
   * Get allowNewAssetRegistration
   * @return allowNewAssetRegistration
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("allowNewAssetRegistration")
  public Boolean getAllowNewAssetRegistration() {
    return allowNewAssetRegistration;
  }

  public void setAllowNewAssetRegistration(Boolean allowNewAssetRegistration) {
    this.allowNewAssetRegistration = allowNewAssetRegistration;
  }

  public InventoryCloneTemplateResponseDto recurrenceRule(RecurrenceRuleEnum recurrenceRule) {
    this.recurrenceRule = recurrenceRule;
    return this;
  }

  /**
   * Get recurrenceRule
   * @return recurrenceRule
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("recurrenceRule")
  public RecurrenceRuleEnum getRecurrenceRule() {
    return recurrenceRule;
  }

  public void setRecurrenceRule(RecurrenceRuleEnum recurrenceRule) {
    this.recurrenceRule = recurrenceRule;
  }

  public InventoryCloneTemplateResponseDto excludedMemberIds(List<UUID> excludedMemberIds) {
    this.excludedMemberIds = excludedMemberIds;
    return this;
  }

  public InventoryCloneTemplateResponseDto addExcludedMemberIdsItem(UUID excludedMemberIdsItem) {
    if (this.excludedMemberIds == null) {
      this.excludedMemberIds = new ArrayList<>();
    }
    this.excludedMemberIds.add(excludedMemberIdsItem);
    return this;
  }

  /**
   * Get excludedMemberIds
   * @return excludedMemberIds
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("excludedMemberIds")
  public List<UUID> getExcludedMemberIds() {
    return excludedMemberIds;
  }

  public void setExcludedMemberIds(List<UUID> excludedMemberIds) {
    this.excludedMemberIds = excludedMemberIds;
  }

  public InventoryCloneTemplateResponseDto inspectorMemberIds(List<UUID> inspectorMemberIds) {
    this.inspectorMemberIds = inspectorMemberIds;
    return this;
  }

  public InventoryCloneTemplateResponseDto addInspectorMemberIdsItem(UUID inspectorMemberIdsItem) {
    if (this.inspectorMemberIds == null) {
      this.inspectorMemberIds = new ArrayList<>();
    }
    this.inspectorMemberIds.add(inspectorMemberIdsItem);
    return this;
  }

  /**
   * Get inspectorMemberIds
   * @return inspectorMemberIds
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("inspectorMemberIds")
  public List<UUID> getInspectorMemberIds() {
    return inspectorMemberIds;
  }

  public void setInspectorMemberIds(List<UUID> inspectorMemberIds) {
    this.inspectorMemberIds = inspectorMemberIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryCloneTemplateResponseDto inventoryCloneTemplateResponseDto = (InventoryCloneTemplateResponseDto) o;
    return Objects.equals(this.inventoryType, inventoryCloneTemplateResponseDto.inventoryType) &&
        Objects.equals(this.title, inventoryCloneTemplateResponseDto.title) &&
        Objects.equals(this.approvalRequired, inventoryCloneTemplateResponseDto.approvalRequired) &&
        Objects.equals(this.allowNewAssetRegistration, inventoryCloneTemplateResponseDto.allowNewAssetRegistration) &&
        Objects.equals(this.recurrenceRule, inventoryCloneTemplateResponseDto.recurrenceRule) &&
        Objects.equals(this.excludedMemberIds, inventoryCloneTemplateResponseDto.excludedMemberIds) &&
        Objects.equals(this.inspectorMemberIds, inventoryCloneTemplateResponseDto.inspectorMemberIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inventoryType, title, approvalRequired, allowNewAssetRegistration, recurrenceRule, excludedMemberIds, inspectorMemberIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryCloneTemplateResponseDto {\n");
    sb.append("    inventoryType: ").append(toIndentedString(inventoryType)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    approvalRequired: ").append(toIndentedString(approvalRequired)).append("\n");
    sb.append("    allowNewAssetRegistration: ").append(toIndentedString(allowNewAssetRegistration)).append("\n");
    sb.append("    recurrenceRule: ").append(toIndentedString(recurrenceRule)).append("\n");
    sb.append("    excludedMemberIds: ").append(toIndentedString(excludedMemberIds)).append("\n");
    sb.append("    inspectorMemberIds: ").append(toIndentedString(inspectorMemberIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
