/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventoryAnomalyBreakdownItemResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventoryAnomalyBreakdownItemResponseDto {

  /**
   * Gets or Sets anomalyType
   */
  public enum AnomalyTypeEnum {
    DAMAGE("DAMAGE"),
    
    LOCATION_MISMATCH("LOCATION_MISMATCH"),
    
    WRONG_HOLDER("WRONG_HOLDER"),
    
    OTHER("OTHER");

    private String value;

    AnomalyTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AnomalyTypeEnum fromValue(String value) {
      for (AnomalyTypeEnum b : AnomalyTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private AnomalyTypeEnum anomalyType;

  private Long count;

  public InventoryAnomalyBreakdownItemResponseDto anomalyType(AnomalyTypeEnum anomalyType) {
    this.anomalyType = anomalyType;
    return this;
  }

  /**
   * Get anomalyType
   * @return anomalyType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("anomalyType")
  public AnomalyTypeEnum getAnomalyType() {
    return anomalyType;
  }

  public void setAnomalyType(AnomalyTypeEnum anomalyType) {
    this.anomalyType = anomalyType;
  }

  public InventoryAnomalyBreakdownItemResponseDto count(Long count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("count")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryAnomalyBreakdownItemResponseDto inventoryAnomalyBreakdownItemResponseDto = (InventoryAnomalyBreakdownItemResponseDto) o;
    return Objects.equals(this.anomalyType, inventoryAnomalyBreakdownItemResponseDto.anomalyType) &&
        Objects.equals(this.count, inventoryAnomalyBreakdownItemResponseDto.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anomalyType, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryAnomalyBreakdownItemResponseDto {\n");
    sb.append("    anomalyType: ").append(toIndentedString(anomalyType)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
