/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventoryScheduleResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventoryScheduleResponseDto {

  /**
   * Gets or Sets inventoryType
   */
  public enum InventoryTypeEnum {
    MEMBER("MEMBER"),
    
    ADMIN("ADMIN");

    private String value;

    InventoryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InventoryTypeEnum fromValue(String value) {
      for (InventoryTypeEnum b : InventoryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private InventoryTypeEnum inventoryType;

  private UUID lastClosedInventoryId;

  private String lastClosedTitle;

  private OffsetDateTime lastClosedAt;

  /**
   * Gets or Sets recurrenceRule
   */
  public enum RecurrenceRuleEnum {
    QUARTERLY("QUARTERLY"),
    
    SEMIANNUAL("SEMIANNUAL"),
    
    ANNUAL("ANNUAL");

    private String value;

    RecurrenceRuleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RecurrenceRuleEnum fromValue(String value) {
      for (RecurrenceRuleEnum b : RecurrenceRuleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private RecurrenceRuleEnum recurrenceRule;

  private OffsetDateTime nextDueDate;

  private Boolean overdue;

  private Boolean nextCycleInProgress;

  public InventoryScheduleResponseDto inventoryType(InventoryTypeEnum inventoryType) {
    this.inventoryType = inventoryType;
    return this;
  }

  /**
   * Get inventoryType
   * @return inventoryType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("inventoryType")
  public InventoryTypeEnum getInventoryType() {
    return inventoryType;
  }

  public void setInventoryType(InventoryTypeEnum inventoryType) {
    this.inventoryType = inventoryType;
  }

  public InventoryScheduleResponseDto lastClosedInventoryId(UUID lastClosedInventoryId) {
    this.lastClosedInventoryId = lastClosedInventoryId;
    return this;
  }

  /**
   * Get lastClosedInventoryId
   * @return lastClosedInventoryId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("lastClosedInventoryId")
  public UUID getLastClosedInventoryId() {
    return lastClosedInventoryId;
  }

  public void setLastClosedInventoryId(UUID lastClosedInventoryId) {
    this.lastClosedInventoryId = lastClosedInventoryId;
  }

  public InventoryScheduleResponseDto lastClosedTitle(String lastClosedTitle) {
    this.lastClosedTitle = lastClosedTitle;
    return this;
  }

  /**
   * Get lastClosedTitle
   * @return lastClosedTitle
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("lastClosedTitle")
  public String getLastClosedTitle() {
    return lastClosedTitle;
  }

  public void setLastClosedTitle(String lastClosedTitle) {
    this.lastClosedTitle = lastClosedTitle;
  }

  public InventoryScheduleResponseDto lastClosedAt(OffsetDateTime lastClosedAt) {
    this.lastClosedAt = lastClosedAt;
    return this;
  }

  /**
   * Get lastClosedAt
   * @return lastClosedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("lastClosedAt")
  public OffsetDateTime getLastClosedAt() {
    return lastClosedAt;
  }

  public void setLastClosedAt(OffsetDateTime lastClosedAt) {
    this.lastClosedAt = lastClosedAt;
  }

  public InventoryScheduleResponseDto recurrenceRule(RecurrenceRuleEnum recurrenceRule) {
    this.recurrenceRule = recurrenceRule;
    return this;
  }

  /**
   * Get recurrenceRule
   * @return recurrenceRule
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("recurrenceRule")
  public RecurrenceRuleEnum getRecurrenceRule() {
    return recurrenceRule;
  }

  public void setRecurrenceRule(RecurrenceRuleEnum recurrenceRule) {
    this.recurrenceRule = recurrenceRule;
  }

  public InventoryScheduleResponseDto nextDueDate(OffsetDateTime nextDueDate) {
    this.nextDueDate = nextDueDate;
    return this;
  }

  /**
   * Get nextDueDate
   * @return nextDueDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("nextDueDate")
  public OffsetDateTime getNextDueDate() {
    return nextDueDate;
  }

  public void setNextDueDate(OffsetDateTime nextDueDate) {
    this.nextDueDate = nextDueDate;
  }

  public InventoryScheduleResponseDto overdue(Boolean overdue) {
    this.overdue = overdue;
    return this;
  }

  /**
   * Get overdue
   * @return overdue
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("overdue")
  public Boolean getOverdue() {
    return overdue;
  }

  public void setOverdue(Boolean overdue) {
    this.overdue = overdue;
  }

  public InventoryScheduleResponseDto nextCycleInProgress(Boolean nextCycleInProgress) {
    this.nextCycleInProgress = nextCycleInProgress;
    return this;
  }

  /**
   * Get nextCycleInProgress
   * @return nextCycleInProgress
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("nextCycleInProgress")
  public Boolean getNextCycleInProgress() {
    return nextCycleInProgress;
  }

  public void setNextCycleInProgress(Boolean nextCycleInProgress) {
    this.nextCycleInProgress = nextCycleInProgress;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryScheduleResponseDto inventoryScheduleResponseDto = (InventoryScheduleResponseDto) o;
    return Objects.equals(this.inventoryType, inventoryScheduleResponseDto.inventoryType) &&
        Objects.equals(this.lastClosedInventoryId, inventoryScheduleResponseDto.lastClosedInventoryId) &&
        Objects.equals(this.lastClosedTitle, inventoryScheduleResponseDto.lastClosedTitle) &&
        Objects.equals(this.lastClosedAt, inventoryScheduleResponseDto.lastClosedAt) &&
        Objects.equals(this.recurrenceRule, inventoryScheduleResponseDto.recurrenceRule) &&
        Objects.equals(this.nextDueDate, inventoryScheduleResponseDto.nextDueDate) &&
        Objects.equals(this.overdue, inventoryScheduleResponseDto.overdue) &&
        Objects.equals(this.nextCycleInProgress, inventoryScheduleResponseDto.nextCycleInProgress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inventoryType, lastClosedInventoryId, lastClosedTitle, lastClosedAt, recurrenceRule, nextDueDate, overdue, nextCycleInProgress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryScheduleResponseDto {\n");
    sb.append("    inventoryType: ").append(toIndentedString(inventoryType)).append("\n");
    sb.append("    lastClosedInventoryId: ").append(toIndentedString(lastClosedInventoryId)).append("\n");
    sb.append("    lastClosedTitle: ").append(toIndentedString(lastClosedTitle)).append("\n");
    sb.append("    lastClosedAt: ").append(toIndentedString(lastClosedAt)).append("\n");
    sb.append("    recurrenceRule: ").append(toIndentedString(recurrenceRule)).append("\n");
    sb.append("    nextDueDate: ").append(toIndentedString(nextDueDate)).append("\n");
    sb.append("    overdue: ").append(toIndentedString(overdue)).append("\n");
    sb.append("    nextCycleInProgress: ").append(toIndentedString(nextCycleInProgress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
