/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventorySelfConfirmPhotoRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventorySelfConfirmPhotoRequestDto {

  private UUID photoFileId;

  private OffsetDateTime capturedAt;

  private OffsetDateTime uploadedAt;


  public InventorySelfConfirmPhotoRequestDto photoFileId(UUID photoFileId) {
    this.photoFileId = photoFileId;
    return this;
  }

  /**
   * Get photoFileId
   * @return photoFileId
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("photoFileId")
  public UUID getPhotoFileId() {
    return photoFileId;
  }

  public void setPhotoFileId(UUID photoFileId) {
    this.photoFileId = photoFileId;
  }

  public InventorySelfConfirmPhotoRequestDto capturedAt(OffsetDateTime capturedAt) {
    this.capturedAt = capturedAt;
    return this;
  }

  /**
   * Get capturedAt
   * @return capturedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("capturedAt")
  public OffsetDateTime getCapturedAt() {
    return capturedAt;
  }

  public void setCapturedAt(OffsetDateTime capturedAt) {
    this.capturedAt = capturedAt;
  }

  public InventorySelfConfirmPhotoRequestDto uploadedAt(OffsetDateTime uploadedAt) {
    this.uploadedAt = uploadedAt;
    return this;
  }

  /**
   * Get uploadedAt
   * @return uploadedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("uploadedAt")
  public OffsetDateTime getUploadedAt() {
    return uploadedAt;
  }

  public void setUploadedAt(OffsetDateTime uploadedAt) {
    this.uploadedAt = uploadedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventorySelfConfirmPhotoRequestDto inventorySelfConfirmPhotoRequestDto = (InventorySelfConfirmPhotoRequestDto) o;
    return Objects.equals(this.photoFileId, inventorySelfConfirmPhotoRequestDto.photoFileId) &&
        Objects.equals(this.capturedAt, inventorySelfConfirmPhotoRequestDto.capturedAt) &&
        Objects.equals(this.uploadedAt, inventorySelfConfirmPhotoRequestDto.uploadedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(photoFileId, capturedAt, uploadedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventorySelfConfirmPhotoRequestDto {\n");
    sb.append("    photoFileId: ").append(toIndentedString(photoFileId)).append("\n");
    sb.append("    capturedAt: ").append(toIndentedString(capturedAt)).append("\n");
    sb.append("    uploadedAt: ").append(toIndentedString(uploadedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
