/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * InventoryClosureBreakdownItemResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class InventoryClosureBreakdownItemResponseDto {

  /**
   * Gets or Sets closureAction
   */
  public enum ClosureActionEnum {
    CARRY_OVER("CARRY_OVER"),
    
    MANUAL_VERIFY("MANUAL_VERIFY"),
    
    LOST("LOST");

    private String value;

    ClosureActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ClosureActionEnum fromValue(String value) {
      for (ClosureActionEnum b : ClosureActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ClosureActionEnum closureAction;

  /**
   * Gets or Sets closureReasonCode
   */
  public enum ClosureReasonCodeEnum {
    NOT_PARTICIPATED("NOT_PARTICIPATED"),
    
    ON_LEAVE("ON_LEAVE"),
    
    LABEL_DAMAGED("LABEL_DAMAGED"),
    
    LOCATION_UNKNOWN("LOCATION_UNKNOWN");

    private String value;

    ClosureReasonCodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ClosureReasonCodeEnum fromValue(String value) {
      for (ClosureReasonCodeEnum b : ClosureReasonCodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ClosureReasonCodeEnum closureReasonCode;

  private Long count;

  public InventoryClosureBreakdownItemResponseDto closureAction(ClosureActionEnum closureAction) {
    this.closureAction = closureAction;
    return this;
  }

  /**
   * Get closureAction
   * @return closureAction
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("closureAction")
  public ClosureActionEnum getClosureAction() {
    return closureAction;
  }

  public void setClosureAction(ClosureActionEnum closureAction) {
    this.closureAction = closureAction;
  }

  public InventoryClosureBreakdownItemResponseDto closureReasonCode(ClosureReasonCodeEnum closureReasonCode) {
    this.closureReasonCode = closureReasonCode;
    return this;
  }

  /**
   * Get closureReasonCode
   * @return closureReasonCode
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("closureReasonCode")
  public ClosureReasonCodeEnum getClosureReasonCode() {
    return closureReasonCode;
  }

  public void setClosureReasonCode(ClosureReasonCodeEnum closureReasonCode) {
    this.closureReasonCode = closureReasonCode;
  }

  public InventoryClosureBreakdownItemResponseDto count(Long count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("count")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryClosureBreakdownItemResponseDto inventoryClosureBreakdownItemResponseDto = (InventoryClosureBreakdownItemResponseDto) o;
    return Objects.equals(this.closureAction, inventoryClosureBreakdownItemResponseDto.closureAction) &&
        Objects.equals(this.closureReasonCode, inventoryClosureBreakdownItemResponseDto.closureReasonCode) &&
        Objects.equals(this.count, inventoryClosureBreakdownItemResponseDto.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(closureAction, closureReasonCode, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryClosureBreakdownItemResponseDto {\n");
    sb.append("    closureAction: ").append(toIndentedString(closureAction)).append("\n");
    sb.append("    closureReasonCode: ").append(toIndentedString(closureReasonCode)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
