/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * LicenseAssignedUserResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LicenseAssignedUserResponseDto {

  private UUID licenseAssignedUserId;

  private UUID licenseId;

  private String licenseName;

  private UUID memberId;

  private UUID licensePurchaseRecordId;

  private Boolean unlinkedPurchase;

  private OffsetDateTime assignedAt;

  private UUID assignedBy;

  private OffsetDateTime releasedAt;

  private Boolean active;

  private Boolean releaseRequestedYn;

  private OffsetDateTime releaseRequestedAt;

  public LicenseAssignedUserResponseDto licenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
    return this;
  }

  /**
   * Get licenseAssignedUserId
   * @return licenseAssignedUserId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseAssignedUserId")
  public UUID getLicenseAssignedUserId() {
    return licenseAssignedUserId;
  }

  public void setLicenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
  }

  public LicenseAssignedUserResponseDto licenseId(UUID licenseId) {
    this.licenseId = licenseId;
    return this;
  }

  /**
   * Get licenseId
   * @return licenseId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseId")
  public UUID getLicenseId() {
    return licenseId;
  }

  public void setLicenseId(UUID licenseId) {
    this.licenseId = licenseId;
  }

  public LicenseAssignedUserResponseDto licenseName(String licenseName) {
    this.licenseName = licenseName;
    return this;
  }

  /**
   * Get licenseName
   * @return licenseName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("licenseName")
  public String getLicenseName() {
    return licenseName;
  }

  public void setLicenseName(String licenseName) {
    this.licenseName = licenseName;
  }

  public LicenseAssignedUserResponseDto memberId(UUID memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Get memberId
   * @return memberId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("memberId")
  public UUID getMemberId() {
    return memberId;
  }

  public void setMemberId(UUID memberId) {
    this.memberId = memberId;
  }

  public LicenseAssignedUserResponseDto licensePurchaseRecordId(UUID licensePurchaseRecordId) {
    this.licensePurchaseRecordId = licensePurchaseRecordId;
    return this;
  }

  /**
   * Get licensePurchaseRecordId
   * @return licensePurchaseRecordId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licensePurchaseRecordId")
  public UUID getLicensePurchaseRecordId() {
    return licensePurchaseRecordId;
  }

  public void setLicensePurchaseRecordId(UUID licensePurchaseRecordId) {
    this.licensePurchaseRecordId = licensePurchaseRecordId;
  }

  public LicenseAssignedUserResponseDto unlinkedPurchase(Boolean unlinkedPurchase) {
    this.unlinkedPurchase = unlinkedPurchase;
    return this;
  }

  /**
   * 파생값 - 구매내역과 연결되지 않은 배정이면 true
   * @return unlinkedPurchase
  */
  
  @ApiModelProperty(value = "파생값 - 구매내역과 연결되지 않은 배정이면 true")
  @JsonProperty("unlinkedPurchase")
  public Boolean getUnlinkedPurchase() {
    return unlinkedPurchase;
  }

  public void setUnlinkedPurchase(Boolean unlinkedPurchase) {
    this.unlinkedPurchase = unlinkedPurchase;
  }

  public LicenseAssignedUserResponseDto assignedAt(OffsetDateTime assignedAt) {
    this.assignedAt = assignedAt;
    return this;
  }

  /**
   * Get assignedAt
   * @return assignedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("assignedAt")
  public OffsetDateTime getAssignedAt() {
    return assignedAt;
  }

  public void setAssignedAt(OffsetDateTime assignedAt) {
    this.assignedAt = assignedAt;
  }

  public LicenseAssignedUserResponseDto assignedBy(UUID assignedBy) {
    this.assignedBy = assignedBy;
    return this;
  }

  /**
   * Get assignedBy
   * @return assignedBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("assignedBy")
  public UUID getAssignedBy() {
    return assignedBy;
  }

  public void setAssignedBy(UUID assignedBy) {
    this.assignedBy = assignedBy;
  }

  public LicenseAssignedUserResponseDto releasedAt(OffsetDateTime releasedAt) {
    this.releasedAt = releasedAt;
    return this;
  }

  /**
   * Get releasedAt
   * @return releasedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("releasedAt")
  public OffsetDateTime getReleasedAt() {
    return releasedAt;
  }

  public void setReleasedAt(OffsetDateTime releasedAt) {
    this.releasedAt = releasedAt;
  }

  public LicenseAssignedUserResponseDto active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("active")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public LicenseAssignedUserResponseDto releaseRequestedYn(Boolean releaseRequestedYn) {
    this.releaseRequestedYn = releaseRequestedYn;
    return this;
  }

  /**
   * Get releaseRequestedYn
   * @return releaseRequestedYn
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("releaseRequestedYn")
  public Boolean getReleaseRequestedYn() {
    return releaseRequestedYn;
  }

  public void setReleaseRequestedYn(Boolean releaseRequestedYn) {
    this.releaseRequestedYn = releaseRequestedYn;
  }

  public LicenseAssignedUserResponseDto releaseRequestedAt(OffsetDateTime releaseRequestedAt) {
    this.releaseRequestedAt = releaseRequestedAt;
    return this;
  }

  /**
   * Get releaseRequestedAt
   * @return releaseRequestedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("releaseRequestedAt")
  public OffsetDateTime getReleaseRequestedAt() {
    return releaseRequestedAt;
  }

  public void setReleaseRequestedAt(OffsetDateTime releaseRequestedAt) {
    this.releaseRequestedAt = releaseRequestedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseAssignedUserResponseDto licenseAssignedUserResponseDto = (LicenseAssignedUserResponseDto) o;
    return Objects.equals(this.licenseAssignedUserId, licenseAssignedUserResponseDto.licenseAssignedUserId) &&
        Objects.equals(this.licenseId, licenseAssignedUserResponseDto.licenseId) &&
        Objects.equals(this.licenseName, licenseAssignedUserResponseDto.licenseName) &&
        Objects.equals(this.memberId, licenseAssignedUserResponseDto.memberId) &&
        Objects.equals(this.licensePurchaseRecordId, licenseAssignedUserResponseDto.licensePurchaseRecordId) &&
        Objects.equals(this.unlinkedPurchase, licenseAssignedUserResponseDto.unlinkedPurchase) &&
        Objects.equals(this.assignedAt, licenseAssignedUserResponseDto.assignedAt) &&
        Objects.equals(this.assignedBy, licenseAssignedUserResponseDto.assignedBy) &&
        Objects.equals(this.releasedAt, licenseAssignedUserResponseDto.releasedAt) &&
        Objects.equals(this.active, licenseAssignedUserResponseDto.active) &&
        Objects.equals(this.releaseRequestedYn, licenseAssignedUserResponseDto.releaseRequestedYn) &&
        Objects.equals(this.releaseRequestedAt, licenseAssignedUserResponseDto.releaseRequestedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(licenseAssignedUserId, licenseId, licenseName, memberId, licensePurchaseRecordId, unlinkedPurchase, assignedAt, assignedBy, releasedAt, active, releaseRequestedYn, releaseRequestedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseAssignedUserResponseDto {\n");
    sb.append("    licenseAssignedUserId: ").append(toIndentedString(licenseAssignedUserId)).append("\n");
    sb.append("    licenseId: ").append(toIndentedString(licenseId)).append("\n");
    sb.append("    licenseName: ").append(toIndentedString(licenseName)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    licensePurchaseRecordId: ").append(toIndentedString(licensePurchaseRecordId)).append("\n");
    sb.append("    unlinkedPurchase: ").append(toIndentedString(unlinkedPurchase)).append("\n");
    sb.append("    assignedAt: ").append(toIndentedString(assignedAt)).append("\n");
    sb.append("    assignedBy: ").append(toIndentedString(assignedBy)).append("\n");
    sb.append("    releasedAt: ").append(toIndentedString(releasedAt)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    releaseRequestedYn: ").append(toIndentedString(releaseRequestedYn)).append("\n");
    sb.append("    releaseRequestedAt: ").append(toIndentedString(releaseRequestedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
