/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * LicenseResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LicenseResponseDto {

  private UUID licenseId;

  private String name;

  private String memo;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  private Integer purchasedQuantity;

  private Integer assignedQuantity;

  private Integer remainingQuantity;

  private Boolean overAssigned;

  public LicenseResponseDto licenseId(UUID licenseId) {
    this.licenseId = licenseId;
    return this;
  }

  /**
   * Get licenseId
   * @return licenseId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseId")
  public UUID getLicenseId() {
    return licenseId;
  }

  public void setLicenseId(UUID licenseId) {
    this.licenseId = licenseId;
  }

  public LicenseResponseDto name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LicenseResponseDto memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   * @return memo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("memo")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public LicenseResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public LicenseResponseDto purchasedQuantity(Integer purchasedQuantity) {
    this.purchasedQuantity = purchasedQuantity;
    return this;
  }

  /**
   * 파생값 - 구매내역 수량 합계(보유)
   * @return purchasedQuantity
  */
  
  @ApiModelProperty(value = "파생값 - 구매내역 수량 합계(보유)")
  @JsonProperty("purchasedQuantity")
  public Integer getPurchasedQuantity() {
    return purchasedQuantity;
  }

  public void setPurchasedQuantity(Integer purchasedQuantity) {
    this.purchasedQuantity = purchasedQuantity;
  }

  public LicenseResponseDto assignedQuantity(Integer assignedQuantity) {
    this.assignedQuantity = assignedQuantity;
    return this;
  }

  /**
   * 파생값 - 현재 유효한 배정 건수
   * @return assignedQuantity
  */
  
  @ApiModelProperty(value = "파생값 - 현재 유효한 배정 건수")
  @JsonProperty("assignedQuantity")
  public Integer getAssignedQuantity() {
    return assignedQuantity;
  }

  public void setAssignedQuantity(Integer assignedQuantity) {
    this.assignedQuantity = assignedQuantity;
  }

  public LicenseResponseDto remainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
    return this;
  }

  /**
   * 파생값 - 보유 - 배정. 음수면 초과배정
   * @return remainingQuantity
  */
  
  @ApiModelProperty(value = "파생값 - 보유 - 배정. 음수면 초과배정")
  @JsonProperty("remainingQuantity")
  public Integer getRemainingQuantity() {
    return remainingQuantity;
  }

  public void setRemainingQuantity(Integer remainingQuantity) {
    this.remainingQuantity = remainingQuantity;
  }

  public LicenseResponseDto overAssigned(Boolean overAssigned) {
    this.overAssigned = overAssigned;
    return this;
  }

  /**
   * Get overAssigned
   * @return overAssigned
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("overAssigned")
  public Boolean getOverAssigned() {
    return overAssigned;
  }

  public void setOverAssigned(Boolean overAssigned) {
    this.overAssigned = overAssigned;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseResponseDto licenseResponseDto = (LicenseResponseDto) o;
    return Objects.equals(this.licenseId, licenseResponseDto.licenseId) &&
        Objects.equals(this.name, licenseResponseDto.name) &&
        Objects.equals(this.memo, licenseResponseDto.memo) &&
        Objects.equals(this.status, licenseResponseDto.status) &&
        Objects.equals(this.purchasedQuantity, licenseResponseDto.purchasedQuantity) &&
        Objects.equals(this.assignedQuantity, licenseResponseDto.assignedQuantity) &&
        Objects.equals(this.remainingQuantity, licenseResponseDto.remainingQuantity) &&
        Objects.equals(this.overAssigned, licenseResponseDto.overAssigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(licenseId, name, memo, status, purchasedQuantity, assignedQuantity, remainingQuantity, overAssigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseResponseDto {\n");
    sb.append("    licenseId: ").append(toIndentedString(licenseId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    purchasedQuantity: ").append(toIndentedString(purchasedQuantity)).append("\n");
    sb.append("    assignedQuantity: ").append(toIndentedString(assignedQuantity)).append("\n");
    sb.append("    remainingQuantity: ").append(toIndentedString(remainingQuantity)).append("\n");
    sb.append("    overAssigned: ").append(toIndentedString(overAssigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
