/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * LicensePurchaseRecordResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LicensePurchaseRecordResponseDto {

  private UUID licensePurchaseRecordId;

  private UUID vendorId;

  private String vendorName;

  private OffsetDateTime purchaseDate;

  private Integer quantity;

  private BigDecimal unitPrice;

  private BigDecimal totalAmount;

  private String memo;

  public LicensePurchaseRecordResponseDto licensePurchaseRecordId(UUID licensePurchaseRecordId) {
    this.licensePurchaseRecordId = licensePurchaseRecordId;
    return this;
  }

  /**
   * Get licensePurchaseRecordId
   * @return licensePurchaseRecordId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licensePurchaseRecordId")
  public UUID getLicensePurchaseRecordId() {
    return licensePurchaseRecordId;
  }

  public void setLicensePurchaseRecordId(UUID licensePurchaseRecordId) {
    this.licensePurchaseRecordId = licensePurchaseRecordId;
  }

  public LicensePurchaseRecordResponseDto vendorId(UUID vendorId) {
    this.vendorId = vendorId;
    return this;
  }

  /**
   * Get vendorId
   * @return vendorId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("vendorId")
  public UUID getVendorId() {
    return vendorId;
  }

  public void setVendorId(UUID vendorId) {
    this.vendorId = vendorId;
  }

  public LicensePurchaseRecordResponseDto vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

  /**
   * Get vendorName
   * @return vendorName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("vendorName")
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }

  public LicensePurchaseRecordResponseDto purchaseDate(OffsetDateTime purchaseDate) {
    this.purchaseDate = purchaseDate;
    return this;
  }

  /**
   * Get purchaseDate
   * @return purchaseDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("purchaseDate")
  public OffsetDateTime getPurchaseDate() {
    return purchaseDate;
  }

  public void setPurchaseDate(OffsetDateTime purchaseDate) {
    this.purchaseDate = purchaseDate;
  }

  public LicensePurchaseRecordResponseDto quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("quantity")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public LicensePurchaseRecordResponseDto unitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

  /**
   * Get unitPrice
   * @return unitPrice
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("unitPrice")
  public BigDecimal getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }

  public LicensePurchaseRecordResponseDto totalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  /**
   * Get totalAmount
   * @return totalAmount
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("totalAmount")
  public BigDecimal getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
  }

  public LicensePurchaseRecordResponseDto memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   * @return memo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("memo")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicensePurchaseRecordResponseDto licensePurchaseRecordResponseDto = (LicensePurchaseRecordResponseDto) o;
    return Objects.equals(this.licensePurchaseRecordId, licensePurchaseRecordResponseDto.licensePurchaseRecordId) &&
        Objects.equals(this.vendorId, licensePurchaseRecordResponseDto.vendorId) &&
        Objects.equals(this.vendorName, licensePurchaseRecordResponseDto.vendorName) &&
        Objects.equals(this.purchaseDate, licensePurchaseRecordResponseDto.purchaseDate) &&
        Objects.equals(this.quantity, licensePurchaseRecordResponseDto.quantity) &&
        Objects.equals(this.unitPrice, licensePurchaseRecordResponseDto.unitPrice) &&
        Objects.equals(this.totalAmount, licensePurchaseRecordResponseDto.totalAmount) &&
        Objects.equals(this.memo, licensePurchaseRecordResponseDto.memo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(licensePurchaseRecordId, vendorId, vendorName, purchaseDate, quantity, unitPrice, totalAmount, memo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicensePurchaseRecordResponseDto {\n");
    sb.append("    licensePurchaseRecordId: ").append(toIndentedString(licensePurchaseRecordId)).append("\n");
    sb.append("    vendorId: ").append(toIndentedString(vendorId)).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    purchaseDate: ").append(toIndentedString(purchaseDate)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
