/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * LicenseAssignedUserIdResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LicenseAssignedUserIdResponseDto {

  private UUID licenseAssignedUserId;

  public LicenseAssignedUserIdResponseDto licenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
    return this;
  }

  /**
   * Get licenseAssignedUserId
   * @return licenseAssignedUserId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseAssignedUserId")
  public UUID getLicenseAssignedUserId() {
    return licenseAssignedUserId;
  }

  public void setLicenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseAssignedUserIdResponseDto licenseAssignedUserIdResponseDto = (LicenseAssignedUserIdResponseDto) o;
    return Objects.equals(this.licenseAssignedUserId, licenseAssignedUserIdResponseDto.licenseAssignedUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(licenseAssignedUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseAssignedUserIdResponseDto {\n");
    sb.append("    licenseAssignedUserId: ").append(toIndentedString(licenseAssignedUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
