/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * LoanReturnRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LoanReturnRequestDto {

  private Boolean abnormal;

  public LoanReturnRequestDto abnormal(Boolean abnormal) {
    this.abnormal = abnormal;
    return this;
  }

  /**
   * true면 이상 반납 - 자산이 수리중으로 전환됩니다(L3)
   * @return abnormal
  */
  
  @ApiModelProperty(value = "true면 이상 반납 - 자산이 수리중으로 전환됩니다(L3)")
  @JsonProperty("abnormal")
  public Boolean getAbnormal() {
    return abnormal;
  }

  public void setAbnormal(Boolean abnormal) {
    this.abnormal = abnormal;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanReturnRequestDto loanReturnRequestDto = (LoanReturnRequestDto) o;
    return Objects.equals(this.abnormal, loanReturnRequestDto.abnormal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abnormal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanReturnRequestDto {\n");
    sb.append("    abnormal: ").append(toIndentedString(abnormal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
