/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * ProcessConfigResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProcessConfigResponseDto {

  private Boolean loanEnabled;

  private Integer defaultLoanDays;

  private Boolean requireApproval;

  private Boolean blockOnOverdue;

  private Integer maxExtendCount;

  private Integer concurrentLimit = null;

  private Boolean acknowledgementEnabled;

  private Boolean requireManagerApproval;

  private Boolean blockUnapprovedView;

  private Boolean autoRequestOnAssign;

  private Integer approvalDueDays;

  private Integer remindIntervalDays;

  /**
   * 반납 승인 시 기본 제안 생애상태
   */
  public enum DefaultReturnStatusEnum {
    USE("USE"),
    
    STORAGE("STORAGE"),
    
    REPAIR("REPAIR"),
    
    DISUSE("DISUSE"),
    
    DISPOSED("DISPOSED");

    private String value;

    DefaultReturnStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DefaultReturnStatusEnum fromValue(String value) {
      for (DefaultReturnStatusEnum b : DefaultReturnStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private DefaultReturnStatusEnum defaultReturnStatus;

  public ProcessConfigResponseDto loanEnabled(Boolean loanEnabled) {
    this.loanEnabled = loanEnabled;
    return this;
  }

  /**
   * 대여 프로세스 On/Off
   * @return loanEnabled
  */
  
  @ApiModelProperty(value = "대여 프로세스 On/Off")
  @JsonProperty("loanEnabled")
  public Boolean getLoanEnabled() {
    return loanEnabled;
  }

  public void setLoanEnabled(Boolean loanEnabled) {
    this.loanEnabled = loanEnabled;
  }

  public ProcessConfigResponseDto defaultLoanDays(Integer defaultLoanDays) {
    this.defaultLoanDays = defaultLoanDays;
    return this;
  }

  /**
   * Q-38 전역 기본 대여 기한(일)
   * @return defaultLoanDays
  */
  
  @ApiModelProperty(example = "7", value = "Q-38 전역 기본 대여 기한(일)")
  @JsonProperty("defaultLoanDays")
  public Integer getDefaultLoanDays() {
    return defaultLoanDays;
  }

  public void setDefaultLoanDays(Integer defaultLoanDays) {
    this.defaultLoanDays = defaultLoanDays;
  }

  public ProcessConfigResponseDto requireApproval(Boolean requireApproval) {
    this.requireApproval = requireApproval;
    return this;
  }

  /**
   * Q-39 대여 시 관리자 승인 필요 여부 (false=QR 스캔 즉시 대여)
   * @return requireApproval
  */
  
  @ApiModelProperty(value = "Q-39 대여 시 관리자 승인 필요 여부 (false=QR 스캔 즉시 대여)")
  @JsonProperty("requireApproval")
  public Boolean getRequireApproval() {
    return requireApproval;
  }

  public void setRequireApproval(Boolean requireApproval) {
    this.requireApproval = requireApproval;
  }

  public ProcessConfigResponseDto blockOnOverdue(Boolean blockOnOverdue) {
    this.blockOnOverdue = blockOnOverdue;
    return this;
  }

  /**
   * Q-40 연체 중 신규 대여 차단 여부
   * @return blockOnOverdue
  */
  
  @ApiModelProperty(value = "Q-40 연체 중 신규 대여 차단 여부")
  @JsonProperty("blockOnOverdue")
  public Boolean getBlockOnOverdue() {
    return blockOnOverdue;
  }

  public void setBlockOnOverdue(Boolean blockOnOverdue) {
    this.blockOnOverdue = blockOnOverdue;
  }

  public ProcessConfigResponseDto maxExtendCount(Integer maxExtendCount) {
    this.maxExtendCount = maxExtendCount;
    return this;
  }

  /**
   * Q-41 대여 연장 최대 횟수
   * @return maxExtendCount
  */
  
  @ApiModelProperty(example = "1", value = "Q-41 대여 연장 최대 횟수")
  @JsonProperty("maxExtendCount")
  public Integer getMaxExtendCount() {
    return maxExtendCount;
  }

  public void setMaxExtendCount(Integer maxExtendCount) {
    this.maxExtendCount = maxExtendCount;
  }

  public ProcessConfigResponseDto concurrentLimit(Integer concurrentLimit) {
    this.concurrentLimit = concurrentLimit;
    return this;
  }

  /**
   * Q-42 1인 동시 대여 한도 (null=제한 없음)
   * @return concurrentLimit
  */
  
  @ApiModelProperty(value = "Q-42 1인 동시 대여 한도 (null=제한 없음)")
  @JsonProperty("concurrentLimit")
  public Integer getConcurrentLimit() {
    return concurrentLimit;
  }

  public void setConcurrentLimit(Integer concurrentLimit) {
    this.concurrentLimit = concurrentLimit;
  }

  public ProcessConfigResponseDto acknowledgementEnabled(Boolean acknowledgementEnabled) {
    this.acknowledgementEnabled = acknowledgementEnabled;
    return this;
  }

  /**
   * 수령·반납 승인 프로세스 On/Off
   * @return acknowledgementEnabled
  */
  
  @ApiModelProperty(value = "수령·반납 승인 프로세스 On/Off")
  @JsonProperty("acknowledgementEnabled")
  public Boolean getAcknowledgementEnabled() {
    return acknowledgementEnabled;
  }

  public void setAcknowledgementEnabled(Boolean acknowledgementEnabled) {
    this.acknowledgementEnabled = acknowledgementEnabled;
  }

  public ProcessConfigResponseDto requireManagerApproval(Boolean requireManagerApproval) {
    this.requireManagerApproval = requireManagerApproval;
    return this;
  }

  /**
   * Q-43 반납 시 담당자 승인 필수 여부
   * @return requireManagerApproval
  */
  
  @ApiModelProperty(value = "Q-43 반납 시 담당자 승인 필수 여부")
  @JsonProperty("requireManagerApproval")
  public Boolean getRequireManagerApproval() {
    return requireManagerApproval;
  }

  public void setRequireManagerApproval(Boolean requireManagerApproval) {
    this.requireManagerApproval = requireManagerApproval;
  }

  public ProcessConfigResponseDto blockUnapprovedView(Boolean blockUnapprovedView) {
    this.blockUnapprovedView = blockUnapprovedView;
    return this;
  }

  /**
   * Q-44 미승인 자산 임직원 조회 차단 여부
   * @return blockUnapprovedView
  */
  
  @ApiModelProperty(value = "Q-44 미승인 자산 임직원 조회 차단 여부")
  @JsonProperty("blockUnapprovedView")
  public Boolean getBlockUnapprovedView() {
    return blockUnapprovedView;
  }

  public void setBlockUnapprovedView(Boolean blockUnapprovedView) {
    this.blockUnapprovedView = blockUnapprovedView;
  }

  public ProcessConfigResponseDto autoRequestOnAssign(Boolean autoRequestOnAssign) {
    this.autoRequestOnAssign = autoRequestOnAssign;
    return this;
  }

  /**
   * Q-45 배정 시 확인서 자동 요청 여부 (false=수동 요청)
   * @return autoRequestOnAssign
  */
  
  @ApiModelProperty(value = "Q-45 배정 시 확인서 자동 요청 여부 (false=수동 요청)")
  @JsonProperty("autoRequestOnAssign")
  public Boolean getAutoRequestOnAssign() {
    return autoRequestOnAssign;
  }

  public void setAutoRequestOnAssign(Boolean autoRequestOnAssign) {
    this.autoRequestOnAssign = autoRequestOnAssign;
  }

  public ProcessConfigResponseDto approvalDueDays(Integer approvalDueDays) {
    this.approvalDueDays = approvalDueDays;
    return this;
  }

  /**
   * 확인서 승인 기한(일)
   * @return approvalDueDays
  */
  
  @ApiModelProperty(example = "3", value = "확인서 승인 기한(일)")
  @JsonProperty("approvalDueDays")
  public Integer getApprovalDueDays() {
    return approvalDueDays;
  }

  public void setApprovalDueDays(Integer approvalDueDays) {
    this.approvalDueDays = approvalDueDays;
  }

  public ProcessConfigResponseDto remindIntervalDays(Integer remindIntervalDays) {
    this.remindIntervalDays = remindIntervalDays;
    return this;
  }

  /**
   * 확인서 리마인드 재발송 주기(일)
   * @return remindIntervalDays
  */
  
  @ApiModelProperty(example = "3", value = "확인서 리마인드 재발송 주기(일)")
  @JsonProperty("remindIntervalDays")
  public Integer getRemindIntervalDays() {
    return remindIntervalDays;
  }

  public void setRemindIntervalDays(Integer remindIntervalDays) {
    this.remindIntervalDays = remindIntervalDays;
  }

  public ProcessConfigResponseDto defaultReturnStatus(DefaultReturnStatusEnum defaultReturnStatus) {
    this.defaultReturnStatus = defaultReturnStatus;
    return this;
  }

  /**
   * 반납 승인 시 기본 제안 생애상태
   * @return defaultReturnStatus
  */
  
  @ApiModelProperty(value = "반납 승인 시 기본 제안 생애상태")
  @JsonProperty("defaultReturnStatus")
  public DefaultReturnStatusEnum getDefaultReturnStatus() {
    return defaultReturnStatus;
  }

  public void setDefaultReturnStatus(DefaultReturnStatusEnum defaultReturnStatus) {
    this.defaultReturnStatus = defaultReturnStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessConfigResponseDto processConfigResponseDto = (ProcessConfigResponseDto) o;
    return Objects.equals(this.loanEnabled, processConfigResponseDto.loanEnabled) &&
        Objects.equals(this.defaultLoanDays, processConfigResponseDto.defaultLoanDays) &&
        Objects.equals(this.requireApproval, processConfigResponseDto.requireApproval) &&
        Objects.equals(this.blockOnOverdue, processConfigResponseDto.blockOnOverdue) &&
        Objects.equals(this.maxExtendCount, processConfigResponseDto.maxExtendCount) &&
        Objects.equals(this.concurrentLimit, processConfigResponseDto.concurrentLimit) &&
        Objects.equals(this.acknowledgementEnabled, processConfigResponseDto.acknowledgementEnabled) &&
        Objects.equals(this.requireManagerApproval, processConfigResponseDto.requireManagerApproval) &&
        Objects.equals(this.blockUnapprovedView, processConfigResponseDto.blockUnapprovedView) &&
        Objects.equals(this.autoRequestOnAssign, processConfigResponseDto.autoRequestOnAssign) &&
        Objects.equals(this.approvalDueDays, processConfigResponseDto.approvalDueDays) &&
        Objects.equals(this.remindIntervalDays, processConfigResponseDto.remindIntervalDays) &&
        Objects.equals(this.defaultReturnStatus, processConfigResponseDto.defaultReturnStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanEnabled, defaultLoanDays, requireApproval, blockOnOverdue, maxExtendCount, concurrentLimit, acknowledgementEnabled, requireManagerApproval, blockUnapprovedView, autoRequestOnAssign, approvalDueDays, remindIntervalDays, defaultReturnStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessConfigResponseDto {\n");
    sb.append("    loanEnabled: ").append(toIndentedString(loanEnabled)).append("\n");
    sb.append("    defaultLoanDays: ").append(toIndentedString(defaultLoanDays)).append("\n");
    sb.append("    requireApproval: ").append(toIndentedString(requireApproval)).append("\n");
    sb.append("    blockOnOverdue: ").append(toIndentedString(blockOnOverdue)).append("\n");
    sb.append("    maxExtendCount: ").append(toIndentedString(maxExtendCount)).append("\n");
    sb.append("    concurrentLimit: ").append(toIndentedString(concurrentLimit)).append("\n");
    sb.append("    acknowledgementEnabled: ").append(toIndentedString(acknowledgementEnabled)).append("\n");
    sb.append("    requireManagerApproval: ").append(toIndentedString(requireManagerApproval)).append("\n");
    sb.append("    blockUnapprovedView: ").append(toIndentedString(blockUnapprovedView)).append("\n");
    sb.append("    autoRequestOnAssign: ").append(toIndentedString(autoRequestOnAssign)).append("\n");
    sb.append("    approvalDueDays: ").append(toIndentedString(approvalDueDays)).append("\n");
    sb.append("    remindIntervalDays: ").append(toIndentedString(remindIntervalDays)).append("\n");
    sb.append("    defaultReturnStatus: ").append(toIndentedString(defaultReturnStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
