/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TangibleAssetDisposeRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TangibleAssetDisposeRequestDto {

  /**
   * Gets or Sets disposalReasonCode
   */
  public enum DisposalReasonCodeEnum {
    SALE("SALE"),
    
    SCRAP("SCRAP"),
    
    DONATION("DONATION"),
    
    LOSS("LOSS"),
    
    THEFT("THEFT"),
    
    OTHER("OTHER");

    private String value;

    DisposalReasonCodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DisposalReasonCodeEnum fromValue(String value) {
      for (DisposalReasonCodeEnum b : DisposalReasonCodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private DisposalReasonCodeEnum disposalReasonCode;

  private BigDecimal disposalAmount;

  private String counterparty;

  private String memo;


  public TangibleAssetDisposeRequestDto disposalReasonCode(DisposalReasonCodeEnum disposalReasonCode) {
    this.disposalReasonCode = disposalReasonCode;
    return this;
  }

  /**
   * Get disposalReasonCode
   * @return disposalReasonCode
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("disposalReasonCode")
  public DisposalReasonCodeEnum getDisposalReasonCode() {
    return disposalReasonCode;
  }

  public void setDisposalReasonCode(DisposalReasonCodeEnum disposalReasonCode) {
    this.disposalReasonCode = disposalReasonCode;
  }

  public TangibleAssetDisposeRequestDto disposalAmount(BigDecimal disposalAmount) {
    this.disposalAmount = disposalAmount;
    return this;
  }

  /**
   * 매각·처분 금액 - 폐기 등 금액이 없으면 생략
   * @return disposalAmount
  */
  @Valid 
  @ApiModelProperty(value = "매각·처분 금액 - 폐기 등 금액이 없으면 생략")
  @JsonProperty("disposalAmount")
  public BigDecimal getDisposalAmount() {
    return disposalAmount;
  }

  public void setDisposalAmount(BigDecimal disposalAmount) {
    this.disposalAmount = disposalAmount;
  }

  public TangibleAssetDisposeRequestDto counterparty(String counterparty) {
    this.counterparty = counterparty;
    return this;
  }

  /**
   * 매각 상대방 - 해당 없으면 생략
   * @return counterparty
  */
  
  @ApiModelProperty(value = "매각 상대방 - 해당 없으면 생략")
  @JsonProperty("counterparty")
  public String getCounterparty() {
    return counterparty;
  }

  public void setCounterparty(String counterparty) {
    this.counterparty = counterparty;
  }

  public TangibleAssetDisposeRequestDto memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   * @return memo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("memo")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TangibleAssetDisposeRequestDto tangibleAssetDisposeRequestDto = (TangibleAssetDisposeRequestDto) o;
    return Objects.equals(this.disposalReasonCode, tangibleAssetDisposeRequestDto.disposalReasonCode) &&
        Objects.equals(this.disposalAmount, tangibleAssetDisposeRequestDto.disposalAmount) &&
        Objects.equals(this.counterparty, tangibleAssetDisposeRequestDto.counterparty) &&
        Objects.equals(this.memo, tangibleAssetDisposeRequestDto.memo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disposalReasonCode, disposalAmount, counterparty, memo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TangibleAssetDisposeRequestDto {\n");
    sb.append("    disposalReasonCode: ").append(toIndentedString(disposalReasonCode)).append("\n");
    sb.append("    disposalAmount: ").append(toIndentedString(disposalAmount)).append("\n");
    sb.append("    counterparty: ").append(toIndentedString(counterparty)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
