/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TangibleAssetBatchModifyRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TangibleAssetBatchModifyRequestDto {

  @Valid
  private List<UUID> tangibleAssetIds = new ArrayList<>();

  private UUID categoryId;

  private UUID locationId;

  /**
   * 지정 시에만 생애 상태를 변경합니다.
   */
  public enum LifeStatusEnum {
    USE("USE"),
    
    STORAGE("STORAGE"),
    
    REPAIR("REPAIR"),
    
    DISUSE("DISUSE"),
    
    DISPOSED("DISPOSED");

    private String value;

    LifeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LifeStatusEnum fromValue(String value) {
      for (LifeStatusEnum b : LifeStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private LifeStatusEnum lifeStatus;

  /**
   * 지정 시에만 배정 형태를 변경합니다.
   */
  public enum AssignTypeEnum {
    UNASSIGNED("UNASSIGNED"),
    
    PERSONAL("PERSONAL"),
    
    SHARED("SHARED"),
    
    LOANABLE("LOANABLE"),
    
    ON_LOAN("ON_LOAN");

    private String value;

    AssignTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AssignTypeEnum fromValue(String value) {
      for (AssignTypeEnum b : AssignTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private AssignTypeEnum assignType;

  private UUID currentMemberId;


  public TangibleAssetBatchModifyRequestDto tangibleAssetIds(List<UUID> tangibleAssetIds) {
    this.tangibleAssetIds = tangibleAssetIds;
    return this;
  }

  public TangibleAssetBatchModifyRequestDto addTangibleAssetIdsItem(UUID tangibleAssetIdsItem) {
    if (this.tangibleAssetIds == null) {
      this.tangibleAssetIds = new ArrayList<>();
    }
    this.tangibleAssetIds.add(tangibleAssetIdsItem);
    return this;
  }

  /**
   * 일괄 변경할 유형자산 ID 목록
   * @return tangibleAssetIds
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "일괄 변경할 유형자산 ID 목록")
  @JsonProperty("tangibleAssetIds")
  public List<UUID> getTangibleAssetIds() {
    return tangibleAssetIds;
  }

  public void setTangibleAssetIds(List<UUID> tangibleAssetIds) {
    this.tangibleAssetIds = tangibleAssetIds;
  }

  public TangibleAssetBatchModifyRequestDto categoryId(UUID categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * 지정 시에만 종류를 변경합니다.
   * @return categoryId
  */
  @Valid 
  @ApiModelProperty(value = "지정 시에만 종류를 변경합니다.")
  @JsonProperty("categoryId")
  public UUID getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(UUID categoryId) {
    this.categoryId = categoryId;
  }

  public TangibleAssetBatchModifyRequestDto locationId(UUID locationId) {
    this.locationId = locationId;
    return this;
  }

  /**
   * 지정 시에만 위치를 변경합니다.
   * @return locationId
  */
  @Valid 
  @ApiModelProperty(value = "지정 시에만 위치를 변경합니다.")
  @JsonProperty("locationId")
  public UUID getLocationId() {
    return locationId;
  }

  public void setLocationId(UUID locationId) {
    this.locationId = locationId;
  }

  public TangibleAssetBatchModifyRequestDto lifeStatus(LifeStatusEnum lifeStatus) {
    this.lifeStatus = lifeStatus;
    return this;
  }

  /**
   * 지정 시에만 생애 상태를 변경합니다.
   * @return lifeStatus
  */
  
  @ApiModelProperty(value = "지정 시에만 생애 상태를 변경합니다.")
  @JsonProperty("lifeStatus")
  public LifeStatusEnum getLifeStatus() {
    return lifeStatus;
  }

  public void setLifeStatus(LifeStatusEnum lifeStatus) {
    this.lifeStatus = lifeStatus;
  }

  public TangibleAssetBatchModifyRequestDto assignType(AssignTypeEnum assignType) {
    this.assignType = assignType;
    return this;
  }

  /**
   * 지정 시에만 배정 형태를 변경합니다.
   * @return assignType
  */
  
  @ApiModelProperty(value = "지정 시에만 배정 형태를 변경합니다.")
  @JsonProperty("assignType")
  public AssignTypeEnum getAssignType() {
    return assignType;
  }

  public void setAssignType(AssignTypeEnum assignType) {
    this.assignType = assignType;
  }

  public TangibleAssetBatchModifyRequestDto currentMemberId(UUID currentMemberId) {
    this.currentMemberId = currentMemberId;
    return this;
  }

  /**
   * 배정 형태가 개인배정(PERSONAL)/대여중(ON_LOAN)으로 바뀌면 필수, 그 외에는 무시되고 null로 저장됩니다.
   * @return currentMemberId
  */
  @Valid 
  @ApiModelProperty(value = "배정 형태가 개인배정(PERSONAL)/대여중(ON_LOAN)으로 바뀌면 필수, 그 외에는 무시되고 null로 저장됩니다.")
  @JsonProperty("currentMemberId")
  public UUID getCurrentMemberId() {
    return currentMemberId;
  }

  public void setCurrentMemberId(UUID currentMemberId) {
    this.currentMemberId = currentMemberId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TangibleAssetBatchModifyRequestDto tangibleAssetBatchModifyRequestDto = (TangibleAssetBatchModifyRequestDto) o;
    return Objects.equals(this.tangibleAssetIds, tangibleAssetBatchModifyRequestDto.tangibleAssetIds) &&
        Objects.equals(this.categoryId, tangibleAssetBatchModifyRequestDto.categoryId) &&
        Objects.equals(this.locationId, tangibleAssetBatchModifyRequestDto.locationId) &&
        Objects.equals(this.lifeStatus, tangibleAssetBatchModifyRequestDto.lifeStatus) &&
        Objects.equals(this.assignType, tangibleAssetBatchModifyRequestDto.assignType) &&
        Objects.equals(this.currentMemberId, tangibleAssetBatchModifyRequestDto.currentMemberId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tangibleAssetIds, categoryId, locationId, lifeStatus, assignType, currentMemberId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TangibleAssetBatchModifyRequestDto {\n");
    sb.append("    tangibleAssetIds: ").append(toIndentedString(tangibleAssetIds)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    lifeStatus: ").append(toIndentedString(lifeStatus)).append("\n");
    sb.append("    assignType: ").append(toIndentedString(assignType)).append("\n");
    sb.append("    currentMemberId: ").append(toIndentedString(currentMemberId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
