/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TangibleAssetModifyRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TangibleAssetModifyRequestDto {

  private String assetName;

  private UUID categoryId;

  private UUID locationId;

  /**
   * Gets or Sets lifeStatus
   */
  public enum LifeStatusEnum {
    USE("USE"),
    
    STORAGE("STORAGE"),
    
    REPAIR("REPAIR"),
    
    DISUSE("DISUSE"),
    
    DISPOSED("DISPOSED");

    private String value;

    LifeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LifeStatusEnum fromValue(String value) {
      for (LifeStatusEnum b : LifeStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private LifeStatusEnum lifeStatus;

  /**
   * Gets or Sets assignType
   */
  public enum AssignTypeEnum {
    UNASSIGNED("UNASSIGNED"),
    
    PERSONAL("PERSONAL"),
    
    SHARED("SHARED"),
    
    LOANABLE("LOANABLE"),
    
    ON_LOAN("ON_LOAN");

    private String value;

    AssignTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AssignTypeEnum fromValue(String value) {
      for (AssignTypeEnum b : AssignTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private AssignTypeEnum assignType;

  private OffsetDateTime acquisitionDate;

  private BigDecimal acquisitionAmount;

  private String modelName;

  private String manufacturer;

  private String serialNo;

  private UUID currentMemberId;

  private String memo;


  public TangibleAssetModifyRequestDto assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

  /**
   * Get assetName
   * @return assetName
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("assetName")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public TangibleAssetModifyRequestDto categoryId(UUID categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Get categoryId
   * @return categoryId
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("categoryId")
  public UUID getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(UUID categoryId) {
    this.categoryId = categoryId;
  }

  public TangibleAssetModifyRequestDto locationId(UUID locationId) {
    this.locationId = locationId;
    return this;
  }

  /**
   * Get locationId
   * @return locationId
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("locationId")
  public UUID getLocationId() {
    return locationId;
  }

  public void setLocationId(UUID locationId) {
    this.locationId = locationId;
  }

  public TangibleAssetModifyRequestDto lifeStatus(LifeStatusEnum lifeStatus) {
    this.lifeStatus = lifeStatus;
    return this;
  }

  /**
   * Get lifeStatus
   * @return lifeStatus
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("lifeStatus")
  public LifeStatusEnum getLifeStatus() {
    return lifeStatus;
  }

  public void setLifeStatus(LifeStatusEnum lifeStatus) {
    this.lifeStatus = lifeStatus;
  }

  public TangibleAssetModifyRequestDto assignType(AssignTypeEnum assignType) {
    this.assignType = assignType;
    return this;
  }

  /**
   * Get assignType
   * @return assignType
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("assignType")
  public AssignTypeEnum getAssignType() {
    return assignType;
  }

  public void setAssignType(AssignTypeEnum assignType) {
    this.assignType = assignType;
  }

  public TangibleAssetModifyRequestDto acquisitionDate(OffsetDateTime acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
    return this;
  }

  /**
   * Get acquisitionDate
   * @return acquisitionDate
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("acquisitionDate")
  public OffsetDateTime getAcquisitionDate() {
    return acquisitionDate;
  }

  public void setAcquisitionDate(OffsetDateTime acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
  }

  public TangibleAssetModifyRequestDto acquisitionAmount(BigDecimal acquisitionAmount) {
    this.acquisitionAmount = acquisitionAmount;
    return this;
  }

  /**
   * Get acquisitionAmount
   * @return acquisitionAmount
  */
  @NotNull @Valid 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("acquisitionAmount")
  public BigDecimal getAcquisitionAmount() {
    return acquisitionAmount;
  }

  public void setAcquisitionAmount(BigDecimal acquisitionAmount) {
    this.acquisitionAmount = acquisitionAmount;
  }

  public TangibleAssetModifyRequestDto modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("modelName")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public TangibleAssetModifyRequestDto manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Get manufacturer
   * @return manufacturer
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("manufacturer")
  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public TangibleAssetModifyRequestDto serialNo(String serialNo) {
    this.serialNo = serialNo;
    return this;
  }

  /**
   * Get serialNo
   * @return serialNo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("serialNo")
  public String getSerialNo() {
    return serialNo;
  }

  public void setSerialNo(String serialNo) {
    this.serialNo = serialNo;
  }

  public TangibleAssetModifyRequestDto currentMemberId(UUID currentMemberId) {
    this.currentMemberId = currentMemberId;
    return this;
  }

  /**
   * 배정 형태가 개인배정(PERSONAL)/대여중(ON_LOAN)이면 필수, 그 외에는 무시되고 null로 저장됩니다.
   * @return currentMemberId
  */
  @Valid 
  @ApiModelProperty(value = "배정 형태가 개인배정(PERSONAL)/대여중(ON_LOAN)이면 필수, 그 외에는 무시되고 null로 저장됩니다.")
  @JsonProperty("currentMemberId")
  public UUID getCurrentMemberId() {
    return currentMemberId;
  }

  public void setCurrentMemberId(UUID currentMemberId) {
    this.currentMemberId = currentMemberId;
  }

  public TangibleAssetModifyRequestDto memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * Get memo
   * @return memo
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("memo")
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TangibleAssetModifyRequestDto tangibleAssetModifyRequestDto = (TangibleAssetModifyRequestDto) o;
    return Objects.equals(this.assetName, tangibleAssetModifyRequestDto.assetName) &&
        Objects.equals(this.categoryId, tangibleAssetModifyRequestDto.categoryId) &&
        Objects.equals(this.locationId, tangibleAssetModifyRequestDto.locationId) &&
        Objects.equals(this.lifeStatus, tangibleAssetModifyRequestDto.lifeStatus) &&
        Objects.equals(this.assignType, tangibleAssetModifyRequestDto.assignType) &&
        Objects.equals(this.acquisitionDate, tangibleAssetModifyRequestDto.acquisitionDate) &&
        Objects.equals(this.acquisitionAmount, tangibleAssetModifyRequestDto.acquisitionAmount) &&
        Objects.equals(this.modelName, tangibleAssetModifyRequestDto.modelName) &&
        Objects.equals(this.manufacturer, tangibleAssetModifyRequestDto.manufacturer) &&
        Objects.equals(this.serialNo, tangibleAssetModifyRequestDto.serialNo) &&
        Objects.equals(this.currentMemberId, tangibleAssetModifyRequestDto.currentMemberId) &&
        Objects.equals(this.memo, tangibleAssetModifyRequestDto.memo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetName, categoryId, locationId, lifeStatus, assignType, acquisitionDate, acquisitionAmount, modelName, manufacturer, serialNo, currentMemberId, memo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TangibleAssetModifyRequestDto {\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    lifeStatus: ").append(toIndentedString(lifeStatus)).append("\n");
    sb.append("    assignType: ").append(toIndentedString(assignType)).append("\n");
    sb.append("    acquisitionDate: ").append(toIndentedString(acquisitionDate)).append("\n");
    sb.append("    acquisitionAmount: ").append(toIndentedString(acquisitionAmount)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    serialNo: ").append(toIndentedString(serialNo)).append("\n");
    sb.append("    currentMemberId: ").append(toIndentedString(currentMemberId)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
