/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TicketRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TicketRegisterRequestDto {

  /**
   * Gets or Sets ticketType
   */
  public enum TicketTypeEnum {
    PURCHASE("PURCHASE"),
    
    REPAIR("REPAIR"),
    
    REPLACE("REPLACE"),
    
    RETURN("RETURN"),
    
    EXTEND("EXTEND"),
    
    DISPOSAL("DISPOSAL");

    private String value;

    TicketTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TicketTypeEnum fromValue(String value) {
      for (TicketTypeEnum b : TicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private TicketTypeEnum ticketType;

  private String title;

  private String content;

  private UUID tangibleAssetId;


  public TicketRegisterRequestDto ticketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
    return this;
  }

  /**
   * Get ticketType
   * @return ticketType
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("ticketType")
  public TicketTypeEnum getTicketType() {
    return ticketType;
  }

  public void setTicketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
  }

  public TicketRegisterRequestDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TicketRegisterRequestDto content(String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("content")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TicketRegisterRequestDto tangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
    return this;
  }

  /**
   * Get tangibleAssetId
   * @return tangibleAssetId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("tangibleAssetId")
  public UUID getTangibleAssetId() {
    return tangibleAssetId;
  }

  public void setTangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketRegisterRequestDto ticketRegisterRequestDto = (TicketRegisterRequestDto) o;
    return Objects.equals(this.ticketType, ticketRegisterRequestDto.ticketType) &&
        Objects.equals(this.title, ticketRegisterRequestDto.title) &&
        Objects.equals(this.content, ticketRegisterRequestDto.content) &&
        Objects.equals(this.tangibleAssetId, ticketRegisterRequestDto.tangibleAssetId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketType, title, content, tangibleAssetId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketRegisterRequestDto {\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    tangibleAssetId: ").append(toIndentedString(tangibleAssetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
