/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TicketCommentResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TicketCommentResponseDto {

  private UUID ticketCommentId;

  private String content;

  private UUID writtenBy;

  private Boolean isRequester;

  private OffsetDateTime createAt;

  public TicketCommentResponseDto ticketCommentId(UUID ticketCommentId) {
    this.ticketCommentId = ticketCommentId;
    return this;
  }

  /**
   * Get ticketCommentId
   * @return ticketCommentId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("ticketCommentId")
  public UUID getTicketCommentId() {
    return ticketCommentId;
  }

  public void setTicketCommentId(UUID ticketCommentId) {
    this.ticketCommentId = ticketCommentId;
  }

  public TicketCommentResponseDto content(String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("content")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TicketCommentResponseDto writtenBy(UUID writtenBy) {
    this.writtenBy = writtenBy;
    return this;
  }

  /**
   * Get writtenBy
   * @return writtenBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("writtenBy")
  public UUID getWrittenBy() {
    return writtenBy;
  }

  public void setWrittenBy(UUID writtenBy) {
    this.writtenBy = writtenBy;
  }

  public TicketCommentResponseDto isRequester(Boolean isRequester) {
    this.isRequester = isRequester;
    return this;
  }

  /**
   * Get isRequester
   * @return isRequester
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("isRequester")
  public Boolean getIsRequester() {
    return isRequester;
  }

  public void setIsRequester(Boolean isRequester) {
    this.isRequester = isRequester;
  }

  public TicketCommentResponseDto createAt(OffsetDateTime createAt) {
    this.createAt = createAt;
    return this;
  }

  /**
   * Get createAt
   * @return createAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("createAt")
  public OffsetDateTime getCreateAt() {
    return createAt;
  }

  public void setCreateAt(OffsetDateTime createAt) {
    this.createAt = createAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketCommentResponseDto ticketCommentResponseDto = (TicketCommentResponseDto) o;
    return Objects.equals(this.ticketCommentId, ticketCommentResponseDto.ticketCommentId) &&
        Objects.equals(this.content, ticketCommentResponseDto.content) &&
        Objects.equals(this.writtenBy, ticketCommentResponseDto.writtenBy) &&
        Objects.equals(this.isRequester, ticketCommentResponseDto.isRequester) &&
        Objects.equals(this.createAt, ticketCommentResponseDto.createAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketCommentId, content, writtenBy, isRequester, createAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketCommentResponseDto {\n");
    sb.append("    ticketCommentId: ").append(toIndentedString(ticketCommentId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    writtenBy: ").append(toIndentedString(writtenBy)).append("\n");
    sb.append("    isRequester: ").append(toIndentedString(isRequester)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
