/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TicketCommentIdResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TicketCommentIdResponseDto {

  private UUID ticketCommentId;

  public TicketCommentIdResponseDto ticketCommentId(UUID ticketCommentId) {
    this.ticketCommentId = ticketCommentId;
    return this;
  }

  /**
   * Get ticketCommentId
   * @return ticketCommentId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("ticketCommentId")
  public UUID getTicketCommentId() {
    return ticketCommentId;
  }

  public void setTicketCommentId(UUID ticketCommentId) {
    this.ticketCommentId = ticketCommentId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketCommentIdResponseDto ticketCommentIdResponseDto = (TicketCommentIdResponseDto) o;
    return Objects.equals(this.ticketCommentId, ticketCommentIdResponseDto.ticketCommentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketCommentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketCommentIdResponseDto {\n");
    sb.append("    ticketCommentId: ").append(toIndentedString(ticketCommentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
