/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.smartAsset.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * TicketResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TicketResponseDto {

  private UUID ticketId;

  /**
   * Gets or Sets ticketType
   */
  public enum TicketTypeEnum {
    PURCHASE("PURCHASE"),
    
    REPAIR("REPAIR"),
    
    REPLACE("REPLACE"),
    
    RETURN("RETURN"),
    
    EXTEND("EXTEND"),
    
    DISPOSAL("DISPOSAL");

    private String value;

    TicketTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TicketTypeEnum fromValue(String value) {
      for (TicketTypeEnum b : TicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private TicketTypeEnum ticketType;

  private String title;

  private String content;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    WAITING("WAITING"),
    
    RECEIVED("RECEIVED"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    DONE("DONE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  private UUID requestedBy;

  private UUID assigneeId;

  private Boolean unassigned;

  private UUID tangibleAssetId;

  private String tangibleAssetCode;

  private String tangibleAssetName;

  private UUID licenseAssignedUserId;

  private UUID createdAssetId;

  private OffsetDateTime targetDueDate;

  private Boolean overdue;

  private OffsetDateTime completedAt;

  private OffsetDateTime createAt;

  public TicketResponseDto ticketId(UUID ticketId) {
    this.ticketId = ticketId;
    return this;
  }

  /**
   * Get ticketId
   * @return ticketId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("ticketId")
  public UUID getTicketId() {
    return ticketId;
  }

  public void setTicketId(UUID ticketId) {
    this.ticketId = ticketId;
  }

  public TicketResponseDto ticketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
    return this;
  }

  /**
   * Get ticketType
   * @return ticketType
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("ticketType")
  public TicketTypeEnum getTicketType() {
    return ticketType;
  }

  public void setTicketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
  }

  public TicketResponseDto title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TicketResponseDto content(String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("content")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TicketResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TicketResponseDto requestedBy(UUID requestedBy) {
    this.requestedBy = requestedBy;
    return this;
  }

  /**
   * Get requestedBy
   * @return requestedBy
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("requestedBy")
  public UUID getRequestedBy() {
    return requestedBy;
  }

  public void setRequestedBy(UUID requestedBy) {
    this.requestedBy = requestedBy;
  }

  public TicketResponseDto assigneeId(UUID assigneeId) {
    this.assigneeId = assigneeId;
    return this;
  }

  /**
   * Get assigneeId
   * @return assigneeId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("assigneeId")
  public UUID getAssigneeId() {
    return assigneeId;
  }

  public void setAssigneeId(UUID assigneeId) {
    this.assigneeId = assigneeId;
  }

  public TicketResponseDto unassigned(Boolean unassigned) {
    this.unassigned = unassigned;
    return this;
  }

  /**
   * 파생값 - assigneeId가 없으면 true(Q-50 미배정 경고)
   * @return unassigned
  */
  
  @ApiModelProperty(value = "파생값 - assigneeId가 없으면 true(Q-50 미배정 경고)")
  @JsonProperty("unassigned")
  public Boolean getUnassigned() {
    return unassigned;
  }

  public void setUnassigned(Boolean unassigned) {
    this.unassigned = unassigned;
  }

  public TicketResponseDto tangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
    return this;
  }

  /**
   * Get tangibleAssetId
   * @return tangibleAssetId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("tangibleAssetId")
  public UUID getTangibleAssetId() {
    return tangibleAssetId;
  }

  public void setTangibleAssetId(UUID tangibleAssetId) {
    this.tangibleAssetId = tangibleAssetId;
  }

  public TicketResponseDto tangibleAssetCode(String tangibleAssetCode) {
    this.tangibleAssetCode = tangibleAssetCode;
    return this;
  }

  /**
   * Get tangibleAssetCode
   * @return tangibleAssetCode
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("tangibleAssetCode")
  public String getTangibleAssetCode() {
    return tangibleAssetCode;
  }

  public void setTangibleAssetCode(String tangibleAssetCode) {
    this.tangibleAssetCode = tangibleAssetCode;
  }

  public TicketResponseDto tangibleAssetName(String tangibleAssetName) {
    this.tangibleAssetName = tangibleAssetName;
    return this;
  }

  /**
   * Get tangibleAssetName
   * @return tangibleAssetName
  */
  
  @ApiModelProperty(value = "")
  @JsonProperty("tangibleAssetName")
  public String getTangibleAssetName() {
    return tangibleAssetName;
  }

  public void setTangibleAssetName(String tangibleAssetName) {
    this.tangibleAssetName = tangibleAssetName;
  }

  public TicketResponseDto licenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
    return this;
  }

  /**
   * Get licenseAssignedUserId
   * @return licenseAssignedUserId
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("licenseAssignedUserId")
  public UUID getLicenseAssignedUserId() {
    return licenseAssignedUserId;
  }

  public void setLicenseAssignedUserId(UUID licenseAssignedUserId) {
    this.licenseAssignedUserId = licenseAssignedUserId;
  }

  public TicketResponseDto createdAssetId(UUID createdAssetId) {
    this.createdAssetId = createdAssetId;
    return this;
  }

  /**
   * PURCHASE 완료 시 자동등록된 자산(Q-49) - 다른 유형은 항상 null
   * @return createdAssetId
  */
  @Valid 
  @ApiModelProperty(value = "PURCHASE 완료 시 자동등록된 자산(Q-49) - 다른 유형은 항상 null")
  @JsonProperty("createdAssetId")
  public UUID getCreatedAssetId() {
    return createdAssetId;
  }

  public void setCreatedAssetId(UUID createdAssetId) {
    this.createdAssetId = createdAssetId;
  }

  public TicketResponseDto targetDueDate(OffsetDateTime targetDueDate) {
    this.targetDueDate = targetDueDate;
    return this;
  }

  /**
   * Get targetDueDate
   * @return targetDueDate
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("targetDueDate")
  public OffsetDateTime getTargetDueDate() {
    return targetDueDate;
  }

  public void setTargetDueDate(OffsetDateTime targetDueDate) {
    this.targetDueDate = targetDueDate;
  }

  public TicketResponseDto overdue(Boolean overdue) {
    this.overdue = overdue;
    return this;
  }

  /**
   * 파생값 - status가 DONE이 아니고 targetDueDate가 지났으면 true
   * @return overdue
  */
  
  @ApiModelProperty(value = "파생값 - status가 DONE이 아니고 targetDueDate가 지났으면 true")
  @JsonProperty("overdue")
  public Boolean getOverdue() {
    return overdue;
  }

  public void setOverdue(Boolean overdue) {
    this.overdue = overdue;
  }

  public TicketResponseDto completedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

  /**
   * Get completedAt
   * @return completedAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("completedAt")
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

  public TicketResponseDto createAt(OffsetDateTime createAt) {
    this.createAt = createAt;
    return this;
  }

  /**
   * Get createAt
   * @return createAt
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("createAt")
  public OffsetDateTime getCreateAt() {
    return createAt;
  }

  public void setCreateAt(OffsetDateTime createAt) {
    this.createAt = createAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketResponseDto ticketResponseDto = (TicketResponseDto) o;
    return Objects.equals(this.ticketId, ticketResponseDto.ticketId) &&
        Objects.equals(this.ticketType, ticketResponseDto.ticketType) &&
        Objects.equals(this.title, ticketResponseDto.title) &&
        Objects.equals(this.content, ticketResponseDto.content) &&
        Objects.equals(this.status, ticketResponseDto.status) &&
        Objects.equals(this.requestedBy, ticketResponseDto.requestedBy) &&
        Objects.equals(this.assigneeId, ticketResponseDto.assigneeId) &&
        Objects.equals(this.unassigned, ticketResponseDto.unassigned) &&
        Objects.equals(this.tangibleAssetId, ticketResponseDto.tangibleAssetId) &&
        Objects.equals(this.tangibleAssetCode, ticketResponseDto.tangibleAssetCode) &&
        Objects.equals(this.tangibleAssetName, ticketResponseDto.tangibleAssetName) &&
        Objects.equals(this.licenseAssignedUserId, ticketResponseDto.licenseAssignedUserId) &&
        Objects.equals(this.createdAssetId, ticketResponseDto.createdAssetId) &&
        Objects.equals(this.targetDueDate, ticketResponseDto.targetDueDate) &&
        Objects.equals(this.overdue, ticketResponseDto.overdue) &&
        Objects.equals(this.completedAt, ticketResponseDto.completedAt) &&
        Objects.equals(this.createAt, ticketResponseDto.createAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketId, ticketType, title, content, status, requestedBy, assigneeId, unassigned, tangibleAssetId, tangibleAssetCode, tangibleAssetName, licenseAssignedUserId, createdAssetId, targetDueDate, overdue, completedAt, createAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketResponseDto {\n");
    sb.append("    ticketId: ").append(toIndentedString(ticketId)).append("\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    requestedBy: ").append(toIndentedString(requestedBy)).append("\n");
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("    unassigned: ").append(toIndentedString(unassigned)).append("\n");
    sb.append("    tangibleAssetId: ").append(toIndentedString(tangibleAssetId)).append("\n");
    sb.append("    tangibleAssetCode: ").append(toIndentedString(tangibleAssetCode)).append("\n");
    sb.append("    tangibleAssetName: ").append(toIndentedString(tangibleAssetName)).append("\n");
    sb.append("    licenseAssignedUserId: ").append(toIndentedString(licenseAssignedUserId)).append("\n");
    sb.append("    createdAssetId: ").append(toIndentedString(createdAssetId)).append("\n");
    sb.append("    targetDueDate: ").append(toIndentedString(targetDueDate)).append("\n");
    sb.append("    overdue: ").append(toIndentedString(overdue)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
