/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.system.interfaces.inboundAdapter.spec.AuthorizationGroupUserStoreResponseDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AuthorizationGroupUserBatchStoreResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthorizationGroupUserBatchStoreResponseDto {

  @Valid
  private List<@Valid AuthorizationGroupUserStoreResponseDto> authorizationGroupUserIdList;

  public AuthorizationGroupUserBatchStoreResponseDto authorizationGroupUserIdList(List<@Valid AuthorizationGroupUserStoreResponseDto> authorizationGroupUserIdList) {
    this.authorizationGroupUserIdList = authorizationGroupUserIdList;
    return this;
  }

  public AuthorizationGroupUserBatchStoreResponseDto addAuthorizationGroupUserIdListItem(AuthorizationGroupUserStoreResponseDto authorizationGroupUserIdListItem) {
    if (this.authorizationGroupUserIdList == null) {
      this.authorizationGroupUserIdList = new ArrayList<>();
    }
    this.authorizationGroupUserIdList.add(authorizationGroupUserIdListItem);
    return this;
  }

  /**
   * Get authorizationGroupUserIdList
   * @return authorizationGroupUserIdList
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("authorizationGroupUserIdList")
  public List<@Valid AuthorizationGroupUserStoreResponseDto> getAuthorizationGroupUserIdList() {
    return authorizationGroupUserIdList;
  }

  public void setAuthorizationGroupUserIdList(List<@Valid AuthorizationGroupUserStoreResponseDto> authorizationGroupUserIdList) {
    this.authorizationGroupUserIdList = authorizationGroupUserIdList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationGroupUserBatchStoreResponseDto authorizationGroupUserBatchStoreResponseDto = (AuthorizationGroupUserBatchStoreResponseDto) o;
    return Objects.equals(this.authorizationGroupUserIdList, authorizationGroupUserBatchStoreResponseDto.authorizationGroupUserIdList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationGroupUserIdList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationGroupUserBatchStoreResponseDto {\n");
    sb.append("    authorizationGroupUserIdList: ").append(toIndentedString(authorizationGroupUserIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
