/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AuthorizationGroupUserResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthorizationGroupUserResponseDto {

  private UUID authorizationGroupUserId;

  private UUID authorizationGroupId;

  private UUID userId;

  public AuthorizationGroupUserResponseDto authorizationGroupUserId(UUID authorizationGroupUserId) {
    this.authorizationGroupUserId = authorizationGroupUserId;
    return this;
  }

  /**
   * 권한 그룹 사용자 ID
   * @return authorizationGroupUserId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "권한 그룹 사용자 ID")
  @JsonProperty("authorizationGroupUserId")
  public UUID getAuthorizationGroupUserId() {
    return authorizationGroupUserId;
  }

  public void setAuthorizationGroupUserId(UUID authorizationGroupUserId) {
    this.authorizationGroupUserId = authorizationGroupUserId;
  }

  public AuthorizationGroupUserResponseDto authorizationGroupId(UUID authorizationGroupId) {
    this.authorizationGroupId = authorizationGroupId;
    return this;
  }

  /**
   * 권한 그룹 ID
   * @return authorizationGroupId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "권한 그룹 ID")
  @JsonProperty("authorizationGroupId")
  public UUID getAuthorizationGroupId() {
    return authorizationGroupId;
  }

  public void setAuthorizationGroupId(UUID authorizationGroupId) {
    this.authorizationGroupId = authorizationGroupId;
  }

  public AuthorizationGroupUserResponseDto userId(UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * 사용자 ID
   * @return userId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "사용자 ID")
  @JsonProperty("userId")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationGroupUserResponseDto authorizationGroupUserResponseDto = (AuthorizationGroupUserResponseDto) o;
    return Objects.equals(this.authorizationGroupUserId, authorizationGroupUserResponseDto.authorizationGroupUserId) &&
        Objects.equals(this.authorizationGroupId, authorizationGroupUserResponseDto.authorizationGroupId) &&
        Objects.equals(this.userId, authorizationGroupUserResponseDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationGroupUserId, authorizationGroupId, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationGroupUserResponseDto {\n");
    sb.append("    authorizationGroupUserId: ").append(toIndentedString(authorizationGroupUserId)).append("\n");
    sb.append("    authorizationGroupId: ").append(toIndentedString(authorizationGroupId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
