/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AuthorizationGroupUserResponseRelAuthorizationGroupUserDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthorizationGroupUserResponseRelAuthorizationGroupUserDto {

  private UUID authorizationGroupUserId;

  private String authorizationGroupUserName;

  private String authorizationGroupUserCode;

  public AuthorizationGroupUserResponseRelAuthorizationGroupUserDto authorizationGroupUserId(UUID authorizationGroupUserId) {
    this.authorizationGroupUserId = authorizationGroupUserId;
    return this;
  }

  /**
   * 프로그램 ID
   * @return authorizationGroupUserId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "프로그램 ID")
  @JsonProperty("authorizationGroupUserId")
  public UUID getAuthorizationGroupUserId() {
    return authorizationGroupUserId;
  }

  public void setAuthorizationGroupUserId(UUID authorizationGroupUserId) {
    this.authorizationGroupUserId = authorizationGroupUserId;
  }

  public AuthorizationGroupUserResponseRelAuthorizationGroupUserDto authorizationGroupUserName(String authorizationGroupUserName) {
    this.authorizationGroupUserName = authorizationGroupUserName;
    return this;
  }

  /**
   * 프로그램 이름
   * @return authorizationGroupUserName
  */
  
  @ApiModelProperty(example = "사용자 관리", value = "프로그램 이름")
  @JsonProperty("authorizationGroupUserName")
  public String getAuthorizationGroupUserName() {
    return authorizationGroupUserName;
  }

  public void setAuthorizationGroupUserName(String authorizationGroupUserName) {
    this.authorizationGroupUserName = authorizationGroupUserName;
  }

  public AuthorizationGroupUserResponseRelAuthorizationGroupUserDto authorizationGroupUserCode(String authorizationGroupUserCode) {
    this.authorizationGroupUserCode = authorizationGroupUserCode;
    return this;
  }

  /**
   * 프로그램 코드
   * @return authorizationGroupUserCode
  */
  
  @ApiModelProperty(example = "ACTN_100", value = "프로그램 코드")
  @JsonProperty("authorizationGroupUserCode")
  public String getAuthorizationGroupUserCode() {
    return authorizationGroupUserCode;
  }

  public void setAuthorizationGroupUserCode(String authorizationGroupUserCode) {
    this.authorizationGroupUserCode = authorizationGroupUserCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationGroupUserResponseRelAuthorizationGroupUserDto authorizationGroupUserResponseRelAuthorizationGroupUserDto = (AuthorizationGroupUserResponseRelAuthorizationGroupUserDto) o;
    return Objects.equals(this.authorizationGroupUserId, authorizationGroupUserResponseRelAuthorizationGroupUserDto.authorizationGroupUserId) &&
        Objects.equals(this.authorizationGroupUserName, authorizationGroupUserResponseRelAuthorizationGroupUserDto.authorizationGroupUserName) &&
        Objects.equals(this.authorizationGroupUserCode, authorizationGroupUserResponseRelAuthorizationGroupUserDto.authorizationGroupUserCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationGroupUserId, authorizationGroupUserName, authorizationGroupUserCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationGroupUserResponseRelAuthorizationGroupUserDto {\n");
    sb.append("    authorizationGroupUserId: ").append(toIndentedString(authorizationGroupUserId)).append("\n");
    sb.append("    authorizationGroupUserName: ").append(toIndentedString(authorizationGroupUserName)).append("\n");
    sb.append("    authorizationGroupUserCode: ").append(toIndentedString(authorizationGroupUserCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
