/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.system.interfaces.inboundAdapter.spec.AuthorizationGroupUserBatchRegisterRequestItemDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * AuthorizationGroupUserBatchRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthorizationGroupUserBatchRegisterRequestDto {

  @Valid
  private List<@Valid AuthorizationGroupUserBatchRegisterRequestItemDto> authorizationGroupUserList;

  public AuthorizationGroupUserBatchRegisterRequestDto authorizationGroupUserList(List<@Valid AuthorizationGroupUserBatchRegisterRequestItemDto> authorizationGroupUserList) {
    this.authorizationGroupUserList = authorizationGroupUserList;
    return this;
  }

  public AuthorizationGroupUserBatchRegisterRequestDto addAuthorizationGroupUserListItem(AuthorizationGroupUserBatchRegisterRequestItemDto authorizationGroupUserListItem) {
    if (this.authorizationGroupUserList == null) {
      this.authorizationGroupUserList = new ArrayList<>();
    }
    this.authorizationGroupUserList.add(authorizationGroupUserListItem);
    return this;
  }

  /**
   * Get authorizationGroupUserList
   * @return authorizationGroupUserList
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("authorizationGroupUserList")
  public List<@Valid AuthorizationGroupUserBatchRegisterRequestItemDto> getAuthorizationGroupUserList() {
    return authorizationGroupUserList;
  }

  public void setAuthorizationGroupUserList(List<@Valid AuthorizationGroupUserBatchRegisterRequestItemDto> authorizationGroupUserList) {
    this.authorizationGroupUserList = authorizationGroupUserList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationGroupUserBatchRegisterRequestDto authorizationGroupUserBatchRegisterRequestDto = (AuthorizationGroupUserBatchRegisterRequestDto) o;
    return Objects.equals(this.authorizationGroupUserList, authorizationGroupUserBatchRegisterRequestDto.authorizationGroupUserList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationGroupUserList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationGroupUserBatchRegisterRequestDto {\n");
    sb.append("    authorizationGroupUserList: ").append(toIndentedString(authorizationGroupUserList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
