/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * CodeModifyRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CodeModifyRequestDto {

  private String codeName;

  private String codeDescription;

  private Integer codeOrderNo;

  /**
   * 공통코드 사용여부
   */
  public enum CodeUseStatusEnum {
    USED("USED"),
    
    UNUSED("UNUSED");

    private String value;

    CodeUseStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeUseStatusEnum fromValue(String value) {
      for (CodeUseStatusEnum b : CodeUseStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private CodeUseStatusEnum codeUseStatus;


  public CodeModifyRequestDto codeName(String codeName) {
    this.codeName = codeName;
    return this;
  }

  /**
   * 공통코드 이름
   * @return codeName
  */
  @NotNull 
  @ApiModelProperty(example = "재난유형", required = true, value = "공통코드 이름")
  @JsonProperty("codeName")
  public String getCodeName() {
    return codeName;
  }

  public void setCodeName(String codeName) {
    this.codeName = codeName;
  }

  public CodeModifyRequestDto codeDescription(String codeDescription) {
    this.codeDescription = codeDescription;
    return this;
  }

  /**
   * 공통코드 설명
   * @return codeDescription
  */
  
  @ApiModelProperty(example = "재난유형을 표현하는 공통코드입니다.", value = "공통코드 설명")
  @JsonProperty("codeDescription")
  public String getCodeDescription() {
    return codeDescription;
  }

  public void setCodeDescription(String codeDescription) {
    this.codeDescription = codeDescription;
  }

  public CodeModifyRequestDto codeOrderNo(Integer codeOrderNo) {
    this.codeOrderNo = codeOrderNo;
    return this;
  }

  /**
   * 공통코드 순서
   * @return codeOrderNo
  */
  @NotNull 
  @ApiModelProperty(example = "99", required = true, value = "공통코드 순서")
  @JsonProperty("codeOrderNo")
  public Integer getCodeOrderNo() {
    return codeOrderNo;
  }

  public void setCodeOrderNo(Integer codeOrderNo) {
    this.codeOrderNo = codeOrderNo;
  }

  public CodeModifyRequestDto codeUseStatus(CodeUseStatusEnum codeUseStatus) {
    this.codeUseStatus = codeUseStatus;
    return this;
  }

  /**
   * 공통코드 사용여부
   * @return codeUseStatus
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "공통코드 사용여부")
  @JsonProperty("codeUseStatus")
  public CodeUseStatusEnum getCodeUseStatus() {
    return codeUseStatus;
  }

  public void setCodeUseStatus(CodeUseStatusEnum codeUseStatus) {
    this.codeUseStatus = codeUseStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeModifyRequestDto codeModifyRequestDto = (CodeModifyRequestDto) o;
    return Objects.equals(this.codeName, codeModifyRequestDto.codeName) &&
        Objects.equals(this.codeDescription, codeModifyRequestDto.codeDescription) &&
        Objects.equals(this.codeOrderNo, codeModifyRequestDto.codeOrderNo) &&
        Objects.equals(this.codeUseStatus, codeModifyRequestDto.codeUseStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeName, codeDescription, codeOrderNo, codeUseStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeModifyRequestDto {\n");
    sb.append("    codeName: ").append(toIndentedString(codeName)).append("\n");
    sb.append("    codeDescription: ").append(toIndentedString(codeDescription)).append("\n");
    sb.append("    codeOrderNo: ").append(toIndentedString(codeOrderNo)).append("\n");
    sb.append("    codeUseStatus: ").append(toIndentedString(codeUseStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
