/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.system.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.system.interfaces.inboundAdapter.spec.CodeIdResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.CodeModifyRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.CodeRegisterRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.CodeResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "Code", value = "Code", description = "공통코드를 관리하는 API Controller")
@RequestMapping("/api/v1/system")
public interface CodeApi {

    /**
     * PATCH /code/{codeId} : 공통코드 수정
     * 단일 공통코드를 수정합니다.
     *
     * @param codeId 공통코드 ID (required)
     * @param codeModifyRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Code" },
        value = "공통코드 수정",
        nickname = "modifyCode",
        notes = "단일 공통코드를 수정합니다.",
        response = CodeIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = CodeIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/code/{codeId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<CodeIdResponseDto> modifyCode(
        @ApiParam(value = "공통코드 ID", required = true) @PathVariable("codeId") UUID codeId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) CodeModifyRequestDto codeModifyRequestDto
    );


    /**
     * POST /code : 공통코드 등록
     * 단일 공통코드를 등록합니다.
     *
     * @param codeRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Code" },
        value = "공통코드 등록",
        nickname = "registerCode",
        notes = "단일 공통코드를 등록합니다.",
        response = CodeIdResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = CodeIdResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/code",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<CodeIdResponseDto> registerCode(
        @ApiParam(value = "") @Valid @RequestBody(required = false) CodeRegisterRequestDto codeRegisterRequestDto
    );


    /**
     * DELETE /code/{codeId} : 공통코드 삭제
     * 공통코드를 삭제합니다. (soft delete)
     *
     * @param codeId 공통코드 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Code" },
        value = "공통코드 삭제",
        nickname = "removeCode",
        notes = "공통코드를 삭제합니다. (soft delete)",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/code/{codeId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removeCode(
        @ApiParam(value = "공통코드 ID", required = true) @PathVariable("codeId") UUID codeId
    );


    /**
     * GET /code : 공통코드 목록 조회
     * 공통코드 목록을 조회합니다.
     *
     * @param upperCodeId  (optional)
     * @param keyword  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Code" },
        value = "공통코드 목록 조회",
        nickname = "searchAllCode",
        notes = "공통코드 목록을 조회합니다.",
        response = CodeResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = CodeResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/code",
        produces = { "application/json" }
    )
    CommonResponse<List<CodeResponseDto>> searchAllCode(
        @ApiParam(value = "") @Valid @RequestParam(value = "upperCodeId", required = false) UUID upperCodeId,
        @ApiParam(value = "") @Valid @RequestParam(value = "keyword", required = false) String keyword
    );


    /**
     * GET /code/{codeId} : 공통코드 상세 조회
     * 공통코드의 상세정보를 조회합니다.
     *
     * @param codeId 공통코드 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Code" },
        value = "공통코드 상세 조회",
        nickname = "searchCode",
        notes = "공통코드의 상세정보를 조회합니다.",
        response = CodeResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = CodeResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/code/{codeId}",
        produces = { "application/json" }
    )
    CommonResponse<CodeResponseDto> searchCode(
        @ApiParam(value = "공통코드 ID", required = true) @PathVariable("codeId") UUID codeId
    );

}
