/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * CodeRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CodeRegisterRequestDto {

  private UUID upperCodeId;

  private String code;

  private String codeName;

  private String codeDescription;

  private Integer codeDepthNo;

  private Integer codeOrderNo;

  /**
   * 공통코드 사용여부
   */
  public enum CodeUseStatusEnum {
    USED("USED"),
    
    UNUSED("UNUSED");

    private String value;

    CodeUseStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeUseStatusEnum fromValue(String value) {
      for (CodeUseStatusEnum b : CodeUseStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private CodeUseStatusEnum codeUseStatus;


  public CodeRegisterRequestDto upperCodeId(UUID upperCodeId) {
    this.upperCodeId = upperCodeId;
    return this;
  }

  /**
   * 상위 코드 ID
   * @return upperCodeId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "상위 코드 ID")
  @JsonProperty("upperCodeId")
  public UUID getUpperCodeId() {
    return upperCodeId;
  }

  public void setUpperCodeId(UUID upperCodeId) {
    this.upperCodeId = upperCodeId;
  }

  public CodeRegisterRequestDto code(String code) {
    this.code = code;
    return this;
  }

  /**
   * 공통코드
   * @return code
  */
  @NotNull 
  @ApiModelProperty(example = "001", required = true, value = "공통코드")
  @JsonProperty("code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CodeRegisterRequestDto codeName(String codeName) {
    this.codeName = codeName;
    return this;
  }

  /**
   * 공통코드 이름
   * @return codeName
  */
  @NotNull 
  @ApiModelProperty(example = "재난유형", required = true, value = "공통코드 이름")
  @JsonProperty("codeName")
  public String getCodeName() {
    return codeName;
  }

  public void setCodeName(String codeName) {
    this.codeName = codeName;
  }

  public CodeRegisterRequestDto codeDescription(String codeDescription) {
    this.codeDescription = codeDescription;
    return this;
  }

  /**
   * 공통코드 설명
   * @return codeDescription
  */
  
  @ApiModelProperty(example = "재난유형을 표현하는 공통코드입니다.", value = "공통코드 설명")
  @JsonProperty("codeDescription")
  public String getCodeDescription() {
    return codeDescription;
  }

  public void setCodeDescription(String codeDescription) {
    this.codeDescription = codeDescription;
  }

  public CodeRegisterRequestDto codeDepthNo(Integer codeDepthNo) {
    this.codeDepthNo = codeDepthNo;
    return this;
  }

  /**
   * 공통코드 레벨
   * @return codeDepthNo
  */
  @NotNull 
  @ApiModelProperty(example = "1", required = true, value = "공통코드 레벨")
  @JsonProperty("codeDepthNo")
  public Integer getCodeDepthNo() {
    return codeDepthNo;
  }

  public void setCodeDepthNo(Integer codeDepthNo) {
    this.codeDepthNo = codeDepthNo;
  }

  public CodeRegisterRequestDto codeOrderNo(Integer codeOrderNo) {
    this.codeOrderNo = codeOrderNo;
    return this;
  }

  /**
   * 공통코드 순서
   * @return codeOrderNo
  */
  @NotNull 
  @ApiModelProperty(example = "99", required = true, value = "공통코드 순서")
  @JsonProperty("codeOrderNo")
  public Integer getCodeOrderNo() {
    return codeOrderNo;
  }

  public void setCodeOrderNo(Integer codeOrderNo) {
    this.codeOrderNo = codeOrderNo;
  }

  public CodeRegisterRequestDto codeUseStatus(CodeUseStatusEnum codeUseStatus) {
    this.codeUseStatus = codeUseStatus;
    return this;
  }

  /**
   * 공통코드 사용여부
   * @return codeUseStatus
  */
  @NotNull 
  @ApiModelProperty(required = true, value = "공통코드 사용여부")
  @JsonProperty("codeUseStatus")
  public CodeUseStatusEnum getCodeUseStatus() {
    return codeUseStatus;
  }

  public void setCodeUseStatus(CodeUseStatusEnum codeUseStatus) {
    this.codeUseStatus = codeUseStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeRegisterRequestDto codeRegisterRequestDto = (CodeRegisterRequestDto) o;
    return Objects.equals(this.upperCodeId, codeRegisterRequestDto.upperCodeId) &&
        Objects.equals(this.code, codeRegisterRequestDto.code) &&
        Objects.equals(this.codeName, codeRegisterRequestDto.codeName) &&
        Objects.equals(this.codeDescription, codeRegisterRequestDto.codeDescription) &&
        Objects.equals(this.codeDepthNo, codeRegisterRequestDto.codeDepthNo) &&
        Objects.equals(this.codeOrderNo, codeRegisterRequestDto.codeOrderNo) &&
        Objects.equals(this.codeUseStatus, codeRegisterRequestDto.codeUseStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upperCodeId, code, codeName, codeDescription, codeDepthNo, codeOrderNo, codeUseStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeRegisterRequestDto {\n");
    sb.append("    upperCodeId: ").append(toIndentedString(upperCodeId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeName: ").append(toIndentedString(codeName)).append("\n");
    sb.append("    codeDescription: ").append(toIndentedString(codeDescription)).append("\n");
    sb.append("    codeDepthNo: ").append(toIndentedString(codeDepthNo)).append("\n");
    sb.append("    codeOrderNo: ").append(toIndentedString(codeOrderNo)).append("\n");
    sb.append("    codeUseStatus: ").append(toIndentedString(codeUseStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
