/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * MenuOrderModifyRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MenuOrderModifyRequestDto {

  private UUID menuId;

  private UUID parentMenuId;

  public MenuOrderModifyRequestDto menuId(UUID menuId) {
    this.menuId = menuId;
    return this;
  }

  /**
   * 메뉴 ID
   * @return menuId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "메뉴 ID")
  @JsonProperty("menuId")
  public UUID getMenuId() {
    return menuId;
  }

  public void setMenuId(UUID menuId) {
    this.menuId = menuId;
  }

  public MenuOrderModifyRequestDto parentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
    return this;
  }

  /**
   * 부모 메뉴 ID
   * @return parentMenuId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "부모 메뉴 ID")
  @JsonProperty("parentMenuId")
  public UUID getParentMenuId() {
    return parentMenuId;
  }

  public void setParentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuOrderModifyRequestDto menuOrderModifyRequestDto = (MenuOrderModifyRequestDto) o;
    return Objects.equals(this.menuId, menuOrderModifyRequestDto.menuId) &&
        Objects.equals(this.parentMenuId, menuOrderModifyRequestDto.parentMenuId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(menuId, parentMenuId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuOrderModifyRequestDto {\n");
    sb.append("    menuId: ").append(toIndentedString(menuId)).append("\n");
    sb.append("    parentMenuId: ").append(toIndentedString(parentMenuId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
