/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.system.interfaces.inboundAdapter.spec.MenuPermissionStoreResponseDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * MenuPermissionBatchStoreResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MenuPermissionBatchStoreResponseDto {

  @Valid
  private List<@Valid MenuPermissionStoreResponseDto> menuPermissionIdList;

  public MenuPermissionBatchStoreResponseDto menuPermissionIdList(List<@Valid MenuPermissionStoreResponseDto> menuPermissionIdList) {
    this.menuPermissionIdList = menuPermissionIdList;
    return this;
  }

  public MenuPermissionBatchStoreResponseDto addMenuPermissionIdListItem(MenuPermissionStoreResponseDto menuPermissionIdListItem) {
    if (this.menuPermissionIdList == null) {
      this.menuPermissionIdList = new ArrayList<>();
    }
    this.menuPermissionIdList.add(menuPermissionIdListItem);
    return this;
  }

  /**
   * Get menuPermissionIdList
   * @return menuPermissionIdList
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("menuPermissionIdList")
  public List<@Valid MenuPermissionStoreResponseDto> getMenuPermissionIdList() {
    return menuPermissionIdList;
  }

  public void setMenuPermissionIdList(List<@Valid MenuPermissionStoreResponseDto> menuPermissionIdList) {
    this.menuPermissionIdList = menuPermissionIdList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuPermissionBatchStoreResponseDto menuPermissionBatchStoreResponseDto = (MenuPermissionBatchStoreResponseDto) o;
    return Objects.equals(this.menuPermissionIdList, menuPermissionBatchStoreResponseDto.menuPermissionIdList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(menuPermissionIdList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuPermissionBatchStoreResponseDto {\n");
    sb.append("    menuPermissionIdList: ").append(toIndentedString(menuPermissionIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
