/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * MenuRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MenuRegisterRequestDto {

  private String menuName;

  private String menuCode;

  private String menuMapping;

  /**
   * 메뉴 사용 여부
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  /**
   * 메뉴 여부
   */
  public enum MenuStatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    MenuStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MenuStatusEnum fromValue(String value) {
      for (MenuStatusEnum b : MenuStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MenuStatusEnum menuStatus;

  /**
   * 메뉴 타입
   */
  public enum MenuTypeEnum {
    MENU("MENU"),
    
    PROGRAM("PROGRAM"),
    
    URL("URL");

    private String value;

    MenuTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MenuTypeEnum fromValue(String value) {
      for (MenuTypeEnum b : MenuTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MenuTypeEnum menuType;

  private Integer sortSeq;

  private UUID parentMenuId;

  private UUID programId;

  public MenuRegisterRequestDto menuName(String menuName) {
    this.menuName = menuName;
    return this;
  }

  /**
   * 메뉴 이름
   * @return menuName
  */
  
  @ApiModelProperty(example = "사용자 관리", value = "메뉴 이름")
  @JsonProperty("menuName")
  public String getMenuName() {
    return menuName;
  }

  public void setMenuName(String menuName) {
    this.menuName = menuName;
  }

  public MenuRegisterRequestDto menuCode(String menuCode) {
    this.menuCode = menuCode;
    return this;
  }

  /**
   * 메뉴 코드
   * @return menuCode
  */
  
  @ApiModelProperty(example = "ACTN_100", value = "메뉴 코드")
  @JsonProperty("menuCode")
  public String getMenuCode() {
    return menuCode;
  }

  public void setMenuCode(String menuCode) {
    this.menuCode = menuCode;
  }

  public MenuRegisterRequestDto menuMapping(String menuMapping) {
    this.menuMapping = menuMapping;
    return this;
  }

  /**
   * 메뉴 매핑주소
   * @return menuMapping
  */
  
  @ApiModelProperty(example = "AdminMain", value = "메뉴 매핑주소")
  @JsonProperty("menuMapping")
  public String getMenuMapping() {
    return menuMapping;
  }

  public void setMenuMapping(String menuMapping) {
    this.menuMapping = menuMapping;
  }

  public MenuRegisterRequestDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * 메뉴 사용 여부
   * @return status
  */
  
  @ApiModelProperty(value = "메뉴 사용 여부")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public MenuRegisterRequestDto menuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
    return this;
  }

  /**
   * 메뉴 여부
   * @return menuStatus
  */
  
  @ApiModelProperty(value = "메뉴 여부")
  @JsonProperty("menuStatus")
  public MenuStatusEnum getMenuStatus() {
    return menuStatus;
  }

  public void setMenuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
  }

  public MenuRegisterRequestDto menuType(MenuTypeEnum menuType) {
    this.menuType = menuType;
    return this;
  }

  /**
   * 메뉴 타입
   * @return menuType
  */
  
  @ApiModelProperty(value = "메뉴 타입")
  @JsonProperty("menuType")
  public MenuTypeEnum getMenuType() {
    return menuType;
  }

  public void setMenuType(MenuTypeEnum menuType) {
    this.menuType = menuType;
  }

  public MenuRegisterRequestDto sortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
    return this;
  }

  /**
   * 정렬 순서
   * @return sortSeq
  */
  
  @ApiModelProperty(example = "1", value = "정렬 순서")
  @JsonProperty("sortSeq")
  public Integer getSortSeq() {
    return sortSeq;
  }

  public void setSortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
  }

  public MenuRegisterRequestDto parentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
    return this;
  }

  /**
   * 부모 메뉴 ID
   * @return parentMenuId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "부모 메뉴 ID")
  @JsonProperty("parentMenuId")
  public UUID getParentMenuId() {
    return parentMenuId;
  }

  public void setParentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
  }

  public MenuRegisterRequestDto programId(UUID programId) {
    this.programId = programId;
    return this;
  }

  /**
   * 프로그램 ID
   * @return programId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "프로그램 ID")
  @JsonProperty("programId")
  public UUID getProgramId() {
    return programId;
  }

  public void setProgramId(UUID programId) {
    this.programId = programId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuRegisterRequestDto menuRegisterRequestDto = (MenuRegisterRequestDto) o;
    return Objects.equals(this.menuName, menuRegisterRequestDto.menuName) &&
        Objects.equals(this.menuCode, menuRegisterRequestDto.menuCode) &&
        Objects.equals(this.menuMapping, menuRegisterRequestDto.menuMapping) &&
        Objects.equals(this.status, menuRegisterRequestDto.status) &&
        Objects.equals(this.menuStatus, menuRegisterRequestDto.menuStatus) &&
        Objects.equals(this.menuType, menuRegisterRequestDto.menuType) &&
        Objects.equals(this.sortSeq, menuRegisterRequestDto.sortSeq) &&
        Objects.equals(this.parentMenuId, menuRegisterRequestDto.parentMenuId) &&
        Objects.equals(this.programId, menuRegisterRequestDto.programId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(menuName, menuCode, menuMapping, status, menuStatus, menuType, sortSeq, parentMenuId, programId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuRegisterRequestDto {\n");
    sb.append("    menuName: ").append(toIndentedString(menuName)).append("\n");
    sb.append("    menuCode: ").append(toIndentedString(menuCode)).append("\n");
    sb.append("    menuMapping: ").append(toIndentedString(menuMapping)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    menuStatus: ").append(toIndentedString(menuStatus)).append("\n");
    sb.append("    menuType: ").append(toIndentedString(menuType)).append("\n");
    sb.append("    sortSeq: ").append(toIndentedString(sortSeq)).append("\n");
    sb.append("    parentMenuId: ").append(toIndentedString(parentMenuId)).append("\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
