/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * MenuPermissionDetailResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MenuPermissionDetailResponseDto {

  private UUID menuPermissionId;

  private UUID menuId;

  private String menuName;

  private String menuCode;

  private String menuMapping;

  /**
   * 메뉴 사용 여부
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  /**
   * 메뉴 여부
   */
  public enum MenuStatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    MenuStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MenuStatusEnum fromValue(String value) {
      for (MenuStatusEnum b : MenuStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MenuStatusEnum menuStatus;

  /**
   * 메뉴 타입
   */
  public enum MenuTypeEnum {
    MENU("MENU"),
    
    PROGRAM("PROGRAM"),
    
    URL("URL");

    private String value;

    MenuTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MenuTypeEnum fromValue(String value) {
      for (MenuTypeEnum b : MenuTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MenuTypeEnum menuType;

  private Integer sortSeq;

  private UUID parentMenuId;

  private UUID programId;

  /**
   * 조회 권한 상태
   */
  public enum SelectStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    SelectStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SelectStatusEnum fromValue(String value) {
      for (SelectStatusEnum b : SelectStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private SelectStatusEnum selectStatus;

  /**
   * 추가 권한 상태
   */
  public enum InsertStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    InsertStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InsertStatusEnum fromValue(String value) {
      for (InsertStatusEnum b : InsertStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private InsertStatusEnum insertStatus;

  /**
   * 수정 권한 상태
   */
  public enum UpdateStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    UpdateStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UpdateStatusEnum fromValue(String value) {
      for (UpdateStatusEnum b : UpdateStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private UpdateStatusEnum updateStatus;

  /**
   * 삭제 권한 상태
   */
  public enum DeleteStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    DeleteStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeleteStatusEnum fromValue(String value) {
      for (DeleteStatusEnum b : DeleteStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private DeleteStatusEnum deleteStatus;

  /**
   * 인쇄 권한 상태
   */
  public enum PrintStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    PrintStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PrintStatusEnum fromValue(String value) {
      for (PrintStatusEnum b : PrintStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private PrintStatusEnum printStatus;

  /**
   * 다운로드 권한 상태
   */
  public enum DownStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    DownStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DownStatusEnum fromValue(String value) {
      for (DownStatusEnum b : DownStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private DownStatusEnum downStatus;

  /**
   * 관리 권한 상태
   */
  public enum ManageStatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    ManageStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ManageStatusEnum fromValue(String value) {
      for (ManageStatusEnum b : ManageStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ManageStatusEnum manageStatus;

  /**
   * 기타 권한1 상태
   */
  public enum Custom1StatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    Custom1StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static Custom1StatusEnum fromValue(String value) {
      for (Custom1StatusEnum b : Custom1StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private Custom1StatusEnum custom1Status;

  /**
   * 기타 권한2 상태
   */
  public enum Custom2StatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    Custom2StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static Custom2StatusEnum fromValue(String value) {
      for (Custom2StatusEnum b : Custom2StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private Custom2StatusEnum custom2Status;

  /**
   * 기타 권한3 상태
   */
  public enum Custom3StatusEnum {
    ALLOW("ALLOW"),
    
    NONE("NONE");

    private String value;

    Custom3StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static Custom3StatusEnum fromValue(String value) {
      for (Custom3StatusEnum b : Custom3StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private Custom3StatusEnum custom3Status;

  public MenuPermissionDetailResponseDto menuPermissionId(UUID menuPermissionId) {
    this.menuPermissionId = menuPermissionId;
    return this;
  }

  /**
   * 메뉴 권한 ID
   * @return menuPermissionId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "메뉴 권한 ID")
  @JsonProperty("menuPermissionId")
  public UUID getMenuPermissionId() {
    return menuPermissionId;
  }

  public void setMenuPermissionId(UUID menuPermissionId) {
    this.menuPermissionId = menuPermissionId;
  }

  public MenuPermissionDetailResponseDto menuId(UUID menuId) {
    this.menuId = menuId;
    return this;
  }

  /**
   * 메뉴 ID
   * @return menuId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "메뉴 ID")
  @JsonProperty("menuId")
  public UUID getMenuId() {
    return menuId;
  }

  public void setMenuId(UUID menuId) {
    this.menuId = menuId;
  }

  public MenuPermissionDetailResponseDto menuName(String menuName) {
    this.menuName = menuName;
    return this;
  }

  /**
   * 메뉴 이름
   * @return menuName
  */
  
  @ApiModelProperty(example = "사용자 관리", value = "메뉴 이름")
  @JsonProperty("menuName")
  public String getMenuName() {
    return menuName;
  }

  public void setMenuName(String menuName) {
    this.menuName = menuName;
  }

  public MenuPermissionDetailResponseDto menuCode(String menuCode) {
    this.menuCode = menuCode;
    return this;
  }

  /**
   * 메뉴 코드
   * @return menuCode
  */
  
  @ApiModelProperty(example = "ACTN_100", value = "메뉴 코드")
  @JsonProperty("menuCode")
  public String getMenuCode() {
    return menuCode;
  }

  public void setMenuCode(String menuCode) {
    this.menuCode = menuCode;
  }

  public MenuPermissionDetailResponseDto menuMapping(String menuMapping) {
    this.menuMapping = menuMapping;
    return this;
  }

  /**
   * 메뉴 매핑주소
   * @return menuMapping
  */
  
  @ApiModelProperty(example = "AdminMain", value = "메뉴 매핑주소")
  @JsonProperty("menuMapping")
  public String getMenuMapping() {
    return menuMapping;
  }

  public void setMenuMapping(String menuMapping) {
    this.menuMapping = menuMapping;
  }

  public MenuPermissionDetailResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * 메뉴 사용 여부
   * @return status
  */
  
  @ApiModelProperty(value = "메뉴 사용 여부")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public MenuPermissionDetailResponseDto menuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
    return this;
  }

  /**
   * 메뉴 여부
   * @return menuStatus
  */
  
  @ApiModelProperty(value = "메뉴 여부")
  @JsonProperty("menuStatus")
  public MenuStatusEnum getMenuStatus() {
    return menuStatus;
  }

  public void setMenuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
  }

  public MenuPermissionDetailResponseDto menuType(MenuTypeEnum menuType) {
    this.menuType = menuType;
    return this;
  }

  /**
   * 메뉴 타입
   * @return menuType
  */
  
  @ApiModelProperty(value = "메뉴 타입")
  @JsonProperty("menuType")
  public MenuTypeEnum getMenuType() {
    return menuType;
  }

  public void setMenuType(MenuTypeEnum menuType) {
    this.menuType = menuType;
  }

  public MenuPermissionDetailResponseDto sortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
    return this;
  }

  /**
   * 정렬 순서
   * @return sortSeq
  */
  
  @ApiModelProperty(example = "1", value = "정렬 순서")
  @JsonProperty("sortSeq")
  public Integer getSortSeq() {
    return sortSeq;
  }

  public void setSortSeq(Integer sortSeq) {
    this.sortSeq = sortSeq;
  }

  public MenuPermissionDetailResponseDto parentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
    return this;
  }

  /**
   * 부모 메뉴 ID
   * @return parentMenuId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "부모 메뉴 ID")
  @JsonProperty("parentMenuId")
  public UUID getParentMenuId() {
    return parentMenuId;
  }

  public void setParentMenuId(UUID parentMenuId) {
    this.parentMenuId = parentMenuId;
  }

  public MenuPermissionDetailResponseDto programId(UUID programId) {
    this.programId = programId;
    return this;
  }

  /**
   * 프로그램 ID
   * @return programId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "프로그램 ID")
  @JsonProperty("programId")
  public UUID getProgramId() {
    return programId;
  }

  public void setProgramId(UUID programId) {
    this.programId = programId;
  }

  public MenuPermissionDetailResponseDto selectStatus(SelectStatusEnum selectStatus) {
    this.selectStatus = selectStatus;
    return this;
  }

  /**
   * 조회 권한 상태
   * @return selectStatus
  */
  
  @ApiModelProperty(value = "조회 권한 상태")
  @JsonProperty("selectStatus")
  public SelectStatusEnum getSelectStatus() {
    return selectStatus;
  }

  public void setSelectStatus(SelectStatusEnum selectStatus) {
    this.selectStatus = selectStatus;
  }

  public MenuPermissionDetailResponseDto insertStatus(InsertStatusEnum insertStatus) {
    this.insertStatus = insertStatus;
    return this;
  }

  /**
   * 추가 권한 상태
   * @return insertStatus
  */
  
  @ApiModelProperty(value = "추가 권한 상태")
  @JsonProperty("insertStatus")
  public InsertStatusEnum getInsertStatus() {
    return insertStatus;
  }

  public void setInsertStatus(InsertStatusEnum insertStatus) {
    this.insertStatus = insertStatus;
  }

  public MenuPermissionDetailResponseDto updateStatus(UpdateStatusEnum updateStatus) {
    this.updateStatus = updateStatus;
    return this;
  }

  /**
   * 수정 권한 상태
   * @return updateStatus
  */
  
  @ApiModelProperty(value = "수정 권한 상태")
  @JsonProperty("updateStatus")
  public UpdateStatusEnum getUpdateStatus() {
    return updateStatus;
  }

  public void setUpdateStatus(UpdateStatusEnum updateStatus) {
    this.updateStatus = updateStatus;
  }

  public MenuPermissionDetailResponseDto deleteStatus(DeleteStatusEnum deleteStatus) {
    this.deleteStatus = deleteStatus;
    return this;
  }

  /**
   * 삭제 권한 상태
   * @return deleteStatus
  */
  
  @ApiModelProperty(value = "삭제 권한 상태")
  @JsonProperty("deleteStatus")
  public DeleteStatusEnum getDeleteStatus() {
    return deleteStatus;
  }

  public void setDeleteStatus(DeleteStatusEnum deleteStatus) {
    this.deleteStatus = deleteStatus;
  }

  public MenuPermissionDetailResponseDto printStatus(PrintStatusEnum printStatus) {
    this.printStatus = printStatus;
    return this;
  }

  /**
   * 인쇄 권한 상태
   * @return printStatus
  */
  
  @ApiModelProperty(value = "인쇄 권한 상태")
  @JsonProperty("printStatus")
  public PrintStatusEnum getPrintStatus() {
    return printStatus;
  }

  public void setPrintStatus(PrintStatusEnum printStatus) {
    this.printStatus = printStatus;
  }

  public MenuPermissionDetailResponseDto downStatus(DownStatusEnum downStatus) {
    this.downStatus = downStatus;
    return this;
  }

  /**
   * 다운로드 권한 상태
   * @return downStatus
  */
  
  @ApiModelProperty(value = "다운로드 권한 상태")
  @JsonProperty("downStatus")
  public DownStatusEnum getDownStatus() {
    return downStatus;
  }

  public void setDownStatus(DownStatusEnum downStatus) {
    this.downStatus = downStatus;
  }

  public MenuPermissionDetailResponseDto manageStatus(ManageStatusEnum manageStatus) {
    this.manageStatus = manageStatus;
    return this;
  }

  /**
   * 관리 권한 상태
   * @return manageStatus
  */
  
  @ApiModelProperty(value = "관리 권한 상태")
  @JsonProperty("manageStatus")
  public ManageStatusEnum getManageStatus() {
    return manageStatus;
  }

  public void setManageStatus(ManageStatusEnum manageStatus) {
    this.manageStatus = manageStatus;
  }

  public MenuPermissionDetailResponseDto custom1Status(Custom1StatusEnum custom1Status) {
    this.custom1Status = custom1Status;
    return this;
  }

  /**
   * 기타 권한1 상태
   * @return custom1Status
  */
  
  @ApiModelProperty(value = "기타 권한1 상태")
  @JsonProperty("custom1Status")
  public Custom1StatusEnum getCustom1Status() {
    return custom1Status;
  }

  public void setCustom1Status(Custom1StatusEnum custom1Status) {
    this.custom1Status = custom1Status;
  }

  public MenuPermissionDetailResponseDto custom2Status(Custom2StatusEnum custom2Status) {
    this.custom2Status = custom2Status;
    return this;
  }

  /**
   * 기타 권한2 상태
   * @return custom2Status
  */
  
  @ApiModelProperty(value = "기타 권한2 상태")
  @JsonProperty("custom2Status")
  public Custom2StatusEnum getCustom2Status() {
    return custom2Status;
  }

  public void setCustom2Status(Custom2StatusEnum custom2Status) {
    this.custom2Status = custom2Status;
  }

  public MenuPermissionDetailResponseDto custom3Status(Custom3StatusEnum custom3Status) {
    this.custom3Status = custom3Status;
    return this;
  }

  /**
   * 기타 권한3 상태
   * @return custom3Status
  */
  
  @ApiModelProperty(value = "기타 권한3 상태")
  @JsonProperty("custom3Status")
  public Custom3StatusEnum getCustom3Status() {
    return custom3Status;
  }

  public void setCustom3Status(Custom3StatusEnum custom3Status) {
    this.custom3Status = custom3Status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MenuPermissionDetailResponseDto menuPermissionDetailResponseDto = (MenuPermissionDetailResponseDto) o;
    return Objects.equals(this.menuPermissionId, menuPermissionDetailResponseDto.menuPermissionId) &&
        Objects.equals(this.menuId, menuPermissionDetailResponseDto.menuId) &&
        Objects.equals(this.menuName, menuPermissionDetailResponseDto.menuName) &&
        Objects.equals(this.menuCode, menuPermissionDetailResponseDto.menuCode) &&
        Objects.equals(this.menuMapping, menuPermissionDetailResponseDto.menuMapping) &&
        Objects.equals(this.status, menuPermissionDetailResponseDto.status) &&
        Objects.equals(this.menuStatus, menuPermissionDetailResponseDto.menuStatus) &&
        Objects.equals(this.menuType, menuPermissionDetailResponseDto.menuType) &&
        Objects.equals(this.sortSeq, menuPermissionDetailResponseDto.sortSeq) &&
        Objects.equals(this.parentMenuId, menuPermissionDetailResponseDto.parentMenuId) &&
        Objects.equals(this.programId, menuPermissionDetailResponseDto.programId) &&
        Objects.equals(this.selectStatus, menuPermissionDetailResponseDto.selectStatus) &&
        Objects.equals(this.insertStatus, menuPermissionDetailResponseDto.insertStatus) &&
        Objects.equals(this.updateStatus, menuPermissionDetailResponseDto.updateStatus) &&
        Objects.equals(this.deleteStatus, menuPermissionDetailResponseDto.deleteStatus) &&
        Objects.equals(this.printStatus, menuPermissionDetailResponseDto.printStatus) &&
        Objects.equals(this.downStatus, menuPermissionDetailResponseDto.downStatus) &&
        Objects.equals(this.manageStatus, menuPermissionDetailResponseDto.manageStatus) &&
        Objects.equals(this.custom1Status, menuPermissionDetailResponseDto.custom1Status) &&
        Objects.equals(this.custom2Status, menuPermissionDetailResponseDto.custom2Status) &&
        Objects.equals(this.custom3Status, menuPermissionDetailResponseDto.custom3Status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(menuPermissionId, menuId, menuName, menuCode, menuMapping, status, menuStatus, menuType, sortSeq, parentMenuId, programId, selectStatus, insertStatus, updateStatus, deleteStatus, printStatus, downStatus, manageStatus, custom1Status, custom2Status, custom3Status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MenuPermissionDetailResponseDto {\n");
    sb.append("    menuPermissionId: ").append(toIndentedString(menuPermissionId)).append("\n");
    sb.append("    menuId: ").append(toIndentedString(menuId)).append("\n");
    sb.append("    menuName: ").append(toIndentedString(menuName)).append("\n");
    sb.append("    menuCode: ").append(toIndentedString(menuCode)).append("\n");
    sb.append("    menuMapping: ").append(toIndentedString(menuMapping)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    menuStatus: ").append(toIndentedString(menuStatus)).append("\n");
    sb.append("    menuType: ").append(toIndentedString(menuType)).append("\n");
    sb.append("    sortSeq: ").append(toIndentedString(sortSeq)).append("\n");
    sb.append("    parentMenuId: ").append(toIndentedString(parentMenuId)).append("\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    selectStatus: ").append(toIndentedString(selectStatus)).append("\n");
    sb.append("    insertStatus: ").append(toIndentedString(insertStatus)).append("\n");
    sb.append("    updateStatus: ").append(toIndentedString(updateStatus)).append("\n");
    sb.append("    deleteStatus: ").append(toIndentedString(deleteStatus)).append("\n");
    sb.append("    printStatus: ").append(toIndentedString(printStatus)).append("\n");
    sb.append("    downStatus: ").append(toIndentedString(downStatus)).append("\n");
    sb.append("    manageStatus: ").append(toIndentedString(manageStatus)).append("\n");
    sb.append("    custom1Status: ").append(toIndentedString(custom1Status)).append("\n");
    sb.append("    custom2Status: ").append(toIndentedString(custom2Status)).append("\n");
    sb.append("    custom3Status: ").append(toIndentedString(custom3Status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
