/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * ProgramActionModifyRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProgramActionModifyRequestDto {

  /**
   * 액션 유형 (RESTAPI : URL 기반, QUERYID : 쿼리 ID 기반)
   */
  public enum ActionTypeEnum {
    RESTAPI("RESTAPI"),
    
    QUERYID("QUERYID");

    private String value;

    ActionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionTypeEnum fromValue(String value) {
      for (ActionTypeEnum b : ActionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ActionTypeEnum actionType;

  /**
   * 권한 유형 (SELECT : 조회, INSERT : 등록, UPDATE : 수정, DELETE : 삭제, PRINT: 인쇄, DOWN: 다운로드, MANAGE: 관리)
   */
  public enum AuthTypeEnum {
    SELECT("SELECT"),
    
    INSERT("INSERT"),
    
    UPDATE("UPDATE"),
    
    DELETE("DELETE"),
    
    PRINT("PRINT"),
    
    DOWN("DOWN"),
    
    MANAGE("MANAGE");

    private String value;

    AuthTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthTypeEnum fromValue(String value) {
      for (AuthTypeEnum b : AuthTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private AuthTypeEnum authType;

  private String uri;


  public ProgramActionModifyRequestDto actionType(ActionTypeEnum actionType) {
    this.actionType = actionType;
    return this;
  }

  /**
   * 액션 유형 (RESTAPI : URL 기반, QUERYID : 쿼리 ID 기반)
   * @return actionType
  */
  @NotNull 
  @ApiModelProperty(example = "RESTAPI", required = true, value = "액션 유형 (RESTAPI : URL 기반, QUERYID : 쿼리 ID 기반)")
  @JsonProperty("actionType")
  public ActionTypeEnum getActionType() {
    return actionType;
  }

  public void setActionType(ActionTypeEnum actionType) {
    this.actionType = actionType;
  }

  public ProgramActionModifyRequestDto authType(AuthTypeEnum authType) {
    this.authType = authType;
    return this;
  }

  /**
   * 권한 유형 (SELECT : 조회, INSERT : 등록, UPDATE : 수정, DELETE : 삭제, PRINT: 인쇄, DOWN: 다운로드, MANAGE: 관리)
   * @return authType
  */
  @NotNull 
  @ApiModelProperty(example = "SELECT", required = true, value = "권한 유형 (SELECT : 조회, INSERT : 등록, UPDATE : 수정, DELETE : 삭제, PRINT: 인쇄, DOWN: 다운로드, MANAGE: 관리)")
  @JsonProperty("authType")
  public AuthTypeEnum getAuthType() {
    return authType;
  }

  public void setAuthType(AuthTypeEnum authType) {
    this.authType = authType;
  }

  public ProgramActionModifyRequestDto uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * 프로그램 매핑주소
   * @return uri
  */
  @NotNull 
  @ApiModelProperty(example = "/user/_*_/download", required = true, value = "프로그램 매핑주소")
  @JsonProperty("uri")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramActionModifyRequestDto programActionModifyRequestDto = (ProgramActionModifyRequestDto) o;
    return Objects.equals(this.actionType, programActionModifyRequestDto.actionType) &&
        Objects.equals(this.authType, programActionModifyRequestDto.authType) &&
        Objects.equals(this.uri, programActionModifyRequestDto.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionType, authType, uri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgramActionModifyRequestDto {\n");
    sb.append("    actionType: ").append(toIndentedString(actionType)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
