/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * ProgramResponseDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProgramResponseDto {

  private UUID programId;

  private String programName;

  private String programCode;

  private String programMapping;

  /**
   * 메뉴 사용 여부
   */
  public enum StatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private StatusEnum status;

  /**
   * 메뉴 여부
   */
  public enum MenuStatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    MenuStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MenuStatusEnum fromValue(String value) {
      for (MenuStatusEnum b : MenuStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MenuStatusEnum menuStatus;

  /**
   * 모바일 사용 여부
   */
  public enum MobileStatusEnum {
    ENABLE("ENABLE"),
    
    DISABLE("DISABLE");

    private String value;

    MobileStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MobileStatusEnum fromValue(String value) {
      for (MobileStatusEnum b : MobileStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private MobileStatusEnum mobileStatus;

  /**
   * 프로그램 매핑주소 고정여부
   */
  public enum ProgramMappingStatusEnum {
    FIXED("FIXED"),
    
    DEFAULT("DEFAULT");

    private String value;

    ProgramMappingStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProgramMappingStatusEnum fromValue(String value) {
      for (ProgramMappingStatusEnum b : ProgramMappingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private ProgramMappingStatusEnum programMappingStatus;

  private String remark;

  private UUID parentProgramId;

  public ProgramResponseDto programId(UUID programId) {
    this.programId = programId;
    return this;
  }

  /**
   * 프로그램 ID
   * @return programId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "프로그램 ID")
  @JsonProperty("programId")
  public UUID getProgramId() {
    return programId;
  }

  public void setProgramId(UUID programId) {
    this.programId = programId;
  }

  public ProgramResponseDto programName(String programName) {
    this.programName = programName;
    return this;
  }

  /**
   * 프로그램 이름
   * @return programName
  */
  
  @ApiModelProperty(example = "사용자 관리", value = "프로그램 이름")
  @JsonProperty("programName")
  public String getProgramName() {
    return programName;
  }

  public void setProgramName(String programName) {
    this.programName = programName;
  }

  public ProgramResponseDto programCode(String programCode) {
    this.programCode = programCode;
    return this;
  }

  /**
   * 프로그램 코드
   * @return programCode
  */
  
  @ApiModelProperty(example = "ACTN_100", value = "프로그램 코드")
  @JsonProperty("programCode")
  public String getProgramCode() {
    return programCode;
  }

  public void setProgramCode(String programCode) {
    this.programCode = programCode;
  }

  public ProgramResponseDto programMapping(String programMapping) {
    this.programMapping = programMapping;
    return this;
  }

  /**
   * 프로그램 매핑주소
   * @return programMapping
  */
  
  @ApiModelProperty(example = "AdminMain", value = "프로그램 매핑주소")
  @JsonProperty("programMapping")
  public String getProgramMapping() {
    return programMapping;
  }

  public void setProgramMapping(String programMapping) {
    this.programMapping = programMapping;
  }

  public ProgramResponseDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * 메뉴 사용 여부
   * @return status
  */
  
  @ApiModelProperty(value = "메뉴 사용 여부")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ProgramResponseDto menuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
    return this;
  }

  /**
   * 메뉴 여부
   * @return menuStatus
  */
  
  @ApiModelProperty(value = "메뉴 여부")
  @JsonProperty("menuStatus")
  public MenuStatusEnum getMenuStatus() {
    return menuStatus;
  }

  public void setMenuStatus(MenuStatusEnum menuStatus) {
    this.menuStatus = menuStatus;
  }

  public ProgramResponseDto mobileStatus(MobileStatusEnum mobileStatus) {
    this.mobileStatus = mobileStatus;
    return this;
  }

  /**
   * 모바일 사용 여부
   * @return mobileStatus
  */
  
  @ApiModelProperty(value = "모바일 사용 여부")
  @JsonProperty("mobileStatus")
  public MobileStatusEnum getMobileStatus() {
    return mobileStatus;
  }

  public void setMobileStatus(MobileStatusEnum mobileStatus) {
    this.mobileStatus = mobileStatus;
  }

  public ProgramResponseDto programMappingStatus(ProgramMappingStatusEnum programMappingStatus) {
    this.programMappingStatus = programMappingStatus;
    return this;
  }

  /**
   * 프로그램 매핑주소 고정여부
   * @return programMappingStatus
  */
  
  @ApiModelProperty(value = "프로그램 매핑주소 고정여부")
  @JsonProperty("programMappingStatus")
  public ProgramMappingStatusEnum getProgramMappingStatus() {
    return programMappingStatus;
  }

  public void setProgramMappingStatus(ProgramMappingStatusEnum programMappingStatus) {
    this.programMappingStatus = programMappingStatus;
  }

  public ProgramResponseDto remark(String remark) {
    this.remark = remark;
    return this;
  }

  /**
   * 비고
   * @return remark
  */
  
  @ApiModelProperty(value = "비고")
  @JsonProperty("remark")
  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public ProgramResponseDto parentProgramId(UUID parentProgramId) {
    this.parentProgramId = parentProgramId;
    return this;
  }

  /**
   * 부모 프로그램 ID
   * @return parentProgramId
  */
  @Valid 
  @ApiModelProperty(example = "017b6b3b-1b3b-4b6b-8b3b-1b3b4b6b8b3b", value = "부모 프로그램 ID")
  @JsonProperty("parentProgramId")
  public UUID getParentProgramId() {
    return parentProgramId;
  }

  public void setParentProgramId(UUID parentProgramId) {
    this.parentProgramId = parentProgramId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramResponseDto programResponseDto = (ProgramResponseDto) o;
    return Objects.equals(this.programId, programResponseDto.programId) &&
        Objects.equals(this.programName, programResponseDto.programName) &&
        Objects.equals(this.programCode, programResponseDto.programCode) &&
        Objects.equals(this.programMapping, programResponseDto.programMapping) &&
        Objects.equals(this.status, programResponseDto.status) &&
        Objects.equals(this.menuStatus, programResponseDto.menuStatus) &&
        Objects.equals(this.mobileStatus, programResponseDto.mobileStatus) &&
        Objects.equals(this.programMappingStatus, programResponseDto.programMappingStatus) &&
        Objects.equals(this.remark, programResponseDto.remark) &&
        Objects.equals(this.parentProgramId, programResponseDto.parentProgramId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(programId, programName, programCode, programMapping, status, menuStatus, mobileStatus, programMappingStatus, remark, parentProgramId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgramResponseDto {\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    programName: ").append(toIndentedString(programName)).append("\n");
    sb.append("    programCode: ").append(toIndentedString(programCode)).append("\n");
    sb.append("    programMapping: ").append(toIndentedString(programMapping)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    menuStatus: ").append(toIndentedString(menuStatus)).append("\n");
    sb.append("    mobileStatus: ").append(toIndentedString(mobileStatus)).append("\n");
    sb.append("    programMappingStatus: ").append(toIndentedString(programMappingStatus)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    parentProgramId: ").append(toIndentedString(parentProgramId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
