/**
* NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.
* This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.winitech.system.interfaces.inboundAdapter.spec;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionRegisterRequestDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;


import java.util.*;
import javax.annotation.Generated;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * ProgramActionBatchRegisterRequestDto
 */

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProgramActionBatchRegisterRequestDto {

  @Valid
  private List<@Valid ProgramActionRegisterRequestDto> actionList;

  public ProgramActionBatchRegisterRequestDto actionList(List<@Valid ProgramActionRegisterRequestDto> actionList) {
    this.actionList = actionList;
    return this;
  }

  public ProgramActionBatchRegisterRequestDto addActionListItem(ProgramActionRegisterRequestDto actionListItem) {
    if (this.actionList == null) {
      this.actionList = new ArrayList<>();
    }
    this.actionList.add(actionListItem);
    return this;
  }

  /**
   * Get actionList
   * @return actionList
  */
  @Valid 
  @ApiModelProperty(value = "")
  @JsonProperty("actionList")
  public List<@Valid ProgramActionRegisterRequestDto> getActionList() {
    return actionList;
  }

  public void setActionList(List<@Valid ProgramActionRegisterRequestDto> actionList) {
    this.actionList = actionList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramActionBatchRegisterRequestDto programActionBatchRegisterRequestDto = (ProgramActionBatchRegisterRequestDto) o;
    return Objects.equals(this.actionList, programActionBatchRegisterRequestDto.actionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgramActionBatchRegisterRequestDto {\n");
    sb.append("    actionList: ").append(toIndentedString(actionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
