/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.system.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.system.interfaces.inboundAdapter.spec.ProgramDetailResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramModifyRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramRegisterRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramStoreResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "Program", value = "Program", description = "프로그램을 관리하는 API Controller")
@RequestMapping("/api/v1/system")
public interface ProgramApi {

    /**
     * PATCH /program/{programId} : 프로그램 수정
     * 프로그램을 수정합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param programModifyRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program" },
        value = "프로그램 수정",
        nickname = "modifyProgram",
        notes = "프로그램을 수정합니다.",
        response = ProgramStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/program/{programId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<ProgramStoreResponseDto> modifyProgram(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) ProgramModifyRequestDto programModifyRequestDto
    );


    /**
     * POST /program : 프로그램 등록
     * 단일 프로그램을 등록합니다.
     *
     * @param programRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program" },
        value = "프로그램 등록",
        nickname = "registerProgram",
        notes = "단일 프로그램을 등록합니다.",
        response = ProgramStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/program",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<ProgramStoreResponseDto> registerProgram(
        @ApiParam(value = "") @Valid @RequestBody(required = false) ProgramRegisterRequestDto programRegisterRequestDto
    );


    /**
     * DELETE /program/{programId} : 프로그램 삭제
     * 프로그램을 삭제합니다. (hard delete)
     *
     * @param programId programId (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program" },
        value = "프로그램 삭제",
        nickname = "removeProgram",
        notes = "프로그램을 삭제합니다. (hard delete)",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/program/{programId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removeProgram(
        @ApiParam(value = "programId", required = true) @PathVariable("programId") UUID programId
    );


    /**
     * GET /program : 프로그램 목록 조회
     * 모든 프로그램을 조회합니다.
     *
     * @param page 페이지 번호 (0부터 시작) (optional)
     * @param pageSize 페이지 사이즈 (optional)
     * @param searchType 검색 타입 (optional)
     * @param searchKeyword 검색어 (optional)
     * @param menuStatus 메뉴 사용 여부 (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program" },
        value = "프로그램 목록 조회",
        nickname = "searchAllProgram",
        notes = "모든 프로그램을 조회합니다.",
        response = ProgramResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/program",
        produces = { "application/json" }
    )
    CommonResponse<List<ProgramResponseDto>> searchAllProgram(
        @ApiParam(value = "페이지 번호 (0부터 시작)") @Valid @RequestParam(value = "page", required = false) Integer page,
        @ApiParam(value = "페이지 사이즈") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,
        @ApiParam(value = "검색 타입", allowableValues = ", PROGRAM_NAME, PROGRAM_CODE") @Valid @RequestParam(value = "searchType", required = false) String searchType,
        @ApiParam(value = "검색어") @Valid @RequestParam(value = "searchKeyword", required = false) String searchKeyword,
        @ApiParam(value = "메뉴 사용 여부", allowableValues = "ENABLE, DISABLE") @Valid @RequestParam(value = "MenuStatus", required = false) String menuStatus
    );


    /**
     * GET /program/{programId} : 단일 프로그램 조회
     * 단일 프로그램을 조회합니다.
     *
     * @param programId 프로그램 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program" },
        value = "단일 프로그램 조회",
        nickname = "searchProgram",
        notes = "단일 프로그램을 조회합니다.",
        response = ProgramDetailResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramDetailResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/program/{programId}",
        produces = { "application/json" }
    )
    CommonResponse<ProgramDetailResponseDto> searchProgram(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId
    );

}
