/**
 * NOTE: 이 클래스 파일은 자동 생성된 파일입니다. 이 파일을 직접 수정하지 마십시오.  
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.winitech.system.interfaces.inboundAdapter.spec;

import com.winitech.common.response.CommonResponse;

import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionBatchRegisterRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionBatchStoreResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionDetailResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionModifyRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionRegisterRequestDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionResponseDto;
import com.winitech.system.interfaces.inboundAdapter.spec.ProgramActionStoreResponseDto;
import java.util.UUID;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(tags = "Program Action", value = "Program Action", description = "프로그램의 액션을 관리하는 API Controller")
@RequestMapping("/api/v1/system")
public interface ProgramActionApi {

    /**
     * PATCH /program/{programId}/action/{actionId} : 프로그램 액션 수정
     * 프로그램 액션을 수정합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param actionId 프로그램 액션 ID (required)
     * @param programActionModifyRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 수정",
        nickname = "modifyProgramAction",
        notes = "프로그램 액션을 수정합니다.",
        response = ProgramActionStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramActionStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/program/{programId}/action/{actionId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<ProgramActionStoreResponseDto> modifyProgramAction(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "프로그램 액션 ID", required = true) @PathVariable("actionId") UUID actionId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) ProgramActionModifyRequestDto programActionModifyRequestDto
    );


    /**
     * POST /program/{programId}/action : 프로그램 액션 등록
     * 단일 프로그램 액션을 등록합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param programActionRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 등록",
        nickname = "registerProgramAction",
        notes = "단일 프로그램 액션을 등록합니다.",
        response = ProgramActionStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramActionStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/program/{programId}/action",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<ProgramActionStoreResponseDto> registerProgramAction(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) ProgramActionRegisterRequestDto programActionRegisterRequestDto
    );


    /**
     * POST /program/{programId}/action/batch : 프로그램 액션 일괄 등록
     * 단일 프로그램의 액션을 여러건 등록합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param programActionBatchRegisterRequestDto  (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 일괄 등록",
        nickname = "registerProgramActionBatch",
        notes = "단일 프로그램의 액션을 여러건 등록합니다.",
        response = ProgramActionBatchStoreResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramActionBatchStoreResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/program/{programId}/action/batch",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    CommonResponse<ProgramActionBatchStoreResponseDto> registerProgramActionBatch(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "") @Valid @RequestBody(required = false) ProgramActionBatchRegisterRequestDto programActionBatchRegisterRequestDto
    );


    /**
     * DELETE /program/{programId}/action/{actionId} : 프로그램 액션 삭제
     * 프로그램 액션을 삭제합니다. (hard delete)
     *
     * @param programId programId (required)
     * @param actionId actionId (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 삭제",
        nickname = "removeProgramAction",
        notes = "프로그램 액션을 삭제합니다. (hard delete)",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/program/{programId}/action/{actionId}",
        produces = { "application/json" }
    )
    CommonResponse<String> removeProgramAction(
        @ApiParam(value = "programId", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "actionId", required = true) @PathVariable("actionId") UUID actionId
    );


    /**
     * GET /program/{programId}/action : 프로그램 액션 목록 조회
     * 모든 프로그램을 조회합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param page 페이지 번호 (0부터 시작) (optional)
     * @param pageSize 페이지 사이즈 (optional)
     * @param searchType 검색 타입 (optional)
     * @param searchKeyword 검색어 (optional)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 목록 조회",
        nickname = "searchAllProgramAction",
        notes = "모든 프로그램을 조회합니다.",
        response = ProgramActionResponseDto.class,
        responseContainer = "List"
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramActionResponseDto.class, responseContainer = "List")
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/program/{programId}/action",
        produces = { "application/json" }
    )
    CommonResponse<List<ProgramActionResponseDto>> searchAllProgramAction(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "페이지 번호 (0부터 시작)") @Valid @RequestParam(value = "page", required = false) Integer page,
        @ApiParam(value = "페이지 사이즈") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,
        @ApiParam(value = "검색 타입", allowableValues = ", PROGRAM_NAME, PROGRAM_CODE, URL") @Valid @RequestParam(value = "searchType", required = false) String searchType,
        @ApiParam(value = "검색어") @Valid @RequestParam(value = "searchKeyword", required = false) String searchKeyword
    );


    /**
     * GET /program/{programId}/action/{actionId} : 단일 프로그램 액션 조회
     * 단일 프로그램 액션을 조회합니다.
     *
     * @param programId 프로그램 ID (required)
     * @param actionId 프로그램 액션 ID (required)
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "단일 프로그램 액션 조회",
        nickname = "searchProgramAction",
        notes = "단일 프로그램 액션을 조회합니다.",
        response = ProgramActionDetailResponseDto.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = ProgramActionDetailResponseDto.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/program/{programId}/action/{actionId}",
        produces = { "application/json" }
    )
    CommonResponse<ProgramActionDetailResponseDto> searchProgramAction(
        @ApiParam(value = "프로그램 ID", required = true) @PathVariable("programId") UUID programId,
        @ApiParam(value = "프로그램 액션 ID", required = true) @PathVariable("actionId") UUID actionId
    );


    /**
     * GET /program/action/syncAll : 프로그램 액션 전체 동기화
     * 프로그램 액션을 전체 동기화합니다.
     *
     * @return OK (status code 200)
     */
    @ApiOperation(
        tags = { "Program Action" },
        value = "프로그램 액션 전체 동기화",
        nickname = "syncAllProgramAction",
        notes = "프로그램 액션을 전체 동기화합니다.",
        response = String.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/program/action/syncAll",
        produces = { "application/json" }
    )
    CommonResponse<String> syncAllProgramAction(
        
    );

}
